### ISSUE TITLE
Crash in AbstractActionSheetPicker.m line 36

### ISSUE THREAD

**Issue by ljonesfl** [skywinder/ActionSheetPicker-3.0#101]
uname(&systemInfo);

![abstractactionsheetpickerm](https://cloud.githubusercontent.com/assets/1099983/5145674/be997a2c-7172-11e4-99b5-317e47f5fa4f.png)

**Comment by skywinder** [comment]
I'm tentatively closing this one then, since it seems to be either a configuration issue or an issue with Xcode. Feel free to reopen this if you have any new insights :v:
