### ISSUE TITLE
Works on simulator - never starts on device.

### ISSUE THREAD

**Issue by mworsnop** [skywinder/ActionSheetPicker-3.0#118]
Below is the error log from the iPhone device. I am not sure what its trying to reference?  The app works great on the simulator.

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  0

Dyld Error Message:
  Library not loaded: @rpath/CoreActionSheetPicker.framework/CoreActionSheetPicker
  Referenced from: /private/var/mobile/Containers/Bundle/Application/6C4ABDB3-9FC6-41C4-A53C-79F083A1740E/NutriLife.app/NutriLife
  Reason: image not found
  Dyld Version: 353.6

Binary Images:
0x1fe20000 - 0x1fe43fff dyld armv7s  <8ffd813a380c333bbd4a25e1dbe05715> /usr/lib/dyld

**Comment by skywinder** [comment]
I'm tentatively closing this one then, since it seems to be either a configuration issue or an issue with Xcode. Feel free to reopen this if you have any new insights  :v:

**Comment by kompw** [comment]
have this same problem! I don't know how to solve it, but can copy the source code and change CoreActionSheetPicker.h (import how #import "AbstractActionSheetPicker.h" .....)

work for me

**Comment by skywinder** [comment]
@mworsnop @kompw Please, check the last version. It seems, that I fix it.

The problem was in missing Embedded library. http://stackoverflow.com/questions/26104975/dyld-library-not-loaded-rpath-libswiftcore-dylib-image-not-found

**Comment by paramadharmika** [comment]
Here what is work for me, using Objective C project
- Import the core action sheet picker to your project
- Add core action sheet picker to embedded libraries of your targets project properties

And that's it, it will run on your device
