### ISSUE TITLE
Light status bar style

### ISSUE THREAD

**Issue by georgschlenkhoff** [skywinder/ActionSheetPicker-3.0#119]
I use light status bar style for my app. However, picker shows default (black) status bar. Is there an easy way to use light (white) status bar?

**Comment by jpayan** [comment]
It should work to add this code in the @implementation of SWActionSheetVC
```- (UIStatusBarStyle)preferredStatusBarStyle
{
    return [UIApplication sharedApplication].statusBarStyle;
}```

**Comment by skywinder** [comment]
@georgschlenkhoff, Confirm, I occur this bug and add special segment control in example to test this behaviour (bug occurs with `UIBarStyleBlack`).

@jpayan which controller you mean as `SWActionSheetVC`?
If you have idea, how to fix it - please, create a pull-request. Or explain it in details here. Thanks.
