### ISSUE TITLE
Swift; Does not conform to protocol

### ISSUE THREAD

**Issue by switchCTRL** [skywinder/ActionSheetPicker-3.0#120]
![bildschirmfoto 2014-12-23 um 12 08 40](https://cloud.githubusercontent.com/assets/7301984/5537122/9104835c-8a9c-11e4-82dc-dd8ed888760e.png)

Hey, i'm getting this Error and can´t resolve them. I would like to use the ActionSheetCustomPicker. Any suggestions?

Best regards

**Comment by skywinder** [comment]
@switchCTRL any updates?

**Comment by switchCTRL** [comment]
I tryed to add the protocol and the methods but it does not work. Now i use the string picker. It works better.... I think it is another swift/Xcode bug...
