### ISSUE TITLE
Changing Units on Countdown View

### ISSUE THREAD

**Issue by Jasonvdm** [skywinder/ActionSheetPicker-3.0#124]
I am building a custom timer and this action sheet is great for editing the timer, however, the countdown timer is built in hours and minutes and i need minutes and seconds. Is there an easy way for me to modify this myself? 

Alternatively, is there any way to introduce multiple columns for the string picker? Right now you can just input rows. Some other action sheet pickers allow you to input 2 dimensional arrays.

**Comment by skywinder** [comment]
@Jasonvdm feel free to reopen, if you have any question.
