### ISSUE TITLE
How To Pass  array Of Dictionraies to picker 

### ISSUE THREAD

**Issue by perlasivakrishna** [skywinder/ActionSheetPicker-3.0#126]
I have Arrray of Dictionary.I want All complnets of  partcular object in a row. For Ex.

Class
{
       {  
             Name:Ramu
              Id:   001
        }
      {  
             Name:Siva
              Id:   002
        }

}
I want show names in picker And get Id on done Click.

**Comment by skywinder** [comment]
There is very special case to implement native support for this.
All you have to do is create array with all object, present it, and then handle response and do whatever you want.

**Comment by perlasivakrishna** [comment]
k Thanks for resposne.I have already done by creating array.
