### ISSUE TITLE
Date Picker not aligned well on landscape iPhone 6 Plus

### ISSUE THREAD

**Issue by jpike88** [skywinder/ActionSheetPicker-3.0#129]
![photo 26-01-2015 4 00 59 pm](https://cloud.githubusercontent.com/assets/9585787/5895467/6de2ac42-a56c-11e4-94bf-06f0d6363bac.png)

**Comment by skywinder** [comment]
@jpike88 Can you explain, how it should be aligned?

**Comment by jpike88** [comment]
Shouldn't the bottom of the scroller be flush with the bottom of the screen?

**Comment by skywinder** [comment]
@jpike88 Ok, thats right. In the picture it's quite unclear where is the bottom. The picker shouldn't be so hight. Thanks for mention it!
I quite busy now to fix it. So, can't promise a quick fix. But ready to review a PR.
