### ISSUE TITLE
Invalid target/action

### ISSUE THREAD

**Issue by malakiya** [skywinder/ActionSheetPicker-3.0#130]
Hi, i was trying to use the ActionSheetPicker but i have a problem

I created an UITextField in my storyboard and them i created an IBAction with Tocuh Down event and looks like this

```
- (IBAction)selectCountryOrigin:(id)sender {
    NSArray *colors = [NSArray arrayWithObjects:@"Red", @"Green", @"Blue", @"Orange", nil];
    
    [ActionSheetStringPicker showPickerWithTitle:@"Select a Color"
                                            rows:colors
                                initialSelection:0
                                       doneBlock:nil
                                     cancelBlock:nil
                                          origin:sender];
}
```

and when i tried to select some value from the picker i have the following error

```
2015-01-29 15:12:03.162 NSA[21079:2175861] Invalid target/action ( nil / <null selector> ) combination used for ActionSheetPicker
```

I feel a fool xD
Sorry

**Comment by skywinder** [comment]
You should add some block to done, not `nil`.

try to put to doneBlock:

```obj-c
    ActionStringDoneBlock done = ^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
        NSLog(@"selectedValue = %@", selectedValue);
    };
```

More details you can find in example project.

**Comment by skywinder** [comment]
@malakiya You figured out how to use a `ActionStringDoneBlock`?

**Comment by malakiya** [comment]
Yes, i get it. Thanks a lot!

I have one more question:
I use a UITextField, when i run in my phone i select an element from the ActionSheetPicker and immediately shows me the keyboard.

**Comment by skywinder** [comment]
@malakiya it's default behaviour of `UITextField`. Try to implement delegate method as it described here: http://stackoverflow.com/questions/5615806/disable-uitextfield-keyboard

**Comment by malakiya** [comment]
Thank you very much!
