### ISSUE TITLE
Trying to customize ActionSheetStringPicker, but don't conform to DataSource?

### ISSUE THREAD

**Issue by dilizarov** [skywinder/ActionSheetPicker-3.0#133]
In your walk-through, it states to customize the ActionSheetPicker, you need to use the delegate `ActionSheetCustomPickerDelegate` and then make `func actionSheetPicker(actionSheetPicker: AbstractActionSheetPicker!, configurePickerView pickerView: UIPickerView!) {}`

When I do this, my UIViewController throws an error that says it doesn't conform to `UIPickerViewDataSource`. This isn't covered in the walk-through, and I don't think it should be happening. 

I'm basically trying to mimik this:
https://raw.githubusercontent.com/skywinder/ActionSheetPicker-3.0/master/Screenshots/string.png

I expected to find it in one of the Objective-C or Swift examples, but apparently it isn't there.

**Comment by skywinder** [comment]
Hi. Thanks for pointing out. I will check this method.

Regarding your questions:
What exactly you want to customize?
By your link it's simple `ActionSheetStringPicker` you can use it as is.

**Comment by dilizarov** [comment]
I got the buttons customized, but while I am using ActionSheetStringPicker, I dislike how the background color of the ActionSheetStringPicker is white whereas the ActionSheet itself has a grayish color, so I was hoping to make them both the same color.

**Comment by skywinder** [comment]
@dilizarov thank you for mention it! I will fix it today!

**Comment by skywinder** [comment]
Fixed in #136
