### ISSUE TITLE
ActionSheetDatePicker memory footprint

### ISSUE THREAD

**Issue by jpike88** [skywinder/ActionSheetPicker-3.0#134]
Hi,

This is minor, but try running your example, and watch the memory as you open the pickers. Now try the date picker. The memory jumps up by WAY more. Is this just because it's a date picker, or is there possibly a retain cycle?

**Comment by skywinder** [comment]
Hi! Thanks for mention on it.
I confirm, for some reason memory is not free after `ActionSheetDatePicker` called, all other pickers works as expected.

![screen shot 2015-02-09 at 13 30 28](https://cloud.githubusercontent.com/assets/3356474/6105452/ed49ad3e-b05f-11e4-98bb-8d52fdd98d72.png)

**Comment by jpike88** [comment]
Any luck on it? That's a big issue and is causing memory leaks/crashes for customers

**Comment by skywinder** [comment]
@jpike88 not yet. I tried to find, what  can cause this leak, but didn't find anything wrong in code. It's strange, but leak appears only with `ActionSheetDatePicker`. Any other pickers works correct.

**Comment by jpike88** [comment]
Is this Apple's fault?

**Comment by skywinder** [comment]
@jpike88  I'm not 100% sure, but seems like Apple's bug. Since all other pickers works exactly the same way and they are works correct.

**Comment by jpike88** [comment]
You should probably submit this issue to Apple's bug tracker lol

**Comment by skywinder** [comment]
@jpike88 Already :)
I hope it will disappear in new versions.

**Comment by skywinder** [comment]
Since it's Apple's bug, not I'm going to close this issue

**Comment by Bhide** [comment]
The `ActionSheetStringPicker` too leaks memory. I found this when I am using it on a modally presented `UIViewController`. I think we should reopen this issue.
Refer #358
