### ISSUE TITLE
How to works with ActionStringDoneBlock in Swift?

### ISSUE THREAD

**Issue by manzznam** [skywinder/ActionSheetPicker-3.0#137]
I alwas get this error when i try to write to the "index" variable in this "done" block. I took the code from the Swift Example. A println works inside the block but access to any variable doesn't.

@IBAction func pickerTouched(sender: UIButton) {
        var index = 0
        
        let done: ActionStringDoneBlock = {(picker: ActionSheetStringPicker!, selectedIndex: NSInteger!, selectedValue : AnyObject!) in            
            index = selectedIndex
            return
        }
        
        ActionSheetStringPicker.showPickerWithTitle("Nav Bar From Picker", rows: ["One", "Two", "A lot"], initialSelection: 1, doneBlock: done, cancelBlock: {ActionStringCancelBlock in return }, origin: sender.superview!.superview)
    }

![screenshot 2015-02-12 16 30 13](https://cloud.githubusercontent.com/assets/3786112/6170376/83f3f58e-b2d4-11e4-9ca9-e0d91e8da30a.png)

**Comment by skywinder** [comment]
Hi, please, check your `origin`. I belive it should be not `sender.superview!.superview` (most likely it `nil`) but `sender.superview`.

**Comment by manzznam** [comment]
Sorry that doesn't work neither. In my project i use a ContainerViewController as the window!.rootViewController. In the container i create a navigationController: mainNavigationController = UINavigationController(rootViewController: mainViewController). The mainViewController contains the Button for displaying the picker. Probably my views are different from the example and so is my origin then. But how do i know which is the right origin? Has the origin be the same view where the picker is shown?

**Comment by skywinder** [comment]
Usually origin should be just the view, that call this picker. Such complex `sender.superview!.superview` expression should be only when you present picker on iPad from `tableviewcell` - to set correct position of the picker.

So, try to use just `origin` in your case. And let me know, if you still this error. Also, check, that you sender is not `nil`!

**Comment by manzznam** [comment]
What do you exactly mean with just use "origin"? I mean what parameter should i use for "origin"?

**Comment by skywinder** [comment]
sender.view

**Comment by manzznam** [comment]
In my case sender is UIButton and does not have a property "sender.view". I tried also "view" and "self.view" as origin but i get the same error...

**Comment by skywinder** [comment]
oops, i mean just `sender` (cuz UIButton is subclass of view). Is it works?

**Comment by manzznam** [comment]
No that doesn't work either. I just tried to access a variable in your original Swift-Example project (fresh checkout) and there i get the same error. Could you provide some sample code how i can use the selectedIndex of the Picker in my ViewController?

**Comment by skywinder** [comment]
Yes, of course! You can fins a lot of examples in that repo. Just clone this repo and open `xcworspace` file.

**Comment by manzznam** [comment]
I only found <code>doneBlock: {ActionStringDoneBlock in return}</code> in your Swift sample code. But there is no example with a "programmed out" block of the doneBlock. I mean how can i write a correct done block in which i set the selected index e.g. <code>self.selectedIndex = selectedIndex</code>

**Comment by loomtronic** [comment]
I am getting the same thing.  Would be great to have a clear, working example of how to get the value from the picker

**Comment by skywinder** [comment]
@loomtronic is this error exists in example project? Can you point it out? Because I'm confused and have no idea, how to reproduce it.

**Comment by loomtronic** [comment]
I haven't tried it in the example project... the example project I have not seen any Swift examples for this code.  The Swift examples only have doneBlock: {ActionStringDoneBlock in return}, not the code @manzznam is using

**Comment by manzznam** [comment]
Yes that was my question as well. I only need some sample Swift code how to get the selected Index in that doneBlock.

**Comment by skywinder** [comment]
@manzznam, @loomtronic  Yes, you're right! It's a good question, thank you!
**fucking_closure_syntax**! Spend an hour to figure out, how to do it!
Check examples now.

**Comment by manzznam** [comment]
Thank you, now it's working. Great job
