### ISSUE TITLE
Question: Is there any way to change month's languages in date picker mode?

### ISSUE THREAD

**Issue by malakiya** [skywinder/ActionSheetPicker-3.0#141]
Is there any way to change month's languages in date picker?

**Comment by skywinder** [comment]
`ActionSheetDatePicker` has a property `locale`, that linked with `UIDatePicker` `locale` property. Did you try to set it?

**Comment by malakiya** [comment]
it works, thanks!

**Comment by keremtiryaki** [comment]
a sample for swift
`datePicker.locale = NSLocale(localeIdentifier: "en_EN")`

**Comment by RafaRuiz** [comment]
I didn't understand, how do I have to set the "locale" property?

**Comment by eyyubzademireli** [comment]
Hi. Azerbaijani language doesn't work. How can I fix it? locale="az"
