### ISSUE TITLE
Failed to allocate data stores for 10000 rows in section 0

### ISSUE THREAD

**Issue by jpike88** [skywinder/ActionSheetPicker-3.0#142]
CoreFoundation
___exceptionPreprocess
libobjc.A.dylib
_objc_exception_throw
CoreFoundation
[NSException raise:format:]
Foundation
[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
UIKit
[UISectionRowData refreshWithSection:tableView:tableViewRowData:]
UIKit
[UITableViewRowData numberOfRows]
UIKit
[UITableView noteNumberOfRowsChanged]
UIKit
[UITableView reloadData]
UIKit
[UIPickerView layoutSubviews]
UIKit
[_UIDatePickerView layoutSubviews]
UIKit
[UIPickerView selectedRowInComponent:]
UIKit
[_UIDatePickerMode loadDate:animated:]
UIKit
[_UIDatePickerMode_DateAndTime loadDate:animated:]
UIKit
[_UIDatePickerView _loadDate:animated:]
UIKit
[_UIDatePickerView _setDate:animated:forced:]
UIKit
[_UIDatePickerView setTimeZone:]
Report Writer Plus
ActionSheetDatePicker.m line 157 in [ActionSheetDatePicker configuredPickerView]
Report Writer Plus
AbstractActionSheetPicker.m line 200 in [AbstractActionSheetPicker showActionSheetPicker]
Report Writer Plus
ActionSheetDatePicker.m line 73 in [ActionSheetDatePicker showPickerWithTitle:datePickerMode:selectedDate:doneBlock:cancelBlock:origin:]

**Comment by skywinder** [comment]
Hmm .. Since this project is based on `UIPickerView`, did you try to create a` UIPickerView` 1000 elements? It works?

Anyway, according Apple's HIG - you should avoid put too many item in picker. Use UITableView instead.

**Comment by jpike88** [comment]
This issue is with ActionSheetDatePicker, there's no list to populate

**Comment by skywinder** [comment]
Can't reproduce it. Anyway, creating picker with 10000 rows is ridiculous.
