### ISSUE TITLE
How to run example project?

### ISSUE THREAD

**Issue by SomeAreDead** [skywinder/ActionSheetPicker-3.0#145]
Hi, been planning to use ASP3 for some time but other pressures dragged me away, came back to it, refreshed download and now none of the example projects compile - changes to initwithtitle method of the ActionSheetDatePicker class I think

If I change the code to use a newer version I then get linking errors...

Tried removing ASP3 entirely and downloading again and as a ZIP - same issue....

Any ideas

**Comment by skywinder** [comment]
@SomeAreDead Please, explain problem more detail: how to reproduce this issue?

**Comment by SomeAreDead** [comment]
As I said, just download the package either as ZIP or using GitHub and the examples don't compile.

**Comment by skywinder** [comment]
@SomeAreDead  
There is a 4 project inside workspace and 3 examples. Which one?
 And all of them compiled successful for me.
What the Os X version? Xcode version? Simulator or device?

**Comment by SomeAreDead** [comment]
The issue I get is not a version of environment one. The issue is that in the Objective C example the InitWithTitle calls in the example do not match any of those defined in the source. I also have the library objects showing up as red (ones with a shield icon). Sorry can't get to my Mac to be more specific - if you look at my original post that sums it up. Source files don't match the examples - I have removed the component and all of it's part entirely from the machine and re-downloaded it and I still get the same error. Unless there is some mismatch between what's now in the source and some compiled object I still have somewhere lurking that I cannot see...

**Comment by skywinder** [comment]
@SomeAreDead it's really weird. I also re-download this project and it's works.
Since you are first, who can't run the example project - I can't suggest anything to you right now..

**Comment by SomeAreDead** [comment]
Most annoying thing is it was working until I did another fetch... I'm guessing somehow part of the project is not being overwritten.... I'll look again when I can

**Comment by SomeAreDead** [comment]
OK, so I clear my machine of all traces of ActionSheetPicker and do a new Clone to my desktop using GitHub. If I open Example-for-iOS-7-and-6 and run it it works first time. However if I open Obj-C-Example in XCode it will neither compile or run. 
![screen shot 2015-03-02 at 13 33 30](https://cloud.githubusercontent.com/assets/1868139/6441539/c129a36c-c0e0-11e4-9f33-f99726c3d257.png)
It appears to be using a version of InitWithTitle that isn't in the source...
![screen shot 2015-03-02 at 13 35 01](https://cloud.githubusercontent.com/assets/1868139/6441557/f7a6e42c-c0e0-11e4-9b63-0180b5affac0.png)
In addition there are some highlighted objects in the explorer
![screen shot 2015-03-02 at 13 36 10](https://cloud.githubusercontent.com/assets/1868139/6441578/1e25b84e-c0e1-11e4-9264-02320efe891e.png)

I have tried precompiling the CoreActionSheetPicker app.
If I fix the errors and use one of the InitWithTitle methods that are available I think get linking errors.

Is it that some relative path is not correct by default? I have downloaded to my desktop...

The SwiftExample also fails with an error that seems to mean it cannot see the core objects
![screen shot 2015-03-02 at 13 38 11](https://cloud.githubusercontent.com/assets/1868139/6441610/780cf37c-c0e1-11e4-88b0-4bb45c169080.png)

Feels to me like something is wrong with the overall structure of the project.

**Comment by SomeAreDead** [comment]
p.s. XCode 6.1 and OSX bang up to date

**Comment by SomeAreDead** [comment]
It also looks like the String picker also uses a tapDismissAction which also doesn't exist in source, and another InitWithTitle...
![screen shot 2015-03-02 at 13 49 42](https://cloud.githubusercontent.com/assets/1868139/6441805/03e1d876-c0e3-11e4-80ff-784bda187c0a.png)

**Comment by skywinder** [comment]
@SomeAreDead ok, I got it. You can't just open `xcodeproj` file.
As I describe in [README.md](https://github.com/skywinder/ActionSheetPicker-3.0#example-projects):  you should open `open Example.xcworkspace`
And then open ActionSheetPicker project inside and run it!

**Comment by SomeAreDead** [comment]
So to put this into my own project (pre Swift, pre storyboard, ancient and all hand coded) what source do I integrate? Just the CoreActionSheetPicker folder?

**Comment by skywinder** [comment]
No, it's framework directory, it does not contain picker code at all.
As also described in readme:
> The "old school" way is manually add to your project all from "Pickers" folder and import necessary headers.
