### ISSUE TITLE
upside down portrait mode displays incorrectly

### ISSUE THREAD

**Issue by VinceW331** [skywinder/ActionSheetPicker-3.0#146]
hello skywinder, 
my situation was same as  " upside down portrait mode displays incorrectly on iPhone 4S device/emulator #52 ".

that seems like only happen on Phone( iPhone5s/iPhone6 plus/.. , simulator or device).

I tried the example (ActionSheetPicker), that using portrait and upside/down mode
if choosing any kind of iPad simulator, that's work fine in portrait and upside/down.
if choosing any kind of iPhone, in upside/down mode, the Picker appears upside down respect to the rest of the app.

Xcode: 6.1.1 
simulator: iOS 8.1
device(iPhone6 plus): iOS 8.1.3
ActionSheetPicker-3.0:  1.3.13 

Can you help me check it~? thanks a lot.

**Comment by skywinder** [comment]
How to reproduce this bug? In example project picker automatically dismiss in case of change orientation, so I can't figure out, how to reproduce it.

**Comment by VinceW331** [comment]
hi skywinder , 
there's what I did.


1) in "General" tab of "ActionSheetPicker" target, select "Device Orientation", turn Udside Down to checked.

2) in ActionSheetPickerTableViewController.m , about line 35, I added a catologe:
@implementation UINavigationController(testUpsideDown)
- (BOOL)shouldAutorotate
{
    return self.visibleViewController.shouldAutorotate;
}
- (NSUInteger)supportedInterfaceOrientations
{
    return self.visibleViewController.supportedInterfaceOrientations;
}
@end 

3) and rewrite ActionSheetPickerTableViewController's method:
- (BOOL)shouldAutorotate  // > iOS 6 autorotation
{
    return YES;
}

- (NSUInteger)supportedInterfaceOrientations // > iOS 6 autorotation
{
    return (UIInterfaceOrientationMaskPortrait | UIInterfaceOrientationMaskPortraitUpsideDown);
}

4) build and run iPhone simulator

5) rotate simulator 180 degree

6) click the blue "barButton" (maybe any one)

thanks for reply ~

**Comment by skywinder** [comment]
@VinceW331  fixed in `1.5.0`

**Comment by VinceW331** [comment]
great thanks to you and dtrauger :D  you save me~~~
