### ISSUE TITLE
Share Extension wont work

### ISSUE THREAD

**Issue by ViktorLajos** [skywinder/ActionSheetPicker-3.0#147]
Hello all!

I found this library, for making awesome pickers, but it wont wokr in SHareing exension (ios8), because it uses UIApplication.sharedApplication, witch is not reachable in extensions. Are you planning some solutions for this?

**Comment by skywinder** [comment]
@ViktorLajos Hi. Thanks for mention it. I don't know, how to get workaround for this limitation.
So, now I can suggest 2 methods to integrate this project:

1. `CocoaPods`
2. manual move `Pickers` folder to you project.

**Comment by ViktorLajos** [comment]
I think, you misunderstood me: So the problem is, when you make a Share Extension (or any kind of extension) inside the mother project, you can't use the sharedApplication property... It's a limitation of App Extensions, and it drops an error: "'sharedApplication' is unavailable: not available iOS (App Extension)". And the library uses many places the sharedApplication, so xcode won't compile it inside the extension. I tried to fix this issue, I added a processor macro to the ext., and I rewrote the places where you call the sharedApplication, to other, not too correct codes with #ifdef... it compiles, but I think I did something wrong because it works on iPad, but not on iPhone

**Comment by skywinder** [comment]
My fault. (I have a "Frameworks" meaning in my mind)

Yes, this feature make sense.
This project use sharedApplication to check orientation, and to presenting view on iPhones. So, probably it will be a tricky to adopt it for Extensions.
Can you share your code (as a branch from master) to review it?

**Comment by ViktorLajos** [comment]
I deleted my codes, because they won't work (and it wasn't source controlled)... the only one thing what worked correct is get the current orientation by comparing the [[UIScreen mainScreen] bounds].size.width with the height (and you can get the origin of the screen right with [[UIScreen mainScreen] bounds].origin)... the other changes were hacky solutions (like: return the accepted orientations always true)

**Comment by skywinder** [comment]
@ViktorLajos  I found new checkbox in `Xcode 6.3` 
![screen shot 2015-04-17 at 11 02 12](https://cloud.githubusercontent.com/assets/3356474/7198089/526b07b0-e4f1-11e4-82ca-74306f3fb24f.png)

It should help to build proper extension kit.

**Comment by alexszilagyi** [comment]
@skywinder : where I can find that option?

**Comment by alexszilagyi** [comment]
@skywinder: I've managed to fix it in the end by upgrading to ```0.35.0``` () version of cocadpods.
Uninstall: ```sudo gem uninstall cocoapods```
Install older version: ```sudo gem install cocoapods -v 0.35.0```. Hope it helps! :smile:

**Comment by skywinder** [comment]
@alexszilagyi sorry, but how `cocoapods` is related with incompatibility of this project with Extensions?

@ViktorLajos do you now, what can be alternative to `sharedApplication` in extensions? How to ensure, that we present picker above all other views?

**Comment by alexszilagyi** [comment]
@skywinder: no idea, but I can tell you for sure that I've spent several hours to figure it out and that was my solution...

**Comment by skywinder** [comment]
@ViktorLajos Seems if it's not impossible, at least it's not easy to make it work in App Extension. So I'm going to close this issue. Let me know, if you find solution.

**Comment by shikharsinghal** [comment]
Please have a look at this [AFNetworking issue](https://github.com/CocoaPods/CocoaPods/issues/3191)
would adapting the code snippet for the pod file help?

**Comment by skywinder** [comment]
@shikharsinghal problem not in the Pods. We are using  `[UIApplication sharedApplication]` inside the code, that won't work in extension.
