### ISSUE TITLE
Integrating with nicklockwood/CountryPicker

### ISSUE THREAD

**Issue by vkumarsharma** [skywinder/ActionSheetPicker-3.0#148]
Wanted a flag based country name functionality integrated in ActionsheetPicket. I use the code of Country picker and integrate same as two spearate files on Actionsheetpciker + the resources used

**Comment by skywinder** [comment]
@vkumarsharma Thanks for proposal.
First of all, we have to ask of @nicklockwood about this integration.
It's a good idea. Now I'm busy on other projects, so don't have a time to implement it.Is someone can implement it - I'm ready to review pull request.

**Comment by vkumarsharma** [comment]
Hi Petr
I have done in integration which works for me. There are two new files in Picker and a change in Tests to select countries.
However i was not able to get the resource bundle for flags working from a library due to my lack of knowledge so flags are not showing in scroll.
I have put a pull request and you may review if it is worth it to put in main line
Vikas   


     On Thursday, March 5, 2015 2:19 PM, Petr Korolev <notifications@github.com> wrote:
   

 @vkumarsharma Thanks for proposal.
First of all, we have to ask of @nicklockwood about this integration.
It's a good idea. Now I'm busy on other projects, so don't have a time to implement it.Is someone can implement it - I'm ready to review pull request.—

**Comment by skywinder** [comment]
@vkumarsharma Thanks for your effort! :+1: 
I will review #158 and try to fix flags images!

**Comment by vkumarsharma** [comment]
A small update if that helps, the bundle is working in pod when i use it in seperate project, but when i use it in the demo project with the code it doesn't seems like project configuration issue 


     On Tuesday, March 31, 2015 4:00 PM, Petr Korolev <notifications@github.com> wrote:
   

 @vkumarsharma Thanks for your effort!  
I will review #158 and try to fix flags images!—

**Comment by skywinder** [comment]
@vkumarsharma I can review PR with this feature. Let me know if you still interested in this addition.
