### ISSUE TITLE
Question: When press the UITextField

### ISSUE THREAD

**Issue by malakiya** [skywinder/ActionSheetPicker-3.0#151]
Hi, I have a question
When I pressed the UITextField in some case show the pickerview in others i have to press and hold a little more time. It's not like an UIButton for example.

For all UITextField i have 
`[textField addTarget:self action:@selector(action:) forControlEvents:UIControlEventTouchDown]` 
like the example.

Can you help me?

**Comment by skywinder** [comment]
Hi. it's quite uncertain case. 
Probably it related with tapping outside of the bound of textField. Probably it's related with [The Responder]Chain(https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/event_delivery_responder_chain/event_delivery_responder_chain.html)

**Comment by skywinder** [comment]
@malakiya Can you check #157 - it looks very similar to your problem. I already implement workaround for it, so try to reproduce your delay - is it remain in last version?

**Comment by malakiya** [comment]
@skywinder sorry for my late reply 
I reproduced and the perfomance its perfect now, i don't have delay in iphone.

Thanks a lot!

**Comment by skywinder** [comment]
:+1:
