### ISSUE TITLE
Changelog for private repository

### ISSUE THREAD

**Issue by bernamaxim** [skywinder/ActionSheetPicker-3.0#153]
How I can generate changelog for private repository?
I just generate it and the output only :

# Change Log

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by skywinder** [comment]
@bernamaxim I think you are miss the project.
Please, open an issue in https://github.com/skywinder/github-changelog-generator/issues and describe more detail, which parameters are you pass in the script.
