### ISSUE TITLE
Crash if picker still in motion

### ISSUE THREAD

**Issue by camflan** [skywinder/ActionSheetPicker-3.0#154]
If a user clicks "Done" while the picker is still in motion the StringPicker crashes the application. It also happens happens if the view is still animating into position and you hit "done".

I see that this was marked as fixed in `1.1.21`, but I'm seeing it in a downloaded .zip from last week.

**Comment by camflan** [comment]
Other issue caused the crash, sorry.

**Comment by skywinder** [comment]
@camflan did you find the reason of the crash? It not related with Picker, right?

**Comment by camflan** [comment]
@skywinder Yes, we found the reason for the crash. I think it's related, but only partially.

One of the developers had set initialSelection: to a value outside of the range of the array. However, it didn't crash except when the picker was still in motion and we'd hit the Done button.

**Comment by skywinder** [comment]
Ok. So I think it's kind of side effect of out of the range value. 
Thus close this issue. Feel free to reopen it, if you still have any problems with this problem.
