### ISSUE TITLE
Make title / buttons optional

### ISSUE THREAD

**Issue by fatuhoku** [skywinder/ActionSheetPicker-3.0#155]
I don't want the nav bar to be displayed at all. Is this possible?

**Comment by skywinder** [comment]
Yes, It was implemented in #140. Just set `picker. toolbar.hidden = YES`

**Comment by fatuhoku** [comment]
Ah!

**Comment by speedy-colibri** [comment]
Hello,
I'm using version 2.2.0 of ActionSheetPicker but still cannot hide the toolbar. Even if I do `picker.toolbar.hidden = YES`, but as soon as I call `[picker showActionSheetPicker]` the toolbar gets created by some function called `[self createPickerToolbarWithTitle...`, hence overwriting my settings. How is this hiding really supposed to work?
Thanks in advance!
