### ISSUE TITLE
How to get origin:sender when you dont have a sender

### ISSUE THREAD

**Issue by mworsnop** [skywinder/ActionSheetPicker-3.0#165]
I have the need to show the ActionSheetStringPicker calling it from the results of code rather than when the user presses a button. 

I do not have a ORIGIN which usually has origin:sender  

As I do not have a sender I don’t know what else to put there? 

The view controller is: @interface pinMapEdit : UIViewController

Can you please help?

**Comment by skywinder** [comment]
Every `UIViewController` has a property `view` So, just set this view as `origin`.
