### ISSUE TITLE
ActionSheetDatePicker Max and min Date doesn't work

### ISSUE THREAD

**Issue by Wildregar** [skywinder/ActionSheetPicker-3.0#169]
Hi, with this code minimum and maximum date doens't work... where I'm wrong?

    NSCalendar *calendar = [NSCalendar currentCalendar];
    NSDateComponents *minimumDateComponents = [calendar components:NSCalendarUnitDay | NSCalendarUnitMonth | NSCalendarUnitYear fromDate:[NSDate date]];
    [minimumDateComponents setYear:1900];

    ActionSheetDatePicker *dateNascitaPicker = [[ActionSheetDatePicker alloc]
                                                    initWithTitle:@""
                                                    datePickerMode:UIDatePickerModeDate
                                                    selectedDate:[NSDate date]
                                                    doneBlock:^(ActionSheetDatePicker *picker, id selectedDate, id origin)
        {
            
        }
                                                    cancelBlock:^(ActionSheetDatePicker *picker)
        {
            
        }
                                                    origin:self.txtDataNascita];
        
       
        NSDate *minDate = [calendar dateFromComponents:minimumDateComponents];
        NSDate *maxDate = [NSDate date];
        
        [dateNascitaPicker setMinimumDate:minDate];
        [dateNascitaPicker setMaximumDate:maxDate];
        
        [dateNascitaPicker showActionSheetPicker];

**Comment by skywinder** [comment]
@Wildregar I check your code and it works. Please, notice, that this is Apple's realisation, and it not quite  clear for me, when I first time saw it:

If you try to select date before `1900` -  picker will roll back with a little delay after releasing of the finger from the screen.

Please check again and let me know, if this bug is reproducible.

**Comment by skywinder** [comment]
I also add example with min and max date to example project

**Comment by skywinder** [comment]
@Wildregar feel free to reopen, if you still sure, that is a bug.

**Comment by palKaran** [comment]
This may help you.

`[[ActionSheetDatePicker alloc] initWithTitle:@"Date" datePickerMode:UIDatePickerModeDate selectedDate:_selectedDate minimumDate:nil maximumDate:[NSDate date] target:self action:@selector(toDateWasSelected:element:) origin:textField]`

**Comment by warisappify** [comment]
@skywinder can you please replace function named *DatePickerClicked* in your swift sample with following function


    @IBAction func DatePickerClicked(_ sender: UIButton) {
        let datePicker = ActionSheetDatePicker(title: "Date:", datePickerMode: UIDatePickerMode.date, selectedDate: Date(), doneBlock: {
            picker, value, index in
            print("value = \(String(describing: value))")
            return
        }, cancel: { ActionStringCancelBlock in return }, origin: sender.superview!.superview)
        let secondsInWeek: TimeInterval = 7 * 24 * 60 * 60;
        datePicker?.maximumDate = Date(timeInterval: -secondsInWeek, since: Date())
        datePicker?.show()
    }

And then run the code tap on *UIDatePickerMode Date* then click *Done* in picker bar button without changing anything and see the result in logs.
I got these which are wrong.

`
value = Optional(2018-09-27 07:22:27 +0000)
index = Optional(<UITableViewCell: 0x7fcb86841a00; frame = (0 124; 375 40); autoresize = W; layer = <CALayer: 0x60c00003ed20>>)
picker = Optional(<ActionSheetDatePicker: 0x7fcb84e046c0>)
`

For more detail here are the screenshots for you.

<img width="689" alt="screen shot 2018-09-27 at 12 30 52 pm" src="https://user-images.githubusercontent.com/24873180/46129849-49237480-c251-11e8-84a7-bfbf6a7d151a.png">

<img width="689" alt="screen shot 2018-09-27 at 12 30 52 pm" src="https://user-images.githubusercontent.com/24873180/46129848-488ade00-c251-11e8-8e7a-5a3f6b85bc0b.png">

Need a quick help.
Thanks in advance.

**Comment by keshu1024** [comment]
This works for me: 


    
    @IBAction func dobBtnPressed(_ sender : UIButton) {
        let datePicker = ActionSheetDatePicker(title: "Date:", datePickerMode: UIDatePicker.Mode.date, selectedDate: Date(), doneBlock: {
            picker, value, index in
            
            print("value = \(String(describing: value))")
            print("index = \(String(describing: index))")
            print("picker = \(String(describing: picker))")
            self.dateOfBirthField.text = "\(value as? Date ?? Date())"
            return
        }, cancel: { ActionStringCancelBlock in return }, origin: sender.superview!.superview)
        
        if #available(iOS 13.0, *) {
            datePicker?.pickerBackgroundColor = UIColor.secondarySystemBackground
        } else {
            datePicker?.pickerBackgroundColor = UIColor.white
        }
        
        var components = DateComponents()
        components.year = -100
        let minDate = Calendar.current.date(byAdding: components, to: Date())

        components.year = -18
        let maxDate = Calendar.current.date(byAdding: components, to: Date())
        
        datePicker?.minimumDate = minDate ?? Date()
        datePicker?.maximumDate = maxDate ?? Date()
        
        datePicker?.show()
    }
