### ISSUE TITLE
Keywindow issue

### ISSUE THREAD

**Issue by rjgdesign** [skywinder/ActionSheetPicker-3.0#174]
Hey guys,

Got a bool to check active window...

BOOL alertOrActionSheetIsVisible = [UIApplication sharedApplication].keyWindow != [UIApplication sharedApplication].delegate.window;

But, when action sheet picker is opened, then closed by hitting done, its still returning true. Any ideas?

Cheers!

**Comment by skywinder** [comment]
Hello.
Please, clarify the problem: Steps to reproduce and what the expected result for this case?

**Comment by rjgdesign** [comment]
I'm using Flow (https://github.com/OliverLetterer/Flow), and when you open the picker, it never marks a tutorial as completed, after its been opened, with that line:

BOOL alertOrActionSheetIsVisible = [UIApplication sharedApplication].keyWindow != [UIApplication sharedApplication].delegate.window;

Being the problem.

**Comment by skywinder** [comment]
I don't know, how this string:

    BOOL alertOrActionSheetIsVisible = [UIApplication sharedApplication].keyWindow != [UIApplication sharedApplication].delegate.window;

related with this project. Sorry, but I can't help with integration with side projects.

If the question - how to get know, that picker is dismissed, the answer is:

You can use your favorite callback pattern ( block, selectors of delegation) to get informed, when Picker is being dismissed.
