### ISSUE TITLE
Text color of toolbar buttons

### ISSUE THREAD

**Issue by mzgaljic** [skywinder/ActionSheetPicker-3.0#175]
Hello,

I looked at the source code but it is not immediately obvious (at all) where I could change the text color of the toolbar buttons. I am using the date picker, and would like the "cancel" and "start" buttons to be a different color.

**Comment by mzgaljic** [comment]
Never mind, this can be done very easily. Like so:

    UIColor *desiredColor = [UIColor redColor];
    NSDictionary *attributes = @{ NSForegroundColorAttributeName : desiredColor };
    
    [[UIBarButtonItem appearanceWhenContainedIn:[UISearchBar class], nil]
     setTitleTextAttributes:attributes forState:UIControlStateNormal];

**Comment by skywinder** [comment]
Thanks for solution! :+1:

**Comment by skywinder** [comment]
related with  #175

**Comment by skywinder** [comment]
it will be fixed with #54 pretty soon. I will make some easier way to set tint color for buttons
