### ISSUE TITLE
Error while installing with cocoapods

### ISSUE THREAD

**Issue by brucelee206** [skywinder/ActionSheetPicker-3.0#177]
When installing with pods, I get the following error: 
[!] /usr/bin/git clone https://github.com/skywinder/ActionSheetPicker-3.0.git /Users/tungdao/Workplace/meety/Meety/Pods/ActionSheetPicker-3.0 --single-branch --depth 1 --branch 1.6.2
error: RPC failed; result=56, HTTP code = 200

fatal: The remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed
How to fix it?

**Comment by skywinder** [comment]
Which version of cocoapods are you using?

I believe it's problem cocoapods, not this project.
Similar problem described here:
http://stackoverflow.com/questions/26197171/git-clone-repository-error-rpc-failed-result-56-http-code-200

**Comment by brucelee206** [comment]
Thanks. I solved it by using this command before pod install:
git config --global http.postBuffer 1048576000
