### ISSUE TITLE
ActionSheetStringPicker freezes in simulator

### ISSUE THREAD

**Issue by Waderoni** [skywinder/ActionSheetPicker-3.0#179]
I was using an iPhone 5 simulator and overtime the action sheet came up, I can only scroll 1 item down and then it freezes.  Works on my actual iPhone 5 but the simulator freezes

**Comment by skywinder** [comment]
Strange. But have no idea, how to reproduce it.
Please, provide more details about this bug.

**Comment by skywinder** [comment]
@Waderoni please, provide your code example, how are you call picker and handle callbacks.

**Comment by Waderoni** [comment]
So weird!  It's completely happy now and scrolls fine. I think you can close this out and I apologize for wasting your time.  It will scroll just fine now. I really don't know what happened.
