### ISSUE TITLE
Swift example project cannot be parsed

### ISSUE THREAD

**Issue by bmurmistro** [skywinder/ActionSheetPicker-3.0#181]
I just cloned the repo and tried to open the swift example and got an error message ... "Swift-Example.xcodeproj cannot be opened because the project file cannot be parsed."

I'm using xcode 6.3.2

**Comment by skywinder** [comment]
Please, open `xcworkspace` file, (not xcodeproj). as it described in readme.

**Comment by bmurmistro** [comment]
Got it.

Btw, this control is fantastic! Thanks!

**Comment by skywinder** [comment]
@bmurmistro sorry, just found, that I broke example for swift project in last update. Will fix it now!

bdw: now you can open swift xcodeproject separately, and as part of xcworkspace also!
