### ISSUE TITLE
Missing argument for paramater cancelAction.  (SWIFT)

### ISSUE THREAD

**Issue by fika4life** [skywinder/ActionSheetPicker-3.0#182]
I get the error message "Missing argument for parameter cancelAction".  There is no cancelAction in the example so I don't know what to do about this error. When I add cancelAction it says there is an extra argument cancelAction. 

Here is my code. Would be grateful for any help. Thanks!

    @IBAction func SchoolPicker(sender: AnyObject) {
         ActionSheetStringPicker.showPickerWithTitle("A String", rows: anArray, initialSelection: 1,
           doneBlock: {
            picker, value, index in

            println("value = \(value)")
            println("index = \(index)")
            println("picker = \(picker)")
             return
             },cancelBlock: { ActionStringCancelBlock in return } ,origin:sender)

}

**Comment by fika4life** [comment]
Solved it. My array "anArray" was actually a Lazybidirectional Collection so needed to be converted to an array!

**Comment by skywinder** [comment]
:+1: 
I don't even know about this class before. 
Something  new in swift! every day! :wink:
