### ISSUE TITLE
Get wrong Selected Date when we set min or max date.

### ISSUE THREAD

**Issue by ankitjp** [skywinder/ActionSheetPicker-3.0#183]
I tried with your example code, when we pass min and max date at that time date picker return -1 date then actual selected date. Also i notice once we select Today or Yesterday in picker it`s start working proper.

**Comment by andrewloyola** [comment]
you might not be checking for UTC time. try something like this:

NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
[dateFormatter setTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"UTC"]];
[dateFormatter stringFromDate:datePicker.date]

**Comment by ankitjp** [comment]
yes i am using date picker with timezone, but i am getting wrong date in my done button selector.

**Comment by egemenayhan** [comment]
time picker always returns 3 hours earlier how can I fix it? For ex. if I choose 12 it returns 9

**Comment by skywinder** [comment]
@ankitjp, @egemenayhan  Did you find solution?

**Comment by egemenayhan** [comment]
@ankitjp yes, format date for your region before use
