### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by hblockx** [skywinder/ActionSheetPicker-3.0#184]
Is there a way to change the Done / Cancel-buttons titles without creating custom-buttons? I need buttons fitting the current system-language.

Best regards!

**Comment by hblockx** [comment]
var doneButton = UIBarButtonItem(title: "customDoneText", style: UIBarButtonItemStyle.Done, target: nil, action: nil)
        var cancelButton = UIBarButtonItem(title: "customCancelText", style: UIBarButtonItemStyle.Plain, target: nil, action: nil)

        actionSheetStringPicker.setDoneButton(doneButton)
     actionSheetStringPicker.setCancelButton(cancelButton)

For the ones searching for this, too

**Comment by skywinder** [comment]
Hi. Yes, you are provided correct solution by yourself. Cheers! :+1: 
Related with #163
