### ISSUE TITLE
Xcode 7 beta and Swift 2.0

### ISSUE THREAD

**Issue by conradwt** [skywinder/ActionSheetPicker-3.0#185]
Is there a timeline when we'll see support for Xcode 7 beta and Swift 2.0?

**Comment by skywinder** [comment]
Shame of me, didn't try Swift 2.0 yet. :relaxed: 
Can you explain, what the problems with Xcode and Swift 2.0 occurred?

**Comment by conradwt** [comment]
@skywinder It may be best to create a version 4.0 of ActionSheetPicker because Xcode 7 beta wants to run the Swift 2.0 migrator but the deployment target can remain iOS 8.

**Comment by skywinder** [comment]
No way! No more versions in the name of project! :smile: 
It was my mistake to name in like that, when I just fork it for personal needs :joy:
But thanks for mention, if you have any ideas, how to adopt this project for modern syntax & IDE - let me know.

**Comment by conradwt** [comment]
@skywinder I would recommend removing the version from the repo name and using a Git tag to track version of this component.

**Comment by skywinder** [comment]
@conradwt I'm using tags for semantic versioning. Please check #86 & https://github.com/skywinder/ActionSheetPicker-3.0/wiki/Why-3.0%3F for more details about project naming.

**Comment by conradwt** [comment]
@skywinder It may be a good idea to switch the name of the repo after iOS 9/OSX 10.11 SDKs are GM.  Then simply update the README with the information.

**Comment by skywinder** [comment]
The support of Swift 2 implemented in branch `swift-2.0`. You can use this branch in your bleeding edges projects :wink: 
It will be merged with master as soon as Xcode will be update to 7 version in AppStore.

**Comment by conradwt** [comment]
@skywinder Was my PR not acceptable because I took a look at the swift-2.0 branch and it appears to have the same changes of the PR?

**Comment by skywinder** [comment]
@conradwt now there is only Xcode auto migration fixes. And I prefer to do them by myself to understand, what and why changed there. If you have any additional changes to this auto-fixes of IDE - I will be glad to merge them.

**Comment by conradwt** [comment]
@skywinder I just wanted to understand the process for submitting code to the project.  Thus, I'll let you know what I'm going to do before submitting a PR.  After learning more about the migrator, it appears to  be changes for Mac OS 10.11 and iOS 9 in addition to the Swift changes.  Thus, I'm guessing that a better name for the branch my be xcode-7.  Just a thought and thanks for creating the branch and moving the project forward.

**Comment by PSchu** [comment]
Since the Xcode 7 GM is out do you plan on making a release out of the swift-2.0 branch?

**Comment by skywinder** [comment]
@PSchu is it possible to release apps to AppStore from Xcode 7 GM?

**Comment by PSchu** [comment]
Yes, Thats normally what the GM is for;)
Also today iOS9 will be released to the public

**Comment by skywinder** [comment]
Ok, I will prepare project to major update then!

**Comment by conradwt** [comment]
@skywinder It's great to hear that the swift-2.0 branch is being merged into master.

**Comment by PSchu** [comment]
@skywinder Thanks
