### ISSUE TITLE
ActionSheetPickerView  Picker View not appearing for iPAD

### ISSUE THREAD

**Issue by VinayagamD** [skywinder/ActionSheetPicker-3.0#187]
The picker view is inflating with iPhone and not in iPad how to fix this issue.
Thanks in advance

**Comment by VinayagamD** [comment]
ActionSheetDatePickerView view not displaying for iPAD this was exact issue

**Comment by skywinder** [comment]
What the iOS version?
Did you check example project on iPad? Is it not working too?

**Comment by VinayagamD** [comment]
ios 8.1

**Comment by skywinder** [comment]
Did you try to run example project? Is it works?

**Comment by skywinder** [comment]
Looks very similar to #156

**Comment by VinayagamD** [comment]
Ya it is similar but here it is only for iPad not for iPhone.
With Regards,

Vinayagam.D
Wattabyte Inc

**Comment by skywinder** [comment]
@VinayagamD it also for ipad. Did you check `origin` parameter?
please, provide code your code example.

**Comment by VinayagamD** [comment]
self.pickerView = [self configuredPickerView];
    NSAssert(_pickerView != NULL, @"Picker view failed to instantiate, perhaps you have invalid component data.");
    [masterView addSubview:_pickerView];
    [self presentPickerForView:masterView];

If it enter this statement is there any problem

**Comment by VinayagamD** [comment]
if ( IS_IPAD )
    {
        return CGSizeMake(320, 320);
    }

what is the size need to be given?

**Comment by skywinder** [comment]
@VinayagamD Is  #131 Fix this issue?
