### ISSUE TITLE
How can i change done button name?

### ISSUE THREAD

**Issue by taos-thiagoaos** [skywinder/ActionSheetPicker-3.0#19]
How can i change done button name?

And how can i access default buttons?

**Comment by tomblah** [comment]
@skywinder I'm guessing that in this solution we should use:

`ActionSheetStringPicker *picker = [[ActionSheetStringPicker alloc] initWithTitle:@"Select a Block" rows:colors initialSelection:0 doneBlock:done cancelBlock:cancel origin:sender];
    [picker setDoneButton:[[UIBarButtonItem alloc] initWithTitle:@"My Text"  style:UIBarButtonItemStylePlain target:nil action:nil]];
    [picker showActionSheetPicker];`

As opposed to:

`ActionSheetStringPicker *picker = [ActionSheetStringPicker showPickerWithTitle:@"Select a Block" rows:colors initialSelection:0 doneBlock:done cancelBlock:cancel origin:sender];
    [picker setDoneButton:[[UIBarButtonItem alloc] initWithTitle:@"My Text"  style:UIBarButtonItemStylePlain target:nil action:nil]];
    [picker showActionSheetPicker];`

As the latter will show two pickers on top of each other.
