### ISSUE TITLE
No such module 'ActionSheetPicker_3_0' for Swift

### ISSUE THREAD

**Issue by daniyalme** [skywinder/ActionSheetPicker-3.0#190]
Ive been trying to integrate ActionSheetPicker in a Swift project but it keeps giving me No such module error on the import statement.

I have followed the readme tutorial as mentioned, the installation of cocoapods goes fine, I use "touch Podfile" in the project folder to include the line "pod 'ActionSheetPicker-3.0'" and do "pod install" and everything shows all well.

Then i open the . xcworkspace but when i use the statement "import ActionSheetPicker_3_0" in the ViewController it does not builds, I have tried cleaning the project and nothing helps from even cleaning the build.

Im on XCode Version 6.4 (6E35b) can anyone please create a sample swift project, the readme works fine when creating a Objective-C project

**Comment by skywinder** [comment]
Hi, @daniyalme . thanks For mention it. I will try to figure out, what's wrong there. Please, check #125 discussion, since it exactly about this issue.

**Comment by daniyalme** [comment]
Hey @skywinder thanks for the quick reply, really appreciate your time. I reviewed the thread #125 in detail before creating this issue and the suggestions from that thread were updated to readme but i tried all the suggestions by @D051p0 but no avail

**Comment by awhare** [comment]
@daniyalme I just installed CocoaPods and ActionSheetPicker for the first time and was having the same problem. I ended up removing the "import ActionSheetPicker_3_0" line and building my project, with no references to ActionSheetPicker anywhere yet. After a successful build I re-added the line and I no longer have the error. Not sure why, but that seems to have fixed it for me.

**Comment by dautermann** [comment]
the way I fixed it in my own Swift project was to add 

`use_frameworks!`

to my PodFile.

Here's my complete PodFile:

```
xcodeproj 'MyAwsumProject.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'ActionSheetPicker-3.0'
```

I was then able to add `import ActionSheetPicker_3_0` to the top of the .swift file where was including ActionSheetPicker.

**Comment by skywinder** [comment]
@daniyalme  thanks!   :+1: I will update readme with this details.
