### ISSUE TITLE
Can we add it as subview with proper framming?

### ISSUE THREAD

**Issue by hagile** [skywinder/ActionSheetPicker-3.0#191]
Is it possible to add ActionSheetPicker-3.0 as subview of any other view? I want to add this in a view having following size. Size(w - 300, h - 300). Is this possible? I don't want any handler (done) button or anything to close it. I just want selection.

**Comment by skywinder** [comment]
Hi. No, it's not possible. for that porpose you can use native `UIPickerView`

**Comment by hagile** [comment]
@skywinder, I used `UIPickerView` however I'm big fan of your action sheet too. Though, I guess, you'd allowed to this.

**Comment by skywinder** [comment]
@hagile Thanks!
Implementation of this project is not allowed to manually setup window size. 
I will be glad to review PR with this feature. Cheers! :beers:
