### ISSUE TITLE
Picker presenting problems on iOS 9 within multitasking-splitview in compact size 

### ISSUE THREAD

**Issue by xjki** [skywinder/ActionSheetPicker-3.0#194]
When presenting picker on iPad using iOS9 and within multitasking splitview when app
is sized to compact size, picker covers all screen (instead of beeing presented as popover or presented as sheet from below) and becomes unresponsive of buttons.

![simulator screen shot 20 07 2015 17 19 56](https://cloud.githubusercontent.com/assets/747340/8777900/9207d9f0-2f03-11e5-84eb-c7cbe8d69456.png)

**Comment by xjki** [comment]
Happens to be UIPopoverPresentationController  (as it is attached when presenting picker)  default behavior - full screen in compact size. Seems there is no way yet to overwrite this behavior with custom presentation controller - see http://averagejake.com/post/125859113437/custom-presentation-controllers-and-adaptability

**Comment by kashifhisam** [comment]
I have created a pull request for work-around of this bug:

https://github.com/skywinder/ActionSheetPicker-3.0/pull/199

**Comment by skywinder** [comment]
Fixed in #199. Thanks, @kashifhisam! :tada:
