### ISSUE TITLE
pickerTextAttributes not applying to ActionSheetDatePicker

### ISSUE THREAD

**Issue by VrasidasP** [skywinder/ActionSheetPicker-3.0#197]
Hi I just checked the latest commit, but I saw that the pickerTextAttributes don't apply to ActionSheetDatePicker.

*** Searching around I've seen that changing the text color in UIDatePicker is not natively supported :(
If you ever decide to use a custom UIPickerView to act as UIDatePicker this should be resolved. 
Until then, dimming the background for dark mode will have to suffice.

**Comment by skywinder** [comment]
@VrasidasP hi. yes, you are on right way. Since it uses native date picker it's not possible to customize it. The only thing, that I can suggest - is create your own date picker on base `CustomActionSheetPicker` or `ActionSheetMultipleStringsPicker` that will be merged soon (#196)
