### ISSUE TITLE
Headers not found when using use_frameworks

### ISSUE THREAD

**Issue by gklka** [skywinder/ActionSheetPicker-3.0#198]
I have to use `use_frameworks` option in CocoaPods because one of my other pods. ActionSheetPicker does not support this: after enabling the option, header files can no longer seen, so Xcode displays errors about missing files.

```
#import <ActionSheetPicker-3.0/ActionSheetPicker.h>
```

`/Users/gk/Developer/iOS/GKSoftware/vibu/vibu/Screens/Profile/VMEditProfileController.m:341:39: Use of undeclared identifier 'ActionSheetDatePicker'`

My Podfile:

```
# Uncomment this line to define a global platform for your project
#platform :ios, '7.0'

use_frameworks!

target 'vibu' do

pod "GKFadeNavigationController"
pod "AFNetworking"
pod "MBProgressHUD"
pod "UIAlertView-Blocks"
pod "CocoaLumberjack", '2.0'
pod "SDWebImage"
pod "TUSafariActivity"
pod "BDDRScrollViewAdditions"
pod "MBProgressHUD"
pod "ActionSheetPicker-3.0"
pod "HCSStarRatingView", :git => 'https://github.com/hugocampossousa/HCSStarRatingView.git'
pod "CCHMapClusterController"
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"

end

target 'vibuTests' do

end
```

**Comment by skywinder** [comment]
For Obj-c projects:

#import "ActionSheetPicker.h"
For Swift projects:

import ActionSheetPicker_3_0

**Comment by skywinder** [comment]
Let me know if you still need help
