### ISSUE TITLE
Use of unresolved identifier 'ActionSheetMultipleStringPicker'

### ISSUE THREAD

**Issue by Dimes** [skywinder/ActionSheetPicker-3.0#203]
I'm using ActionSheetPicker with CocoaPods. I have `import ActionSheetPicker_3_0` at the top of my swift file. This seems to only import the following, however:

    ActionSheetCustomPicker
    ActionSheetDatePicker
    ActionSheetDistancePicker
    ActionSheetLocalePicker
    ActionSheetStringPicker

As you can see, `ActionSheetMultipleStringPicker` is missing. Is there another way of getting this functionality? Should the swift example be updated?

**Comment by skywinder** [comment]
@alexperezpaya please, check this issue, it's about your picker. :wink:

**Comment by alexperezpaya** [comment]
@Dimes @skywinder I'm out for vacation but I'll have a look it as soon as I can.

**Comment by skywinder** [comment]
@alexperezpaya any updates? Related with #196
