### ISSUE TITLE
Display picker in UITextField

### ISSUE THREAD

**Issue by JehBee** [skywinder/ActionSheetPicker-3.0#207]
I'm trying to display the result of the DateAndTime Picker in a UITextField "DateAndTimeTextField", but I can't figure out what to put in.  Here is my swift code:

  @IBOutlet weak var DateTimeTextField: UITextField!
  @IBAction func DateAndTimeClicked(sender: UIButton) {
    
    var datePicker = ActionSheetDatePicker(title: "Date and Time:", datePickerMode: UIDatePickerMode.DateAndTime, selectedDate: NSDate(), doneBlock: {
      picker, value, index in
      
      //println("index = \(index)")
      //println("picker = \(picker)")
      println("value = \(value)")
      
      var dateFormatter = NSDateFormatter()
      dateFormatter.dateFormat = "MM/dd/yyyy"
      //self.DateTimeTextField.text = (dateString)
      
      self.DateTimeTextField.text = ("\(value)")

      return
      }, cancelBlock: { ActionStringCancelBlock in return }, origin: sender.superview!.superview)
    let secondsInWeek: NSTimeInterval = 7 * 24 * 60 * 60;
    datePicker.minimumDate = NSDate(timeInterval: -secondsInWeek, sinceDate: NSDate())
    datePicker.maximumDate = NSDate(timeInterval: secondsInWeek, sinceDate: NSDate())
    datePicker.minuteInterval = 20

    datePicker.showActionSheetPicker() 
}

**Comment by skywinder** [comment]
Related with #239
