### ISSUE TITLE
Use of unresolved identifier 'ActionSheetStringPicker' - Siwft 2

### ISSUE THREAD

**Issue by Canmmy** [skywinder/ActionSheetPicker-3.0#208]
Hi,

I had import ActionSheetPicker with Carthage in Xcode 7 beta 4.
I successful to import in Carthage but when I import source code as below it will show error:
"Use of unresolved identifier 'ActionSheetStringPicker'

ActionSheetStringPicker.showPickerWithTitle("Nav Bar From Picker", rows: ["One", "Two", "A lot"], initialSelection: 1, doneBlock: {
                picker, value, index in
                
                println("value = \(value)")
                println("index = \(index)")
                println("picker = \(picker)")
                return
                }, cancelBlock: { ActionStringCancelBlock in return }, origin: sender)

Can you guide me how it work in Swift2?

**Comment by skywinder** [comment]
Hello. There is no support Swift 2 yet.
Close in favor of #185
