### ISSUE TITLE
Error while using CoreActionSheetPicker

### ISSUE THREAD

**Issue by manishpurplefront** [skywinder/ActionSheetPicker-3.0#209]
![screen shot 2015-09-09 at 11 40 27 am](https://cloud.githubusercontent.com/assets/13223874/9754533/c086a80e-56e7-11e5-86bf-15ace5141c90.png)

**Comment by skywinder** [comment]
what object is `sender` in your case?

**Comment by manishpurplefront** [comment]
I am using UITableViewController.

**Comment by skywinder** [comment]
You have to specify `UIView` as origin in this case.
