### ISSUE TITLE
iOS 9 support - UIPopoverController deprecated

### ISSUE THREAD

**Issue by nationalpaulyip** [skywinder/ActionSheetPicker-3.0#210]
Tested on version 1.72, when compiling with Xcode 7.0 beta 6, the following message showed.

'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.

**Comment by skywinder** [comment]
Hello. thanks for report. I'm full of work now, so, can't quickly fix it. But it's necessary to resolve this thing before iOS 9 release.

**Comment by sticksen** [comment]
Well...iOS9 release has happenend. :)

**Comment by Bjqrn88** [comment]
Are there still work being done on this issue.. ??

**Comment by skywinder** [comment]
@Bjqrn88  Not yet

**Comment by yosuke1985** [comment]
Hod you guys fixed this problem??

**Comment by Lilac911** [comment]
I am waiting for the solution too :(

**Comment by skywinder** [comment]
Don't have a time to refactor code right now. But I agree, it has to be fixed asap.

**Comment by Lilac911** [comment]
I wish I could help. But I don't know objective-C :(

**Comment by Lilac911** [comment]
So, there is no solution for that right now?

**Comment by skywinder** [comment]
@Lilac911 as I said before - don't have a time now to refactor this picker. If I would much appreciated if someone will handle this thing..

**Comment by aniliosdev** [comment]
Any Updates??

**Comment by skywinder** [comment]
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by ddaddy** [comment]
I just looked to fix this however it's quite a big job. The AbstractActionSheetPicker class needs to know which ViewController to present the popup onto as the new popup methods work just like presenting any other view controller. So every init method will need changing to accept the viewController too and i'm not sure how much of a change @skywinder wants to have?

**Comment by skywinder** [comment]
Looks like it solved long time ago.
Feel free to reopen the issue if you still need help. 👍
