### ISSUE TITLE
ActionSheetDatePicker iOS 9 Problems

### ISSUE THREAD

**Issue by appcelerate** [skywinder/ActionSheetPicker-3.0#213]
Hi,

the ActionSheet Date Picker will not showing in iOS 9. Only a black alpha 0.1 View will Block the Screen.

Regards,
Dennis

**Comment by skywinder** [comment]
Hello. Thanks for mention. It's critical bug, but I'm in vacation next 2 weeks, and will be out of internet. If someone find solution - please create a PR.

**Comment by skywinder** [comment]
@appcelerate Can't reproduce this bug. Please provide me more details, how to reproduce it.
