### ISSUE TITLE
ActionSheetPickerCustomPickerDelegate

### ISSUE THREAD

**Issue by Nilesh04** [skywinder/ActionSheetPicker-3.0#214]
I am using custom picker. It works well till iOS 8.4
But in iOS 9 I am getting issue in picker it is showing ... in place of text.
PFA. If anyone finds solution then Please revert back.
![2c1d5cd0-6141-11e5-8dad-d4ac4b38607c](https://cloud.githubusercontent.com/assets/11361817/10018116/bbf3b18c-6151-11e5-98c5-8eb2133a2c6b.png)

**Comment by skywinder** [comment]
Can you describe, this issue in details and provide code example?

**Comment by skywinder** [comment]
You can make text size smaller to fit labels inside. That's it.
