### ISSUE TITLE
iOS 9 keyboard problem

### ISSUE THREAD

**Issue by jasuha2** [skywinder/ActionSheetPicker-3.0#215]
when i used this  at iOS 8 there was not a problem.

but when i upgrated to iOS 9. there is a problem.

when  Textfield touch down event keyboard and action view opening together. how to block keyboard when press the touch down event. i want  to  just open the action view

**Comment by skywinder** [comment]
Hello. Thanks for mention. It's critical bug, but I'm in vacation next 2 weeks, and will be out of internet. If someone find solution - please create a PR.
Related with #213

**Comment by CigarsNMartinis** [comment]
Jasuha2, I got around this by resigningfirstresponder in textFieldDidBeginEditing event.

**Comment by Lenord2** [comment]
Hi All,

Keyboard is not appearing entire application adfter Upgarde iOS version from 8.4 to 9. I am working on this from last 2 days on wards. But I didn't get solution till now. Please help me out rom this issue. Thanks in advance

**Comment by Flitskikker** [comment]
I worked around this by placing a UIButton over the UITextField (same size and position) and then opening the picker on the button click, and writing the chosen value to the text field when the user taps Done.
I save the index in the text field's tag and feed it to initialSelection.

**Comment by allaire** [comment]
@skywinder Do you have any hint of what's causing this?

**Comment by skywinder** [comment]
@allaire  can't reproduce it yet

**Comment by allaire** [comment]
@skywinder this was happening in this case (at least for me):

I have a tableview with two cells, one when I select it opens a `ActionSheetPicker`, and the other is a cell with a `UITextField` that opens the keyboard.

The workaround I used is `view.endEditing(true)` each time `didSelectRowAtIndexPath` is called. That way I make sure any keyboard is dismissed if present.

Does it helps you at all to reproduce it?

Thanks!

**Comment by CigarsNMartinis** [comment]
It's easy to reproduce. Set up one text field with a standard keyboard, set up another with date picker. Touch into the first textfield, popping the keyboard. Type some stuff.  Touch into the second textfield which then pops the date picker *behind* the keyboard, which does not dismiss.

**Comment by skywinder** [comment]
@allaire @CigarsNMartinis Hi. I confirm - in iOS 9 keyboard starts to overlap `ActionSheetPicker`.
I create special button in Swift project example to to test this case. 
But normally it's your responsibility to manage of hiding/presenting keyboard before presenting another view. SO, I don't think that it's required to add additional code inside the project to force hiding keyboard. It could cause unpedicted side effects in others apps.
So, all you have to do - it's call `self.view.endEditing(true)` before fire `ActionSheetPicker`. 
I don't thing that is a bug of `ActionSheetPicker`. Let's assume it a feature of iOS 9, ok? :wink:

**Comment by colinrblake** [comment]
I have the exact problem @CigarsNMartinis  describes (text field followed by ActionSheetDatePicker of type UIDatePickerModeCountDownTimer). I've tried calling endEditing:YES and resignFirstRepsonder before creating the picker but the picker still appears BEHIND the keyboard.

It's timing related because it doesn't occur in the simulator, and to fix the problem on a real device I call resignFirstResponder after a 0.1 second delay.
