### ISSUE TITLE
How to change Font of certain labels in picker

### ISSUE THREAD

**Issue by Hadjimina** [skywinder/ActionSheetPicker-3.0#217]
Heyo guys

So I'm having a a bit of a problem. I have a ActionSheetMultipleStringPicker where I would like to change the font of the first, 5th and 11th label of the first component to bold. I have implemented such a thing with a standard PickerView which was fairly easy. Is there any way I could achieve this with ActionSheetPicker ?

Really love this project, great work !

Philipp

**Comment by skywinder** [comment]
Hi! Thanks for your feedback! It's not possible for now.
It is duplicate of #58.
