### ISSUE TITLE
how to custom the donebutton's ttile "done" or the cancelbutton's title?

### ISSUE THREAD

**Issue by wangchaodong** [skywinder/ActionSheetPicker-3.0#219]

**Comment by wangchaodong** [comment]
I just found that use setDoneButton can make it!  :D

**Comment by skywinder** [comment]
NI, it can. Could you provide your code?

**Comment by wangchaodong** [comment]
hi!
I try in your example project do some change! 
I think it should make it but it give me some exception! here is the code: 

        let a = ActionSheetMultipleStringPicker.init(title: "Multiple String Picker", rows: [
                ["One", "Two", "A lot"],
                ["Many", "Many more", "Infinite"],
                ["aaa","sss","ccc","xxxx"]
            ], initialSelection: [0, 0, 0], doneBlock: {ActionMultipleStringDoneBlock in return }, cancelBlock: {ActionMultipleStringCancelBlock in return }, origin: sender)
        
        a.setCancelButton(UIBarButtonItem(title: "My own title", style: UIBarButtonItemStyle.Plain, target: self, action: nil))
        a.showActionSheetPicker()

here, xcode notice that the exception is the last code:         a.showActionSheetPicker()
 Am I did some thing wrong?

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
