### ISSUE TITLE
I guess here have something wrong!

### ISSUE THREAD

**Issue by wangchaodong** [skywinder/ActionSheetPicker-3.0#220]
![image](https://cloud.githubusercontent.com/assets/9583900/10386711/1e24e496-6e8d-11e5-9d95-12dbc169660d.png)

**Comment by skywinder** [comment]
Hello! Could you clarify?

Probably code is not obvious, initialSelections array - is the array indexes of selections for each component.

**Comment by wangchaodong** [comment]
If you try to init a picker with ActionSheetMultipleStringPicker , you would know what I mean!

**Comment by skywinder** [comment]
Close in favor of #222. Let's continue discussion there.

**Comment by skywinder** [comment]
@alexperezpaya FYI
