### ISSUE TITLE
Disable particular row where user can only we that row but cannot select it.

### ISSUE THREAD

**Issue by hardikamal** [skywinder/ActionSheetPicker-3.0#223]
Hi @skywinder,
Thanks for the library.Is it possible to disable particular row where user can only we that row but cannot select it? like time slots suppose its 2.30pm then 1-2pm is disabled and user cannot select that time slot.

**Comment by skywinder** [comment]
Hello. it's not supported OTB. But you can make it by your own with `ActionSheetCustomPicker`

**Comment by hardikamal** [comment]
Solved Thanks...!!!

**Comment by coanag** [comment]
@hardikamal can you please provide a workaround how did you achieve it?
Im into it too.
Thanks
