### ISSUE TITLE
Picker is duplicated when use showActionSheetPicker

### ISSUE THREAD

**Issue by StanleySathler** [skywinder/ActionSheetPicker-3.0#224]
Hey sky winder,
First of all, thanks to gave us this brilliant tool.

I'm having a little problem: I'm trying to custom my done and cancel button using, as you already said, setDoneButton and setCancelButton. However, when I am using [picker showActionSheetPicker], I am getting two pickers: one with correct buttons (modified) and another one, which shows up when I close the first, which has the original buttons.

**Comment by skywinder** [comment]
Hi! Can you provide code example to reproduce this issue?
