### ISSUE TITLE
Cocoa pod update

### ISSUE THREAD

**Issue by odejonge** [skywinder/ActionSheetPicker-3.0#225]
If I run '$ pod update' it prints **Installing ActionSheetPicker-3.0 1.5.1 (was 1.5.0)** but if I look into the README.md file I see in the heading version 2.0.3? Why this difference? This has my attention because I get a warning in my project: **/Users/.../Pods/ActionSheetPicker-3.0/Pickers/SWActionSheet.m:221:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')**
Is this due to an minor version or an unresolved bug?

**Comment by skywinder** [comment]
Fixed. Current version is `2.0.3`
