### ISSUE TITLE
how to call an ActionSheetPicker Programatically in Swift?

### ISSUE THREAD

**Issue by RafaelGadret** [skywinder/ActionSheetPicker-3.0#226]
Hello!
I'm trying to call, for example, ActionSheetDatePicker, from code , without an IBaction, with no success.
The swift example included only show how to call ActionSheetDatePicker from a IBAction.
Please can someone help me with the correct syntax to call ActionSheetDatePicker from inside  functions with no linking to the interface builder(programmatically)?

Thanks!

**Comment by skywinder** [comment]
There is no linking to IB at all. Please, check examples project for more info.
