### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by WenchaoIOS** [skywinder/ActionSheetPicker-3.0#227]
Hi @skywinder 
    Do you think we could add `infinite` feature in this picker? Something like:

```objective-c
+ (instancetype)showPickerWithTitle:(NSString *)title infiniteRows:(NSArray *)strings initialSelection:(NSInteger)index doneBlock:(ActionStringDoneBlock)doneBlock cancelBlock:(ActionStringCancelBlock)cancelBlock origin:(id)origin;
```

I've finished this in `ActionSheetStringPicker` and `ActionSheetMultiStringPicker` for own-usage. I'll send a pr if u r interested.

**Comment by skywinder** [comment]
Hello! If it's already implemented - please sent PR, I will review it! :+1: 
FYI: According Apple guidelines - you should'n use picker for more than 10 items (they recommend to use UITableView in such cases).

**Comment by WenchaoIOS** [comment]
[Done](#228). And I'd like to submit the 'multiple string version' and other versions if you think it's fine.
