### ISSUE TITLE
Cancel and Done button is white

### ISSUE THREAD

**Issue by yuchaozh** [skywinder/ActionSheetPicker-3.0#230]
Hi,

I am using the following code to show a number picker, but the done and cancel button is white.

NSArray *colors = [NSArray arrayWithObjects:@"1", @"2", @"3", @"4", nil];
[ActionSheetStringPicker showPickerWithTitle:@"Image video length (seconds): " rows:colors initialSelection:2 
       doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
							NSLog(@"Picker: %@, Index: %ld, value: %@",
								picker, (long)selectedIndex, selectedValue); }
	 cancelBlock:^(ActionSheetStringPicker *picker) {
							NSLog(@"Block Picker Canceled"); }
 origin:self.view];

My device is 9.0.2 Do you know how to fix that? I just want it the default blue color.

Thanks in advance.

![img_1194](https://cloud.githubusercontent.com/assets/3889738/10653588/6ec04786-7826-11e5-922d-e0b0d8d95b7b.jpg)

**Comment by skywinder** [comment]
You can use custom buttons to acheve that. Look at exaples.

**Comment by yuchaozh** [comment]
Issue solved. Thanks. please close it.
