### ISSUE TITLE
Problem with click on UITextField

### ISSUE THREAD

**Issue by SalvatoreAD** [skywinder/ActionSheetPicker-3.0#232]
Hi, I try this code and it's work for UIButton, but it doesn't work on UITextField.

This is the code in swift: 

`@IBAction func posti_disponibili(sender: UITextField) {`
`et postiPicker = ActionSheetStringPicker.showPickerWithTitle("Nav Bar From Picker", rows: ["One", "Two", "A lot"], initialSelection: 1, doneBlock: {`
`picker, value, index in`
`print("value = \(value)")`
`print("index = \(index)")`
`print("picker = \(picker)")`
`return`
`}, cancelBlock: { ActionStringCancelBlock in return }, origin: sender)`
`postiPicker.showActionSheetPicker()`
` }`

Can you help me?

Thanks

**Comment by skywinder** [comment]
Please, put breakpoint in @IBaction and check, that event for this IBActions triggered. I don't think, that is a problem of Picker.

**Comment by skywinder** [comment]
Let me know if you need help.
