### ISSUE TITLE
ActionSheetStringPicker problem with simulator and device iOS9

### ISSUE THREAD

**Issue by nasanchez** [skywinder/ActionSheetPicker-3.0#233]
I have an application that uses ActionSheetStringPicker but when I call the ActionSheetStringPicker, the background of all my app is white. When I select a date, the picker dissapears and the white background also dissapears.

Can you help me? Here is my code:

self.selectedDate = [NSDate date];
_actionSheetPicker = [[ActionSheetDatePicker alloc] initWithTitle:@"Fecha inicio" datePickerMode:UIDatePickerModeDate selectedDate:self.selectedDate target:self action:@selector(dateWasSelected:element:) origin:self.view];
self.actionSheetPicker.hideCancel = YES;
[self.actionSheetPicker showActionSheetPicker];

![captura de pantalla 2015-11-25 a las 11 25 05](https://cloud.githubusercontent.com/assets/16014944/11394753/5bab63b8-9367-11e5-9cb6-7efeb981ddaa.png)

**Comment by skywinder** [comment]
@nasanchez  Did you solve this issue?
