### ISSUE TITLE
import ActionSheetPicker_3_0 no such module ActionSheetPicker_3_0 xcode 7.1.1

### ISSUE THREAD

**Issue by tirrorex** [skywinder/ActionSheetPicker-3.0#237]
Hello, after install the pod, i cannot import the module to work with it, i use the latest version of xcode

**Comment by chendadk** [comment]
Maybe you should clean your project.

**Comment by skywinder** [comment]
Yep. Try to delete derived data for the project. It should help.

**Comment by destinyshuling** [comment]
Hi, I have the same problem.
I have tried these ways, but it's still not working.
I use the latest version of Xcode (7.3.1) and swift (2.2).
Could you help me? thanks!

**Comment by skywinder** [comment]
Wow. New Xcode/Swift version it works in other way with imports!
In Swift project you have to write `import CoreActionSheetPicker` see 8de6364

**Comment by skywinder** [comment]
@destinyshuling please, let me know, if it works for you!

**Comment by destinyshuling** [comment]
@skywinder Thank you so much!!! It was finally able to successfully work.

**Comment by Cj370118568** [comment]
I work with this way,but i cant solve the problem. @skywinder @destinyshuling

**Comment by Cj370118568** [comment]
i simply use cocoaspod and do as readme. And i tried to delete the derived data and clean the project.
but i dont work...
 I use the latest version of Xcode (7.3.1) and swift (2.2).

**Comment by skywinder** [comment]
Hey, guys there is kind of magic. Sometimes works 'import Core_Action_Sheet_Pucker'. Give it a try!
