### ISSUE TITLE
Presenting Picker as UITextField

### ISSUE THREAD

**Issue by Lilac911** [skywinder/ActionSheetPicker-3.0#238]
How can I put the picker and selected item in UITextField ?
like in this example, 

<img width="213" alt="string" src="https://cloud.githubusercontent.com/assets/16125816/11547320/e7a62ed4-9907-11e5-9224-3acf320e917a.png">

Thank you

**Comment by skywinder** [comment]
@Lilac911 please take a look at the example in the demo project inside this repo.
