### ISSUE TITLE
Values in Swift Example don't show up after selected

### ISSUE THREAD

**Issue by Lilac911** [skywinder/ActionSheetPicker-3.0#239]
I tried to get the selected value from ,ActionSheetStringPicker, and display it in the same text field in swift.
I took a look in the examples, but nothing in swift. 
The swift example showed the pickers in tableview. In addition, in swift example when I select a value, it didn't show up. How can I fix that?

**Comment by skywinder** [comment]
@Lilac911 In Swift example it print to console values via `print()`. So you can show this values in UITextField in same way.

**Comment by skywinder** [comment]
Related with #207

**Comment by Lilac911** [comment]
good. solved thanx!
