### ISSUE TITLE
How to update the rows in multiStringPicker?

### ISSUE THREAD

**Issue by wangchaodong** [skywinder/ActionSheetPicker-3.0#241]
How can I update the rows after I select one row In one column, such as I select first column at the second row, I want to update the row of second column, (something like Country Picker). It's there any way to reach  it?

**Comment by skywinder** [comment]
You have to use `CustomActionSheetPicker` for that.

**Comment by ReckWang** [comment]
How to use CustomActionSheetPicker for that?

**Comment by skywinder** [comment]
@ReckWang so Here is an answer: same way as I implement it in "Country Picker" (see the demo and source code. It also based on `CustomActionSheetPicker`

**Comment by Kavisha-Dev** [comment]
Hello @skywinder 
Thank you for such a nice library. 

I am trying to create a Picker using ActionSheetCustomPicker since I want to handle the 'didSelectRow'  method of the picker delegate so that I can change the 2nd-row value based on the first row and vice versa.

I referred you're '**selectAMusicalScale**' method in  'ActionSheetPickerCustomPickerDelegate'  from ActionSheetPickerViewController  class.

I kind-of converted the class into swift (since I am coding in Swift) and expected that the 'didSelectRow' method to get hit on changing the value of the picker. But the method does not get hit. 

I create a repo demonstrating the above: https://github.com/Kavisha-Dev/TestActionSheetPicker
It would be great if you could scan over and let me know if you see anything that I am missing.

Thanks,
Kavisha

**Comment by skywinder** [comment]
Hello, @Kavisha-Dev . thank for detaile exmpalantion.


I checked your example. 

after a while, with debugging I found that delegate does not set properly.


so `_delegate` here is `nil`
`- (void)notifyTarget:(id)target didSucceedWithAction:(SEL)successAction origin:(id)origin
`
<img width="745" alt="Screenshot 2020-03-11 at 13 31 19" src="https://user-images.githubusercontent.com/3356474/76385445-9b504b00-639c-11ea-9663-dabff92b5b1c.png">


Looks that problem in the string
`    if ( self = [self initWithTarget:nil successAction:nil cancelAction:nil origin:origin] )
`


<img width="897" alt="Screenshot 2020-03-11 at 13 29 38" src="https://user-images.githubusercontent.com/3356474/76385296-5d532700-639c-11ea-87f8-f0a9343180c6.png">


---

I'm overloaded with other projects now, so can't you offer time for further assistance, please bring my apologies. but feel free to send here new information. I will try to help you during my free time. thank you.

**Comment by Kavisha-Dev** [comment]
Thank you @skywinder for providing direction. I will look into this and see what I find. Thanks again.

**Comment by Kavisha-Dev** [comment]
Hello @skywinder ,

The delegate was indeed nil at notifyTarget.

1. So I created a delegate variable called `@property(nonatomic, strong) id<UIPickerViewDelegate, UIPickerViewDataSource> customDelegate;` in AbstractActionSheetPicker.h

<img width="686" alt="Screenshot 2020-03-17 at 1 29 31 PM" src="https://user-images.githubusercontent.com/8425297/76836143-4f971900-6856-11ea-9f45-e2f57b373421.png">


2. Set the delegate in ActionSheetCustomPicker.m ->  initWithTitle as `self.customDelegate = delegate;`

<img width="811" alt="Screenshot 2020-03-17 at 1 28 55 PM" src="https://user-images.githubusercontent.com/8425297/76836177-62a9e900-6856-11ea-94e5-c6750e5b3b2a.png">

By doing so, my delegate methods in ActionSheetPickerCustomPickerDelegate were getting hit and didSelectRow did get called. yay!
Although quite frankly, I am not quite sure how it solved the problem. 

I committed all the changes here:  https://github.com/Kavisha-Dev/TestActionSheetPicker with https://github.com/Kavisha-Dev/TestActionSheetPicker/commit/56d6841c64209b2e65c9c3bb23f9ace5e410d236 being the commit changes. 

Can you have look at the change in **AbstractActionSheetPicker.h** & in **ActionSheetCustomPicker.m** and see if it makes sense to you.

Thanks,
Kavisha

**Comment by skywinder** [comment]
Amazing. Thank you. I need to check, why its nil ed.. maybe some weak references problem. Will dig into it. Thanks for the help! 

Ps
Would you mind to make a PR in order to honor you contribution?

**Comment by Kavisha-Dev** [comment]
You're most welcome!

By the way, when you told about weak references, 

1. I actually went back to `ActionSheetCustomPicker.h` and checked this property:`@property(nonatomic, weak) id <ActionSheetCustomPickerDelegate> delegate;`
2. Changed it from weak to strong -`@property(nonatomic, strong) id <ActionSheetCustomPickerDelegate> delegate;` AND, it checked. When I ran my project with this change, the delegate methods & didSelectRow were indeed being called.  :/ 
The customDelegate property that I previously created is not needed.

As per your project git commits, this change from strong to weak was recently done. 
Could you kindly have a look at this?

Thank you.

**Comment by Kavisha-Dev** [comment]
Hi there! Did you get a chance to have a look at it? Thanks.

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
