### ISSUE TITLE
Take 5-10 second for the ActionSheetPicker to show up, ? 

### ISSUE THREAD

**Issue by johisco** [skywinder/ActionSheetPicker-3.0#242]
Hi! Im using the ActionSheetPicker in my swift app.

Im using the picker in to places one the the, one is initialized on button click inside an IBOutlet and the other is initialized within a function.

The one initialized from the IBOutlet is initialized and runs instantly while the one initialized from my function takes ages to load...

Anyone care to help me out ? 

        
        let streetNumbers:[String] = makeStreetNumber(1, n: 999)
        let thisRows  = [[geo.street], streetNumbers]
        let initSelection = [0, 0]
        
        ActionSheetMultipleStringPicker.showPickerWithTitle("Ange gatunummer", rows: thisRows as Array, initialSelection: initSelection as Array, doneBlock: {
            picker, values, indexes in
            
            runSomeCode() // .. run some code. 
            return
        }, cancelBlock: { ActionMultipleStringCancelBlock in return }, origin: self.view)

Both functions contains exactly the same thing only thing to differ is the origin from which they are called.

I´ve tried to initialized the IBOutlet function with a simulated click with the same result (take ages to load)
I´ve also tested setting it up with breakpoints as to make sure the error isn't before or after actionsheetpicker function...

**Comment by skywinder** [comment]
@johisco Did you solve it?
