### ISSUE TITLE
Help With Keyboard Popping Up

### ISSUE THREAD

**Issue by MikeKogan** [skywinder/ActionSheetPicker-3.0#249]
Love this library but am struggling with a single issue on ipad. I am using ActionSheetStringPicker in a modalViewController ALMOST exactly as in the example ActionSheetPickerViewController.m

What is different is I also have another textview that is not using a pickerview but is a standard textview.

When the VC with the 2 textviews starts up the standard textview is selected - shouldbeginediting is not called at this point.

When I type in that textfield the keyboard pops up at the bottom etc. If I hit the TAB key control (focus, nextresponder?) stays in the textfield because shouldbeginediting is called for the textview with the picker and it bounces back to the standard textview (I guess?).

When I then select the textfield that uses your stringpicker shouldbeginediting is called, it returns NO, and the picker operates properly. However the "focus" never leaves the original standard textview, and I never see shouldendediting or didendediting fort either textview.

As a result I never see the focus move off the original textview without the picker, the keyboard is never dismissed etc.

The ActionStringPicker just doesn't want to play nice when there is a standard textview in the neighborhood.

I verified this behavior by going into your example, and added a plain old textview to the ActionSheetPickerViewController's View - so you can see the issue there as well.

What am I failing to handle? If I want to mix textviews with no pickers on a form with textviews that use your picker how can I make it work?

Thanks in advance for any advice you can provide, and I apologize for the cruddy writeup. I wanted to change the title which is incorrect but couldn't.

**Comment by skywinder** [comment]
sorry, I can't understand your topic, it's hard to reproduce. You can also try to ask quesiton on SO https://stackoverflow.com/questions/tagged/actionsheetpicker
