### ISSUE TITLE
Crash on iPad IOS7

### ISSUE THREAD

**Issue by AlexanderOsokin** [skywinder/ActionSheetPicker-3.0#250]
`+ (BOOL)canShowPopover {
    if (IS_IPAD) {
        if ([UITraitCollection class]) {
            UITraitCollection *traits = [UIApplication sharedApplication].keyWindow.traitCollection;
            if (traits.horizontalSizeClass == UIUserInterfaceSizeClassCompact)
                return NO;
        }
        return YES;
    }
    return NO;
}`

UITraitCollection class is  not available in IOS7

**Comment by panyult** [comment]
UITraitCollection class is not available in IOS7   +1

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
