### ISSUE TITLE
Invalid object with performSelector:withObject in ActionSheetDatePicker subclass

### ISSUE THREAD

**Issue by ph1lb4** [skywinder/ActionSheetPicker-3.0#253]
I found this issue when subclassing ActionSheetDatePicker. Might help someone in the future. 

http://stackoverflow.com/questions/35198594/performselectorwithobject-sending-wrong-object-only-on-ipad/35198960#35198960

**Comment by skywinder** [comment]
Thanks. I hope Apply fixed it already! :)
