### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Sadmansamee** [skywinder/ActionSheetPicker-3.0#254]
I keep getting this warning.

ActionSheetPicker-3.0/Pickers/AbstractActionSheetPicker.m:53:34: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.

**Comment by skywinder** [comment]
Thanks, for explanation. Don't have a time to refactor code right now. But I agree, it has to be fixed asap..
Close it in favor of #210
