### ISSUE TITLE
UI test failed - can't find value 

### ISSUE THREAD

**Issue by marekmatula** [skywinder/ActionSheetPicker-3.0#255]
I have trouble with UI testing of my application using ActionSheetPicker.
There should be some problem with value handling. Common test case with UIPickerView works fine.

I prepared simple test case - https://github.com/marekmatula/UIPickerViewTester
Steps to reproduce
- clone
- pod install
- run test: UIPickerViewTesterUITests.testAspPicker() 

My result:
UI Testing Failure - Internal error: unable to find current value 'iPhone 3GS, 3 of 10' in possible values iPhone, iPhone 3G, iPhone 3GS, iPhone 4, iPhone 4S, iPhone 5, iPhone 5C, iPhone 5S, iPhone 6, iPhone 6 Plus for the picker wheel "iPhone 3GS, 3 of 10" PickerWheel

**Comment by skywinder** [comment]
@marekmatula ok, I will take a look , what going wrong there.

**Comment by marekmatula** [comment]
I have a little hint for you. 
Go to file _ActionSheetStringPicker.m_
Try comment function:
_(UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view {_

**Comment by marekmatula** [comment]
I found this bugreport today: http://www.openradar.me/22918650

**Comment by skywinder** [comment]
Looks like it solved long time ago.
Feel free to reopen the issue if you still need help. 👍
