### ISSUE TITLE
ActionStringDoneBlock in SWTableViewController

### ISSUE THREAD

**Issue by leo150** [skywinder/ActionSheetPicker-3.0#256]
Hi, thanks for useful framework. 
I guess [SWTableViewController](https://github.com/skywinder/ActionSheetPicker-3.0/blob/master/Example%20Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift) has wrong `doneBlock`. `ActionStringDoneBlock` is `(ActionSheetStringPicker!, Int, AnyObject!) -> Void` but each sheet catch `picker, value, index` for example

```
let datePicker = ActionSheetDatePicker(title: "Date:", datePickerMode: UIDatePickerMode.Date, selectedDate: NSDate(), doneBlock: {
            picker, value, index in //<--- here

            print("value = \(value)") //now is Int
            print("index = \(index)") //now is AnyObject
            print("picker = \(picker)")
            return
        }, cancelBlock: { ActionStringCancelBlock in return }, origin: sender.superview!.superview)
```

**Comment by skywinder** [comment]
Looks like it solved a long time ago.
Feel free to reopen the issue if you still need help. 👍
