### ISSUE TITLE
Can update second rows automatically?

### ISSUE THREAD

**Issue by vanney9** [skywinder/ActionSheetPicker-3.0#257]
I have to show to rows, and the content of second row is decided by the value of first row.
I store the first row data in a NSArray; store the second row data in a NSDictionary which key is the value of the first row.

Can the value of second row changed automatic when the first row scroll?

**Comment by skywinder** [comment]
You have to implement it by yourself. Please, check how `ActionSheetLocalePicker` is implemented. You have very similar task.

**Comment by skywinder** [comment]
Feel free to reopen issue, if you still have questions

**Comment by vanney9** [comment]
yeah, i have figured out this problem, thx!
