### ISSUE TITLE
How can I use this without storyboard on iPad?

### ISSUE THREAD

**Issue by umekun123** [skywinder/ActionSheetPicker-3.0#260]
Hello,
my project don't use storyboard, so I set self.view for origin, but in this case, it doesn't show picker on iPad.

Is there any way to set frame or rect for iPad without storyboard?
Especially from tapped tableview cell, not from barbuttonitem.

**Comment by umekun123** [comment]
I tried using presentFromRect, but no luck yet.

    CGRect selectedRect = [self.tableView rectForRowAtIndexPath:self.tableView.indexPathForSelectedRow];
    ActionSheetStringPicker* picker = [[ActionSheetStringPicker alloc] initWithTitle:@"Select a Block"
                                                                                rows:_dateStrings
                                                                    initialSelection:selectedRow
                                                                           doneBlock:done
                                                                         cancelBlock:cancel
                                                                              origin:self.view];
    picker.presentFromRect = selectedRect;
    [picker showActionSheetPicker];

**Comment by umekun123** [comment]
It was my bad, I wrote this before the method by mistake!  What a stupid mistake..
    [tableView deselectRowAtIndexPath:indexPath animated:YES];

**Comment by skywinder** [comment]
Ok! Thanks for update!
