### ISSUE TITLE
Import statement outdated on Swift-example

### ISSUE THREAD

**Issue by guillosaracco** [skywinder/ActionSheetPicker-3.0#261]
Hi there,

Thanks for this great contribution.
I just tried the swift-example made a very small fix to make it work out of the box by changing the import statement. Also added a podfile in order to have the sample app already set up to run 'pod install'.

**Comment by guillosaracco** [comment]
Apologies for the confusing commits there. The last one (ba5b6d4) does the trick

**Comment by skywinder** [comment]
@guillosaracco no worries, thanks for the PR! :+1:
