### ISSUE TITLE
Multi Line Rows

### ISSUE THREAD

**Issue by NVAT** [skywinder/ActionSheetPicker-3.0#263]
Hello Everybody How can I set multi line row?

**Comment by skywinder** [comment]
If `UIActionPicker` is support multiple rows, so you can do it. it's native control.

**Comment by skywinder** [comment]
have a look this question exactly about this:
http://stackoverflow.com/questions/12865008/uipickerview-with-two-rows

**Comment by NVAT** [comment]
Thanks for answer,but I would like to wrap my row not multi row
