### ISSUE TITLE
How to update Toolbar button title?

### ISSUE THREAD

**Issue by binaries10** [skywinder/ActionSheetPicker-3.0#265]
I wanaa Toolbar Button title update

default title is done, cancel

if change title yes and no 

how do i do?

//Source
ActionSheetDatePicker *datePicker = [[ActionSheetDatePicker alloc]initWithTitle:@"Some Title." datePickerMode:UIDatePickerModeDate selectedDate:[NSDate date] doneBlock:^(ActionSheetDatePicker *picker, id selectedDate, id origin) {
        
        NSLog(@"Picker: %@, Index: %@, value: %@",picker, selectedDate, origin);
    } cancelBlock:^(ActionSheetDatePicker *picker) {
        
    } origin:sender];
    
    [datePicker showActionSheetPicker];

**Comment by skywinder** [comment]
You can't update title after picker is presented (called `showActionSheetPicker`)
