### ISSUE TITLE
Use with inputView

### ISSUE THREAD

**Issue by pbassut** [skywinder/ActionSheetPicker-3.0#266]
Looks like it's not possible to use ActionSheetPicker as an input view.
It would be great to have this feature to make this library a drop-in replacement for uidatepicker(or uipicker in general).

Currently, we have to listen for a focus action on a UITextField, for example, and show the picker from there.

Any thoughts?

**Comment by jrustonapps** [comment]
+1

**Comment by waltermvp** [comment]
Agree with @pbassut. Ive been using this framwork for some years now and it works well, gets the job done and im very grateful for that. However it would be great to have a method to be able to use `UITextField`'s `inputView` and `inputAccesoryView`. 
It seem's this is what apple "wants you to do" also here is a answer from a well known apple engineer where he echoes my sentiment.
http://stackoverflow.com/questions/12828398/show-datepicker-on-textfield-tap

**Comment by skywinder** [comment]
Sounds good. If anybody would like to implement it - I would be glad to review PR 😉

**Comment by skywinder** [comment]
Close for now. Feel free to comment issue if you still need help. 👍
