### ISSUE TITLE
Can we change display format of action sheet date picker?

### ISSUE THREAD

**Issue by raheelahmad786** [skywinder/ActionSheetPicker-3.0#268]
Hi,

I am using ActionSheetDatePicker to display date, Can i change the display format of action sheet date picker i.e dd / mm / yyyy. ?

Thanks,

**Comment by oziphantom** [comment]
Yes, you need to have the locale set to something that uses it that way. For example 

[picker setLocale:[NSLocale localeWithLocaleIdentifier:@"en-AU"]];

That will give you DD/MMM/YYYY

**Comment by SalvatoreAD** [comment]
is it possible to have this format "eeee, dd / mm/ yyyy"??

**Comment by Afrah-Tayyab** [comment]
Hi,
I am using ActionSheetDatePicker to display time, Can i change the display format of action sheet date picker i.e h:mm a. as i am using two languages it working fine for english lang but for arabic it works like "a mm:h" i want that for both it should work like "h:mm a"
Thanks,

**Comment by skywinder** [comment]
Hello. this question is related to `UIDatePicker` (all the properties that it has you can set)
[See this topic for details about date format.](https://stackoverflow.com/questions/43586775/ios-how-to-change-date-picker-display-format)

If it doesn't work: You can create your own picker based on `AbstractActionSheetPicker` or use  `ActionSheetCustomPicker` to implement it.

Feel free to reopen it, if it still actual. 👍
