### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oziphantom** [skywinder/ActionSheetPicker-3.0#270]
When you show a picker control with a single column( might also happen on multiple columns but not tested yet ) and the user just pressed Done as they want the first value, the code will crash trying to index into the options array with -1

**Comment by tony-osibov** [comment]
I am sure you have already found this work around, but just incase... I had this same issue and my solution was to pass 0 as the initialSelection when init the action sheet.

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
