### ISSUE TITLE
How to change "Done" and "Cancel" to other language?

### ISSUE THREAD

**Issue by EdgeWiz** [skywinder/ActionSheetPicker-3.0#274]
as the title, I can't find the way to change the text in barButton to other language...

**Comment by cpvbruno** [comment]
Why closed the issue?

**Comment by enix223** [comment]
you can add your language into Project / Info / Localizations, then the "Cancel" & "Done" button will be displayed in your local language. solution goes [here](http://stackoverflow.com/questions/4089584/uibarbuttonsystemitem-localizable)

**Comment by gulzatique** [comment]
I used this bit of code:
`//localize barButtons
        picker?.setDoneButton(UIBarButtonItem.init(title: "PICKER_Done".localized, style: .done, target: self, action: nil))
        picker?.setCancelButton(UIBarButtonItem.init(title: "PICKER_Cancel".localized, style: .done, target: self, action: nil))`

 and localized is method which I use to localize all my strings on the fly : 
`extension String {
    var localized: String {
        let key = Constants.DefaultsKeys.locale
        if let _ = UserDefaults.standard.string(forKey: key) {} else {
            UserDefaults.standard.set("ru", forKey: key)
            UserDefaults.standard.synchronize()
        }
        
        let lang = UserDefaults.standard.string(forKey: key)
        
        let path = Bundle.main.path(forResource: lang, ofType: "lproj")
        let bundle = Bundle(path: path!)
        
        return NSLocalizedString(self, tableName: nil, bundle: bundle!, value: "", comment: "")
    }
}
`
