### ISSUE TITLE
[Question] How to deal with a UIBarButtonItem as the origin?

### ISSUE THREAD

**Issue by allaire** [skywinder/ActionSheetPicker-3.0#275]
Looks like it only accepts UIView, so when the sender is a UIBarButtonItem, app crashes. Right now I'm setting the origin on my UIToolbar, but I'm wondering if there's a better way.

Thanks @skywinder !

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
