### ISSUE TITLE
Dismissing during orientation change UI issue

### ISSUE THREAD

**Issue by AnthonyMDev** [skywinder/ActionSheetPicker-3.0#276]
When the application is in portrait mode and I use the `doneBlock` to present a view controller that only supports landscape orientation, the animation for the action sheet picker dismissal doesn't look right.

The screen rotates while the action sheet is trying to dismiss and the action sheet retains its smaller width while dismissing.

**Comment by skywinder** [comment]
Is there any ways, how can we fix it?

**Comment by AnthonyMDev** [comment]
I don't really have a solution myself yet. I just wanted to bring it to your attention. I'll think about it and if I come up with anything I'll let you know.

**Comment by ahsanebrahim** [comment]
any update on this @skywinder

**Comment by skywinder** [comment]
@ahsanebrahim No, sorry. If you rget this issue also, please specify this issue in details.  I can't reproduce it.
