### ISSUE TITLE
In Swift, No such module 'CoreActionSheetPicker'

### ISSUE THREAD

**Issue by heqichang** [skywinder/ActionSheetPicker-3.0#279]
Hi,

I tried to import your framework by CocoaPods in Swift, but occur error by use 'import CoreActionSheetPicker'. Use 'import ActionSheetPicker_3_0' is fine.

My CocoaPods's version is 1.0, Xcode's version is 7.3.

**Comment by Cj370118568** [comment]
Same promble! No such module 'CoreActionSheetPicker'.please help

**Comment by funkyLover** [comment]
@heqichang @Cj370118568  try 'import ActionSheetPicker_3_0'?

**Comment by faogustavo** [comment]
I got the same error. I'm using fabric but with this lib its not working.

**Comment by skywinder** [comment]
@faogustavo did you try `import ActionSheetPicker_3_0` or `import CoreActionSheetPicker` or both?

**Comment by faogustavo** [comment]
Yeps. But now its working. I was trying some things from the other isseus like this. One says to add a Bridging Header to swift with the header you need. I just added the header and it worked, no needs to import the header in obj-c. [Here is the sample.](https://medium.com/@stigi/swift-cocoapods-da09d8ba6dd2#.as5dz6i1n)

**Comment by arcioneo** [comment]
just downloadded the project, installed the pod and run it, none of the examples run because of the same error

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
