### ISSUE TITLE
The ActionSheetDatePicker date select the date the first time is right but select the second time is wrong

### ISSUE THREAD

**Issue by VolleyZ** [skywinder/ActionSheetPicker-3.0#285]

**Comment by skywinder** [comment]
Please add some description of your problem. some code exmples, expected result, actual result, stps too reproduce.

**Comment by VolleyZ** [comment]
NSDate *maxDate = [NSDate date];
    ActionSheetDatePicker *actionSheetPicker = [[ActionSheetDatePicker alloc] initWithTitle:title datePickerMode:UIDatePickerModeDate selectedDate:_currentDate
                                                                                     target:self action:@selector(dateWasSelected:element:) origin:self.view];
    
    [actionSheetPicker setMaximumDate:maxDate];
    [actionSheetPicker showActionSheetPicker];

- (void)dateWasSelected:(NSDate *)selectedDate element:(id)element {
    _currentDate = selectedDate;

    NSLog(@"%@",[selectedDate description]);
}

First time i select 2016-06-25 ，it log 2016-06-25 15:01:32 +0000。 this is right。
Second time，i select 2016-06-22 ， it log 2016-06-21 16:00:00 +0000。
Third，i select 2016-06-20， it log 2016-06-19 16:00:00 +0000。

Why？

**Comment by skywinder** [comment]
@VolleyZ I really would like to help, bot have no idea. Please provide full listing of code.
I just double checked this behaviour in project's example - `setMaximumDate:maxDate` works as expected - it doesn't allow to pick date after this date and return last choosen date.

**Comment by VolleyZ** [comment]
Thanks,I know the reason that it is the timezone is different.
In here, i write this code, it is OK.
```
-(void)dateWasSelected:(NSDate *)selectedDate element:(id)element {
     _currentDate = selectedDate;

     NSDateFormatter *dataFormat = [[NSDateFormatter alloc] init];
        [dataFormat setDateFormat:@"yyyy-MM-dd"];

     NSLog(@"%@",[dataFormat stringFromDate:selectedDate]);
}
```

**Comment by skywinder** [comment]
@VolleyZ ok, so issue was in timezone, not in datePicker, right?

**Comment by VolleyZ** [comment]
yes。

**Comment by monicarajendran** [comment]
hi, how can i get the corresponding date components like day, month,  year from the picker ?
