### ISSUE TITLE
ActionSheetCustomPicker with three component , initialSelections crash when the third component have no data,how to solve this problem?

### ISSUE THREAD

**Issue by SuRuiGit** [skywinder/ActionSheetPicker-3.0#289]
<img width="302" alt="728c1a22-3325-4fb4-a881-0f00883c3c81" src="https://cloud.githubusercontent.com/assets/13531664/16790241/da14365a-48e6-11e6-81ca-5b4ffadfc273.png">

crash info
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Number of sections not match'

**Comment by SuRuiGit** [comment]
the code 

`- (void)areaLabelClick:(UITapGestureRecognizer *)recognizer {
    if (self.index1!=0) {
        self.searchView.actionSheetPicker = [[ActionSheetCustomPicker alloc] initWithTitle:@"选择地区" delegate:self showCancelButton:YES origin:self.view initialSelections:@[@(self.index1),@(self.index2),@(self.index3)]];
    }
    else {
        self.searchView.actionSheetPicker = [[ActionSheetCustomPicker alloc] initWithTitle:@"选择地区" delegate:self showCancelButton:YES origin:self.view];
    }
    self.searchView.actionSheetPicker.tapDismissAction  = TapActionSuccess;
    [self.searchView.actionSheetPicker showActionSheetPicker];
}`

**Comment by moheny** [comment]
Did you solve this issue ? I'm having the same error !

**Comment by skywinder** [comment]
Please, kindly check, that params in the array, such as `self.index3` is in the range of items. I believe there are out of range.

**Comment by skywinder** [comment]
As I can see from tests:
https://github.com/skywinder/ActionSheetPicker-3.0/blob/272f31c25c9e8b45cf8e8ed2b99968d01b9a71bb/Pickers/ActionSheetCustomPicker.m#L82

It happens, when the amount of items in the array is not equal not the number of sections.

`[@(self.index1),@(self.index2),@(self.index3)]`

there is 3 items. 
on your picture only 2 column at all.

please provide full delegate methods to investigate this issue
