### ISSUE TITLE
Show custom view without picker

### ISSUE THREAD

**Issue by mikemike396** [skywinder/ActionSheetPicker-3.0#290]
Is there an easy way to not show a picker, but in place show my own custom view. I really like your pop up window and logic to use popover on iPad, but I need to use my own custom view inside the container. Thank You

**Comment by om-ha** [comment]
I wish somebody would answer this.

**Comment by skywinder** [comment]
You can create your own picker based on `AbstractActionSheetPicker` or use  `ActionSheetCustomPicker` to implement it.
