### ISSUE TITLE
iPad iOS 9 problem ActionSheetStringPicker position and size

### ISSUE THREAD

**Issue by balkarov** [skywinder/ActionSheetPicker-3.0#291]
My code:
```
    ActionSheetStringPicker *picker = [[ActionSheetStringPicker alloc] initWithTitle:NSLocalizedString(@"Choose your country", nil) rows:countriesNames initialSelection:index doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
        NSLog(@"Picker: %@, Index: %ld, value: %@", picker, (long)selectedIndex, selectedValue);
    } cancelBlock:^(ActionSheetStringPicker *picker) {
        NSLog(@"Block Picker Canceled");
    } origin:self.view];
```

![image](https://cloud.githubusercontent.com/assets/6030335/16952094/7bc47940-4dd0-11e6-945d-39750e7bed52.png)

**Comment by SuRuiGit** [comment]
I have the same problem
code：
`if ([self.searchView.areaLabel.text isEqualToString:@"全部"]) {
        self.searchView.actionSheetPicker = [[ActionSheetCustomPicker alloc] initWithTitle:@"选择地区" delegate:self showCancelButton:YES origin:self.view];
    }
    else {
        self.searchView.actionSheetPicker = [[ActionSheetCustomPicker alloc] initWithTitle:@"选择地区" delegate:self showCancelButton:YES origin:self.view initialSelections:@[@(self.index1),@(self.index2),@(self.index3)]];
    }
    self.searchView.actionSheetPicker.tapDismissAction  = TapActionSuccess;
    [self.searchView.actionSheetPicker setDoneButton:self.okBarButtonItem];
    [self.searchView.actionSheetPicker setCancelButton:self.cancelBarButtonItem];
    [self.searchView.actionSheetPicker showActionSheetPicker];`
<img width="397" alt="874bf30e-adb9-4e01-ab4a-f77554377aa9" src="https://cloud.githubusercontent.com/assets/13531664/17286491/868671f4-57fc-11e6-99e2-2984638014f0.png">

**Comment by SuRuiGit** [comment]
I solved this problem 

@property(nonatomic) BOOL popoverDisabled; // Disable popover behavior on iPad

ipad setting this property YES

**Comment by tobedev** [comment]
From my own experience, on iPad, you should set the origin to a subview, like a button for example. So you shouldn't use 'self.view' for the origin.

**Comment by skywinder** [comment]
@SuRuiGit thanks for update!
@tobedev you're right. the proper way to call popover, by setting according subview 👍
