### ISSUE TITLE
Swift 3.0 Migration

### ISSUE THREAD

**Issue by katriciab** [skywinder/ActionSheetPicker-3.0#293]
It would be great to start supporting the newest Swift

**Comment by skywinder** [comment]
@katriciab thanks for request. Did you find some issue with Swift 3 already? Can you briefly explain them here in a list?

**Comment by skywinder** [comment]
Thank you, Katricia. Get in touch.

**Comment by skywinder** [comment]
Ready to go on Swift 3.0  :)
