### ISSUE TITLE
ActionSheetMultipleStringPicker is not correctly updated after rotation

### ISSUE THREAD

**Issue by stanmots** [skywinder/ActionSheetPicker-3.0#294]
`ActionSheetMultipleStringPicker` is not correctly updated after the device rotation when the supported orientation is set to Portrait. When the supported is not set the picker is being dismissed (is this intended behaviour?). 

This bug can be easily reproduced using the example project. Just replace [this](https://github.com/skywinder/ActionSheetPicker-3.0/blob/master/Example%20Projects/ObjC-Example/Example/Classes/ActionSheetPickerTableViewController.m#L377) function with the following code:

```
- (IBAction)multiPickerButtonPressed:(id)sender {
    NSArray *rows = @[@[@"C", @"Db", @"D", @"Eb", @"E", @"F", @"Gb", @"G", @"Ab", @"A", @"Bb", @"B"],
                      @[@"Major", @"Minor", @"Dorian", @"Spanish Gypsy"]];
    NSArray *initialSelection = @[@2, @4];
    ActionSheetMultipleStringPicker *picker = [[ActionSheetMultipleStringPicker alloc] initWithTitle:@"Select scale with multipicker" rows:rows initialSelection:initialSelection doneBlock:^(ActionSheetMultipleStringPicker *picker, NSArray *selectedIndexes, id selectedValues) {
        NSLog(@"%@", selectedIndexes);
        NSLog(@"%@", [selectedValues componentsJoinedByString:@", "]);
    } cancelBlock:^(ActionSheetMultipleStringPicker *picker) {
        NSLog(@"picker = %@", picker);
    } origin:(UIView *)sender];
  [picker setSupportedInterfaceOrientations: UIInterfaceOrientationPortrait];
  [picker showActionSheetPicker];
}
```

And the image depicting the completely messed up layout:

![screen shot 2016-07-22 at 7 52 33 pm](https://cloud.githubusercontent.com/assets/10479469/17064598/ea896b7a-5045-11e6-9c62-e4cca7136933.png)

**Comment by ahsanebrahim** [comment]
any update on this?

**Comment by skywinder** [comment]
@ahsanebrahim @storix I can't reproduce it. I tried to change code. Start iPad and iphone on 9 and 10 ios - everything works as expected. Please give me additional details to reproduce it.
![simulator screen shot 31 oct 2016 10 00 56 am](https://cloud.githubusercontent.com/assets/3356474/19847625/ee767cb4-9f50-11e6-930b-e92b69f5b225.png)
