### ISSUE TITLE
ActionSheetDatePicker doesn't show up in iPad, where as the iPod, iPhone does. 

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [skywinder/ActionSheetPicker-3.0#295]
I have integrated ActionSheetDatePicker with textfield, which is working fine in iPhone, iPod device but when I run the same App in the iPad device the Picker View doesn't appear.

Please help me to figure it out.

**Comment by Rashesh-Bosamiya** [comment]
That's it, Done!

I found the solution, and now pickerView show up also in iPad.

A mistake was, I'd set the `origin` parameter as `sender.superView?.superView`

Then, I changed the `origin` parameter as simple `sender`

**Comment by skywinder** [comment]
Thanks for update!
