### ISSUE TITLE
Deprecated UIPopoverController API when targeting iOS 9

### ISSUE THREAD

**Issue by tobedev** [skywinder/ActionSheetPicker-3.0#296]
When targeting iOS 9, UIPopoverController is deprecated. There're 5 instances of this API inside of 'AbstractActionSheetPicker.m'. Any news when could the library be updated?

**Comment by skywinder** [comment]
@tobedev Hi. Yes, every new version of ios make me feel sick. And it's required to update library.
Sadly I'm quite limited in time now to update this library. I would much appreciated if somebody can help to update it for iOS 9.

**Comment by skywinder** [comment]
fixed
