### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by Yoloabdo** [skywinder/ActionSheetPicker-3.0#301]
I'd like to ask if there's a multiple selection from the picker, from an array of strings, thanks

**Comment by kevinonik** [comment]
Same here @skywinder

**Comment by skywinder** [comment]
Hi there. 
Sorry for late reply.
This is wrapper of native `UIPickerView`, that doesn't support multiple selection. I can't eve imagine, how could it possible with such view. But any suggestions are welcome!
