### ISSUE TITLE
Provide block action for "accidental" dismissal of popover

### ISSUE THREAD

**Issue by waltermvp** [skywinder/ActionSheetPicker-3.0#304]
Accroding to the HIG

```
Always save work when automatically closing a popover. It’s easy to dismiss a popover unintentionally by tapping another part of the screen. Discard work only when someone taps an explicit Cancel button.
```
https://developer.apple.com/ios/human-interface-guidelines/ui-views/popovers/

**Comment by waltermvp** [comment]
I see the cancel action is called but there is no way to differentiate a actual cancel button being tapped vs a user tapping on another part of the screen

**Comment by skywinder** [comment]
Yes, but you can disable handling touches in another part of the screen. Hope it helps. Feel free to reopen the issue, if you still need help. 👍

**Comment by skywinder** [comment]
Use `tapDismissAction` property to choose correct handling
