### ISSUE TITLE
Should you support Swift 3?

### ISSUE THREAD

**Issue by ihorodnikoff** [skywinder/ActionSheetPicker-3.0#305]

**Comment by AnthonyMDev** [comment]
I really hope this is coming soon. 

@skywinder I can make a PR for the swift 3 migration if needed.

**Comment by PeeJWeeJ** [comment]
I believe the actual classes are in Obj-C, so it should just require updating the example project and re-building for Swift 3, but you can download and import the picker classes with no problems.

**Comment by AnthonyMDev** [comment]
*face palm* I didn't realize this was in Obj-C. I've been trying to get migrations for so many dependencies this week I just forgot to check. Thanks! haha

**Comment by PeeJWeeJ** [comment]
haha. I wish I could could say I haven't done that... ☺️

**Comment by skywinder** [comment]
Hah! :)
Yep guys, this is classic Obj-C library, so no migrations needed and it works with any version of the swift out of the box 🎉
