### ISSUE TITLE
Crash - exceeds maximum index value of NSNotFound - 1

### ISSUE THREAD

**Issue by phiren** [skywinder/ActionSheetPicker-3.0#307]
Fatal Exception: NSRangeException
**\* -[NSMutableIndexSet addIndexesInRange:]: Range {18446744072121632456, 1} exceeds maximum index value of NSNotFound - 1

**Comment by DoctorG** [comment]
I'm not sure if you're getting the same error in ActionSheetDistancePicker.  I corrected the error in my app.  

Try changing line 171 in DistancePickerView.m
from                         UIView *view = [(subview.subviews)[0] subviews][1];
to                         UIView *view = [(subview.subviews)[0] subviews];

**Comment by phiren** [comment]
@DoctorG , how you can assign array of views to single view? i think there is some problem with the code you shared?, Also crash happens rarely when rotate device, etc.

**Comment by liaolj** [comment]
I also have the same error

**Comment by OlivierMaire** [comment]
I have the same error on the ActionSheetStringPicker.m
line 93, if you replace
`id selectedObject = (self.data.count > 0) ? (self.data)[(NSUInteger) self.selectedIndex] : nil;`
by 
`id selectedObject = (self.data.count > 0 && ((NSUInteger) self.selectedIndex) < self.data.count) ? (self.data)[(NSUInteger) self.selectedIndex] : nil;`
the problem should be resolved.

**Comment by DanielMartinezC** [comment]
Hi, i'm having similar issue with this line of code (line 93 of ActionSheetStringPicker.m) too:

Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndexedSubscript:]: index 3 beyond bounds [0 .. 2]

Is there any future fix or recommendation about this? 

Thanks!

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
