### ISSUE TITLE
Custm Cancel or Done Item Question

### ISSUE THREAD

**Issue by Geforceyu** [skywinder/ActionSheetPicker-3.0#308]
ActionSheetStringPicker *picker = [ActionSheetStringPicker showPickerWithTitle:@"Title" rows:[InfoCateManager sharedInstance].cateNames initialSelection:0 doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
        
    } cancelBlock:^(ActionSheetStringPicker *picker) {
        
    } origin:self.view];
    UIBarButtonItem *cancel = [[UIBarButtonItem alloc] initWithTitle:@"Custom Cancel" style:UIBarButtonItemStylePlain target:nil action:nil];
    UIBarButtonItem *done = [[UIBarButtonItem alloc] initWithTitle:@"Custom Done" style:UIBarButtonItemStyleDone target:nil action:nil];
    [picker setCancelButton:cancel];
    [picker setDoneButton:done];

I Do that to custom Item,But useless。I saw the mehod's implement,the picker is showing , afterwards the custom cancel item method execute，so is not refresh in time.
How Can i to do

**Comment by skywinder** [comment]
You have to init picker before showing it up. `showPickerWithTitle` fires pickers immediately.
There is other method to `init` picker. Then you customize buttons and call `showPicker` method.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
