### ISSUE TITLE
If minuteInterval is not working properly

### ISSUE THREAD

**Issue by jimmy0251** [skywinder/ActionSheetPicker-3.0#310]
If minuteInterval is set and user tapes done button without changing time, it returns provided `selectedDate` instead of adjusted time which was shown in the picker view.

**Comment by skywinder** [comment]
It could be appeared, if done pressed before picker is stopped. Isn't it?

**Comment by jimmy0251** [comment]
No, this happens when you don't touch picker at all and just press done button.
**For example**: Suppose you're showing picker with time 05:53 PM and minutes interval is 5. So picker will show time 05:55 PM, which is right behaviour. Now if you press done button without changing the time, you'll get time 05:53 PM in callback, which I think should be 05:55 PM.

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
