### ISSUE TITLE
Creating picker with custom and time data

### ISSUE THREAD

**Issue by antonijap** [skywinder/ActionSheetPicker-3.0#312]
Hi,

I need a picker that has custom data on the left column (I have an array with custom strings) and on the right, I need hours and minutes.

Can please somebody help me to set up a code for that. I'm using Swift 3 and these docs are not helping me.

**Comment by skywinder** [comment]
You can create your own picker based on `AbstractActionSheetPicker` or use  `ActionSheetCustomPicker` to implement it.
Feel free to reopen the issue, if you still need help. 👍
