### ISSUE TITLE
tapDismissAction not Working Swift 3.0 

### ISSUE THREAD

**Issue by sourabhsharmait** [skywinder/ActionSheetPicker-3.0#313]
```
ActionSheetStringPicker.show(withTitle: textfield.placeholder, rows: rowsArray, initialSelection: 0, doneBlock:
            { picker, values, indexes in
                
                picker?.tapDismissAction = TapAction.cancel
                
                print("values = \(values)")
                print("indexes = \(indexes!)")
                print("picker = \(picker)")
                textfield.text = (String(describing: indexes!))
                return
            },
        cancel: nil, origin: textfield)
    }
```

It Should be disabled when tapped outside the area.

**Comment by skywinder** [comment]
There is too late to setup it in block. You have to `init` picker, then set `tapDismissAction` and then call `showPicker` method. Feel free to reopen the issue, if you still need help. 👍

**Comment by sourabhsharmait** [comment]
var actionSheet:ActionSheetStringPicker!

 self.actionSheet = ActionSheetStringPicker.init(title: "Select Country Code", rows: countryArray, initialSelection: 0, doneBlock:
                        { picker, values, indexes in
                            

                            
                            print("values = \(values)")
                            print("indexes = \(indexes!)")
                            print("picker = \(picker)")
                            textfield.text = (String(describing: indexes!))
                            
                            return
                        },
                                                 cancel: nil, origin: sender)
                    self.actionSheet.tapDismissAction = TapAction.cancel
                    self.actionSheet.show()

Thanks it Works....
