### ISSUE TITLE
Access selectedvalue in cancelBlock

### ISSUE THREAD

**Issue by bb-git** [skywinder/ActionSheetPicker-3.0#314]
I would like to access the selectedvalue in the cancelBlock for performing some gui updates, is this somehow possible?

**Comment by skywinder** [comment]
Hi. No, Cancel means, that user don't want to sent any data about picked values.

**Comment by bb-git** [comment]
So maybe the question was wrong. I would like to use a custom button instead of the cancelblock. How can I access the selected Value in the actionblock?
Thanks

**Comment by skywinder** [comment]
@bb-git for not there is no option to do that.

**Comment by sabiland** [comment]
You can do it like this.

```
picker.addCustomButton(withTitle: "96".customLocalize(), actionBlock: {
            if let p = picker.pickerView as? UIPickerView
            {
                callback(possibleExportSizes[p.selectedRow(inComponent: 0)], true)
            }
        })
```
