### ISSUE TITLE
Swift 3.0/ Xcode 8 support 

### ISSUE THREAD

**Issue by zoufishanmehdi** [skywinder/ActionSheetPicker-3.0#318]
Hi, I'm looking to migrate my code to Swift 3. I was wondering if you will provide support for Swift 3 in the near future. Thanks!

**Comment by heshamsalman** [comment]
This is an Objective-C pod. 

By default, it is Swift 2 and Swift 3 compatible.

**Comment by skywinder** [comment]
https://twitter.com/ios_memes/status/1184426022281908224?s=21

**Comment by skywinder** [comment]
https://twitter.com/ios_memes/status/1184426022281908224?s=21

**Comment by skywinder** [comment]
Updated to Swift 5 already 🎉

**Comment by skywinder** [comment]
Migrating from Swift 2 to Swift 3 was like
![image](https://user-images.githubusercontent.com/3356474/74320517-580db700-4db3-11ea-931d-f0e0a8b00715.png)
