### ISSUE TITLE
Change value of picker programmatically 

### ISSUE THREAD

**Issue by zanesc** [skywinder/ActionSheetPicker-3.0#333]
I'd like to add a "Today" button to the toolbar of my ActionSheetDatePicker. Is there a way to set the value of the picker programmatically while it is displayed so that i can jump to Today? I've looked and haven't seen any available methods.

**Comment by Nathan187** [comment]
is your code in swift 3?  i've been struggling trying to get the date picker to even show.  would you mind sharing your code?

**Comment by zanesc** [comment]
There is sample code in the example projects. You should be able to copy and paste and it should work. If that doesn't work then there might be something else wrong with your project.

With that been said, I have switched to just using a native date picker. This project doesn't work with IQKeyboardManager which I need so I no longer use this.

**Comment by Nathan187** [comment]
the example code is not aimed at swift 3.  i did look a the sample code.  thanks for your reply

**Comment by zanesc** [comment]
The example code does work in Swift 3. The only thing you have to change is NSTimeInterval to TimeInterval.

**Comment by Nathan187** [comment]
@zanesc  i'm not trying to piss you off or get on your bad side.  i guess it's a matter of syntax that i'm not getting right.  i got it to show once...but the picker won't even show anymore.   if you have an example, i'd really appreciate it

**Comment by Nathan187** [comment]
@zanesc nevermind...i figured it out...thanks for not calling me stupid
