### ISSUE TITLE
Example causes EXC_BAD_ACCESS (fix)

### ISSUE THREAD

**Issue by vixez** [skywinder/ActionSheetPicker-3.0#336]
Hello,

In the doneBlock of the Objective-C example there will be the following line:
` NSLog(@"Picker: %@, Index: %@, value: %@",
                                                     picker, selectedIndex, selectedValue);
`

This wil cause EXC_BAD_ACCESS to be thrown.

To fix, just replace "Index: %@" by "Index: %d"
`NSLog(@"Picker: %@, Index: %d, value: %@",
                                                 picker, selectedIndex, selectedValue);`

This is something easy, but you might bang your head on why it's crashing when just trying to run the example as described on the main page.

**Comment by skywinder** [comment]
Thanks, I will  check it!

**Comment by skywinder** [comment]
@vixez yes, it's time to close, thanks :)

**Comment by skywinder** [comment]
fixed in latest commit
