### ISSUE TITLE
Decent example of a custom actionsheet in swift

### ISSUE THREAD

**Issue by Nathan187** [skywinder/ActionSheetPicker-3.0#337]
edit:  looks like the width of the popover view (on iPad) will always be 320.  is there a fix or a way to change this?

does anyone have a decent example of a custom action sheet in swift?

i can't get any of the delegate methods to work/fire.   i need to increase the width of the components (or the view itself)

thanks

**Comment by skywinder** [comment]
There is no such feature yet. I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
