### ISSUE TITLE
iPad problem

### ISSUE THREAD

**Issue by canaksoy** [skywinder/ActionSheetPicker-3.0#338]
<_UIPopoverBackgroundVisualEffectView 0x7f9a35465b20> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

textField.resignFirstResponder()
            let datePicker = ActionSheetDatePicker(title: "Date", datePickerMode: UIDatePickerMode.date, selectedDate: Date(), doneBlock: {
                picker, value, index in
                
                let dateFormatter = DateFormatter()
                dateFormatter.locale = Locale(identifier: "en_US_POSIX")
                dateFormatter.dateFormat = "YYYY-MM-dd"
                
                self.birthday.text = dateFormatter.string(from: value as! Date)
                return
            }, cancel: { ActionStringCancelBlock in return }, origin: textField.superview!.superview)
            datePicker?.show()

**Comment by canaksoy** [comment]
origin: self.birthday 

solved

**Comment by dangnguyenhuu** [comment]
Hi @canaksoy, im facing same problem, how did you solve it?
