### ISSUE TITLE
Wrong format specifier in example

### ISSUE THREAD

**Issue by H2CO3** [skywinder/ActionSheetPicker-3.0#344]
In the example found in the README, there's this line:

```
    NSLog(@"Picker: %@, Index: %@, value: %@",
        picker, selectedIndex, selectedValue);
```

Since `selectedIndex` is an `NSInteger`, i.e. a typedef for a built-in type, and not an Objective-C object, the `%@` format specifier here causes undefined behavior. It would be better to format it using a sufficiently wide format specifier for integers, like this:

```
    NSLog(@"Picker: %@, Index: %lld, value: %@",
        picker, (long long)selectedIndex, selectedValue);
```

**Comment by noorulain17** [comment]
Fixed in #518
