### ISSUE TITLE
how to set calendar identifier and custom locale for ActionSheetDatePicker

### ISSUE THREAD

**Issue by Lithium-HD** [skywinder/ActionSheetPicker-3.0#347]
In **Swift 3** with this line of code I manage to show Persian Date in UIDatePicker
`datePicker.calendar = NSCalendar(identifier:  NSCalendar.Identifier.persian)! as Calendar!`
`datePicker.locale = NSLocale(localeIdentifier: "fa_IR") as Locale`
I wanted to know if it's possible to change ActionSheetDatePicker calendar object to show Persian date?

**Comment by skywinder** [comment]
Hi. It works like a proxy to Cocoa `UIDatePicker`. So if it's possible to do in native `UIDatePicker` - you can do it in this picker as well.

**Comment by Lithium-HD** [comment]
thanks for your help. yeah I did it with this picker and it's showing Persian calendar now.

**Comment by Sobhi-IOS** [comment]
try this line :)     
 DataPicker?.locale = NSLocale(localeIdentifier: "ar") as Locale

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
