### ISSUE TITLE
Displaying full datetime picker

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [skywinder/ActionSheetPicker-3.0#349]
Hi, thanks for lib. I have a question:

Can i use this library for "dd.MM.yyyy hh:mm" picker?

**Comment by xjki** [comment]
Run Swift-Example target to see example with Date+Time picker.

**Comment by skywinder** [comment]
@ibrahimyilmaz7 did find an answer?
Feel free to reopen the issue, if you still need help. 👍
