### ISSUE TITLE
How to distinguish two different ActionSheetPicker when the picker have the same delegate?

### ISSUE THREAD

**Issue by MyNameIsWood** [skywinder/ActionSheetPicker-3.0#353]
I have two pickers in a controller, and the pickers have same delegate, then how to distinguish the two pickers in delegate method?

**Comment by jum** [comment]
Just use the tag value that any UIView has.

**Comment by xjki** [comment]
You can add instance variable for tracking which picker is active, use different picker action parameters for each picker, initialize each picker with its own doneBlock.

**Comment by noorulain17** [comment]
Agreed with @jum, use tag value.
