### ISSUE TITLE
How to set accessibility.identifier for each items

### ISSUE THREAD

**Issue by alfian0** [skywinder/ActionSheetPicker-3.0#354]
Hi, I use your framework to build my app, but I have question about set accessibilty.identifier for automation for each items. Can we set the identifier ?

- Xcode 8.2
- "skywinder/ActionSheetPicker-3.0" "2.2.0"

**Comment by zoufishanmehdi** [comment]
@alfian0 were you able to figure this out?

**Comment by skywinder** [comment]
There is no such feature yet. I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
