### ISSUE TITLE
How i can reload Data

### ISSUE THREAD

**Issue by MervinFlores** [skywinder/ActionSheetPicker-3.0#355]
I want to instert an array of String from a web service, so i want to show the ActionSheetMultipleStringPicker empty, and when i get the array String from web service response reload the picker with the new names of each row. like an UIPickerView.reloadData(). can help me how?

I a few words, i need a method to rename the rows.

**Comment by MervinFlores** [comment]
I solved with a trick... but for the next version build a method to change the titles rows when the picker is created and showed. Thanks

**Comment by irzyxa** [comment]
How did you do this? I have the same problem.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
