### ISSUE TITLE
Link to custom ActionSheet example (Swift or Objective-C)

### ISSUE THREAD

**Issue by om-ha** [skywinder/ActionSheetPicker-3.0#356]
Does anyone have a link for a custom ActionSheet example? 

A Swift one would be great, but if non-existent then an Objective-C one would suffice.

To be specific, I need to insert a custom subview inside the actionsheet picker and keep the toolbar to be default (just done and cancel buttons as well as title). The custom subview would be a custom date picker I have.

**Comment by skywinder** [comment]
There is example in this code.

**Comment by skywinder** [comment]
https://github.com/skywinder/ActionSheetPicker-3.0/blob/c1c9888d2d1bfe918245f350ca60f57bd50a040f/Example%20Projects/ObjC-Example/Example/Classes/ActionSheetPickerTableViewController.m#L200

here it is
