### ISSUE TITLE
Is there any way to only show the Future date not the past dates

### ISSUE THREAD

**Issue by aapacsoft** [skywinder/ActionSheetPicker-3.0#357]
Is there any way to only show the Future date not the past dates 

and Similar question:-  Is there any way to show only years without days and months

Any help will be appriciated

**Comment by ykws** [comment]
@aapacsoft Hi, you can disable the past dates, but visible.

`ActionSheetDatePicker` has `minimumDate` property.
If you set any date, disable before the date.

the following code snippet.
https://gist.github.com/ykws/ff74c7b3e08916d9abf0727c78bbfd9d

**Comment by wei18** [comment]
Close the issue, please refer to https://github.com/skywinder/ActionSheetPicker-3.0/issues/357#issuecomment-324425040
