### ISSUE TITLE
Memory leaks when using ActionSheetDatePicker on a modally presented UIViewController

### ISSUE THREAD

**Issue by Bhide** [skywinder/ActionSheetPicker-3.0#358]
`dateSelector = ActionSheetDatePicker.init(title: "", datePickerMode: .date, 
selectedDate: Date(), 
doneBlock: { [unowned self](datePicker, date, index) in
                    debugPrint("selected date: \((date as! NSDate).formatDateTime())")
                    
                    self.registerInfo["dob"] = AppUtils.stringFromDate(date: (date as! Date), dateFormat: "MM-dd-yyyy") //(date as! Date)
                    
                    self.tableView.beginUpdates()
                    
                    let userInfoModel = self.userDetailsDataSource[atindexPath.row]
                    
                    userInfoModel.disclosureTextObject = date
                    
                    self.userDetailsDataSource[atindexPath.row] = userInfoModel
                    
                    self.tableView.reloadRows(at: [atindexPath], with: .none)
                    
                    self.tableView.endUpdates()
                    
                    self.updateProfileBarButtonItem.isEnabled = true
                    
                    }, cancel: { [unowned self](datePicker) in
                        
                    }, origin: self.view)`

I ran instruments to check the leaks and found 53 leaks when I dismissed my UIViewController without pressing the `ActionSheetDatePicker`'s Cancel or Done. In this case, the presented UIViewController is not deallocated.

**Comment by adamhongmy** [comment]
I notice in [ActionSheetCustomPicker.h ](https://github.com/skywinder/ActionSheetPicker-3.0/blob/master/Pickers/ActionSheetCustomPicker.h)file, the delegate is strong. `@property(nonatomic, strong) id <ActionSheetCustomPickerDelegate> delegate;`  So this property was holding a strong reference to the view controller, which prevented it from ever being deallocated. Changing it to weak might solve the problem.

**Comment by MyNameIsWood** [comment]
@adamhongmy Do you mean modify the source code directly?

**Comment by adamhongmy** [comment]
@MyNameIsWood Yup. diy or wait for the owner to do so. Btw, **if only you use**  **ActionSheetCustomPicker** class, then it worth a shot to try it by changing `@property(nonatomic, strong) id <ActionSheetCustomPickerDelegate> delegate;` to `@property(nonatomic, weak) id <ActionSheetCustomPickerDelegate> delegate;`

**Comment by MyNameIsWood** [comment]
@adamhongmy I already do so. Will it cause any other bugs?

**Comment by adamhongmy** [comment]
@MyNameIsWood Not really. Btw are u calling ActionSheetCustomPicker class?

**Comment by adamhongmy** [comment]
For me it doesn't affect me whether I change it or not because i'm not using it.

**Comment by skywinder** [comment]
already fixed, thanks for investigation, @adamhongmy  👍
