### ISSUE TITLE
ActionSheetPicker-3.0 與 SVProgressHUD

### ISSUE THREAD

**Issue by s2339956** [skywinder/ActionSheetPicker-3.0#361]
ActionSheetPicker-3.0 與 SVProgressHUD 
我使用 ActionSheetPicker 選擇後 執行api SVProgressHUD 
SVProgressHUD 事件 會不動作
請問大家有遇到這樣的問題嗎！？

**Comment by koust** [comment]
Hi , 


I review this lib. ActionSheetPicker-3.0 is not working with SVProgressHUD. You should be  use **setContainerView**  method for work with SVProgressHUD.

**Comment by skywinder** [comment]
It seems that this issue has already been resolved. Feel free to reopen it, if it still actual. 👍
