### ISSUE TITLE
Tool bar buttons not appearing in testflight 

### ISSUE THREAD

**Issue by zoufishanmehdi** [skywinder/ActionSheetPicker-3.0#362]
Hi, date picker tool bar buttons appear in Xcode but not in testflight. This is happening on iPhone 7 iOS 10 and iOS 11. Any ideas? Thank you. 
![datepickertoolbarbuttonsnotvisible](https://user-images.githubusercontent.com/12058032/31190805-33b9853c-a90a-11e7-8e0f-b42caee314e0.png)

**Comment by yapiskan** [comment]
That is happening for me as well. Also, couldn't find a way to change the colors.

**Comment by yapiskan** [comment]
@zoufishanmehdi I found this: https://stackoverflow.com/questions/46107640/ios11-uitoolbar-contentview

Just place the blelow code in `createPickerToolbarWithTitle` method before returning the `pickertoolbar`.
`[toolbar layoutIfNeeded];`

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
