### ISSUE TITLE
Swift 4 

### ISSUE THREAD

**Issue by zoufishanmehdi** [skywinder/ActionSheetPicker-3.0#363]
Hi, are they any plans to migrate to Swift 4 in the near future? Thank you.

**Comment by jriiringan** [comment]
up for Swift 4

**Comment by zoufishanmehdi** [comment]
@jriiringan great, thank you

**Comment by skywinder** [comment]
Hey-hey!
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by swiftyAlpha** [comment]
how to make this run on swift project?

**Comment by swiftyAlpha** [comment]
how can I import CoreActionSheetPicker framework? I have tried manually but getting this issue:dyld: Library not loaded: ...Application/0F14AA40-07E8-403D-BAE7-687589E078FD/POCKETNEWZ.app/POCKETNEWZ
  Reason: image not found

**Comment by skywinder** [comment]
@swiftyAlpha  please, have a look at demo project that based on the swift.

**Comment by skywinder** [comment]
Updated to Swift 5 already 🎉
