### ISSUE TITLE
Change Colors

### ISSUE THREAD

**Issue by jeremiasdsa** [skywinder/ActionSheetPicker-3.0#365]
Hi,

Is that possible to have a set of colors like the image ? If so, how can I achieve that? 

![screen shot 2017-10-23 at 17 36 04](https://user-images.githubusercontent.com/9071775/31911988-da49118e-b818-11e7-8b0a-b6a0934293e9.png)

**Comment by skywinder** [comment]
You can create your own picker based on `AbstractActionSheetPicker` or use  `ActionSheetCustomPicker` to implement it.
