### ISSUE TITLE
In iOS 11 keyboard can not be stowed when the picker bounces

### ISSUE THREAD

**Issue by leoxpx** [skywinder/ActionSheetPicker-3.0#368]
when i choose a textField then choose picker, both of them couldn't down ,the view is death.

**Comment by Maxatma** [comment]
so just use `view.endediting()` ?

**Comment by skywinder** [comment]
Please, give provide more details about this issue. 
How it's going locked? SOme screenshots or code or both of them.

@Maxatma provide good quickfix for that, but actually it could be nice, if it should work without extra code. (for example, we can fire endEditing from the picker) 👍

**Comment by leoxpx** [comment]
`- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {`
......
`[cell setupTitlte:_inputInfosModel.inputLabel inputText:showArr.firstObject inputPlaceholder:_inputInfosModel.inputTip inputAction:nil selectAction:^{`
            
`[self dismissKeyboard]; // dismiss keyboard
ActionSheetStringPicker * picker = [[ActionSheetStringPicker alloc]initWithTitle:@"choose" rows:showArr initialSelection:0 doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
           ......
                } cancelBlock:nil origin:self.view];
        }];`
`- (void)dismissKeyboard {
 [[UIApplication sharedApplication] sendAction:@selector(resignFirstResponder) to:nil from:nil forEvent:UIEventTypeTouches]; // [self.view endEditing:YES]; // [cell.inputText resignFirstResponder]; // no effect all of them
}
`

![image](https://user-images.githubusercontent.com/16935402/34403302-196decc2-eb6d-11e7-9efc-fb6dcc9fcb3f.png)

**Comment by Maxatma** [comment]
@leoxpx Please, format your code, it is impossible to read. To help you, @skywinder  first need to read what problem you have.

**Comment by leoxpx** [comment]
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
        UITableViewCell * cell =   ......

        [cell setupTitlte:@"title" inputText:@"" inputPlaceholder:@"please input" inputAction:nil selectAction:^{

        [self dismissKeyboard]; // dismiss keyboard 

        ActionSheetStringPicker * picker = [[ActionSheetStringPicker alloc]initWithTitle:@"choose" rows:showArr initialSelection:0 doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
         ......
         } cancelBlock:nil origin:self.view]; }];
    }

    -(void)dismissKeyboard {
         [[UIApplication sharedApplication] sendAction:@selector(resignFirstResponder) to:nil from:nil forEvent:UIEventTypeTouches]; 
        // [self.view endEditing:YES]; 
        // [cell.inputText resignFirstResponder]; // no effect all of them 
    } `

    - (void)setupTitlte:(NSString *)title inputText:(NSString *)input inputPlaceholder:(NSString *)placeholder inputAction:(InputAction)inputAction selectAction:(InputAction)selectAction {
          if (selectAction) {
             self.selectAction = selectAction;
             [self.inputText addTarget:self action:@selector(selectedClick) forControlEvents:UIControlEventEditingDidBegin];
        }
    }
    - (void)selectedClick {
        self.selectAction();
    }

**Comment by Maxatma** [comment]
Not sure, if I correctly understood ur code, but 
  we only see how u initialize ur picker, nothing about how it appears.

**Comment by skywinder** [comment]
Thanks, a lot for dive into and helping with this,  @Maxatma 👍  Much appreciated!

@leoxpx  please, show the code, that presents picker. (ie `showPicker` method)

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
