### ISSUE TITLE
unknown error -1=ffffffffffffffff Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by Oren-Edrich** [skywinder/ActionSheetPicker-3.0#369]
I am trying to Archive my project however, I keep receiving this error:
`unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1`

My project will run completely fine on a simulator or on my phone, but it will not build, test, or archive. I have attached a screen shot of the error I have. Any help is greatly appreciated.
<img width="651" alt="screen shot 2017-11-04 at 11 28 47 pm" src="https://user-images.githubusercontent.com/33402256/32418856-1471742a-c23f-11e7-946a-479c195b239f.png">

**Comment by martinpfannemueller** [comment]
How did you fix the problem? I get exactly the same error message.

**Comment by Oren-Edrich** [comment]
It was a target issue. Find all of the ActionSheet files and make sure their targets are set for the app and the tests.

**Comment by martinpfannemueller** [comment]
I had basically the same problem. Thanks for sharing!
