### ISSUE TITLE
How to check - ActionSheetStringPicker is presented ?

### ISSUE THREAD

**Issue by StefaniOSApps** [skywinder/ActionSheetPicker-3.0#371]
How can I check if a ActionSheetStringPicker is presented?
I want update frame after device orientation change.

THX !!

**Comment by skywinder** [comment]
There are no callbacks after you call it to show up.
But it has to handle orientation change events automatically.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
