### ISSUE TITLE
Using ActionSheetCustomPicker

### ISSUE THREAD

**Issue by antonijap** [skywinder/ActionSheetPicker-3.0#373]
I need to create a custom picker with numbers. I am trying to find documentation, but it seems this one is not really covered. I need some assistance if possible.

**Comment by skywinder** [comment]
Hmmm. Please check out Example project in this repo.
https://github.com/skywinder/ActionSheetPicker-3.0#example-projects

There is Huge variate of any kind of pickers.

**Comment by antonijap** [comment]
There is no example I need. Thanks anyway.
