### ISSUE TITLE
Customise rowHeightForComponent

### ISSUE THREAD

**Issue by DmitriyBagrov92** [skywinder/ActionSheetPicker-3.0#374]
If i decide to input long text in row, they will be cutted.
It will be better to autoresize row height according string value or customise it.

Apple doc delegate method:
https://developer.apple.com/documentation/uikit/uipickerviewdelegate/1614386-pickerview

**Comment by skywinder** [comment]
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
