### ISSUE TITLE
ActionSheetPicker popover selection is not working for iPad on iOS 11+

### ISSUE THREAD

**Issue by pritamsalunkhe4** [skywinder/ActionSheetPicker-3.0#384]
Hello,

I am using ActionSheetPicker for iPhone and iPad but on iPad having iOS11+ the popover is not working. When I am trying to scroll the picker it will get dismissed automatically. I thought there will be some issue with my code but I have downloaded the Sample Project and getting same issue with that also.

Everything is working well on iOS 10 but not on iOS11+.

@skywinder Thanks in Advance. :)

**Comment by ambujshukla-cdn** [comment]
@pritamsalunkhe4 did you get the solution of this problem. I',m facing the same issue.

**Comment by xjki** [comment]
Which kind of picker you are having probems with? Can you show the code?
Just tested myself on iPad with iOS11 and iOS12 both Date picker and String picker as popover without issues.

**Comment by laindow** [comment]
I have same issue. This code don't show picker.

        let countryPicker = ActionSheetStringPicker(title: "Countries", rows: countryNames, initialSelection: startPos, doneBlock: { (actionPicker, selectedIndex, selectedValue) in
            
//            print("value = \(selectedValue ?? "")")
//            print("index = \(selectedIndex)")
            self.countryIndex = selectedIndex
            self.countryEdit?.text = selectedValue as! String?
            
        }, cancel: { (actionPicker) in
            //
        }, origin: self.view)
        countryPicker?.show()

**Comment by Afrah-Tayyab** [comment]
I am facing the same issue. I have added a date Picker on a button and a time picker on another button. it's working for Iphone all devices and all iOS Versions not working for Ipad real devices.

**Comment by Afrah-Tayyab** [comment]
> Hello,
> 
> I am using ActionSheetPicker for iPhone and iPad but on iPad having iOS11+ the popover is not working. When I am trying to scroll the picker it will get dismissed automatically. I thought there will be some issue with my code but I have downloaded the Sample Project and getting same issue with that also.
> 
> Everything is working well on iOS 10 but not on iOS11+.
> 
> @skywinder Thanks in Advance. :)

yes facing same issue. I also download the code and it was also making issue. please have a look . and @skywinder Thanks in Advance.

**Comment by Afrah-Tayyab** [comment]
Hey guys this is works for me.  Please use this...

Don’t pass self.view in origin please
pass button or text field.

If user click on button then show picker so please pass button in origin,
If user click on textfield then show picket then pass textfield in origin.

**Comment by Afrah-Tayyab** [comment]
> I have same issue. This code don't show picker.
> 
> ```
>     let countryPicker = ActionSheetStringPicker(title: "Countries", rows: countryNames, initialSelection: startPos, doneBlock: { (actionPicker, selectedIndex, selectedValue) in
> ```
> 
> // print("value = (selectedValue ?? "")")
> // print("index = (selectedIndex)")
> self.countryIndex = selectedIndex
> self.countryEdit?.text = selectedValue as! String?
> 
> ```
>     }, cancel: { (actionPicker) in
>         //
>     }, origin: self.view)
>     countryPicker?.show()
> ```

Pass the textfield in origin not view.

**Comment by noorulain17** [comment]
I faced the same issue as reported by @pritamsalunkhe4 above in `ActionSheetPicker-3.0 (2.3.0)`, though `ActionSheetPicker-3.0 (2.5.0)` has fixed this.
