### ISSUE TITLE
I have upgraded the project to Swift4. Now it has started given some warnings. Need to clear that.

### ISSUE THREAD

**Issue by idrees88** [skywinder/ActionSheetPicker-3.0#385]
I have upgraded the project to Swift4. Now it has started given some warnings. Need to clear that.

Deployment target I am using is iOS9.0

**Comment by alfian0** [comment]
same issue

**Comment by skywinder** [comment]
close in favor of #401

There is no such feature yet. I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
