### ISSUE TITLE
ActionSheet Crashes on Xcode 9.2

### ISSUE THREAD

**Issue by muzamilhassan1987** [skywinder/ActionSheetPicker-3.0#387]
App crashes on device but it works on simulator 
When i am using it on xcode 8 its working fine but when i update my project to xcode 9 app crashes on device but it works on simulator

Crash log 
`dyld: Library not loaded: @rpath/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0
  Referenced from: /var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0: code signing blocked mmap() of '/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0'
	/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0: code signing blocked mmap() of '/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0'
	/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0: stat() failed with errno=1
	/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0: code signing blocked mmap() of '/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0'
	/private/var/containers/Bundle/Application/A7B8157E-EBCA-40CF-AB85-65527BEE5A96/.app/Frameworks/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0: stat() failed with errno=1`

**Comment by LinusGeffarth** [comment]
I second this with the following warning:

```
dyld: Library not loaded: @rpath/ActionSheetPicker_3_0.framework/ActionSheetPicker_3_0
  Referenced from: /Users/[username]/Library/Developer/CoreSimulator/Devices/855A2E8D-DD75-464F-ADDE-6156B295E496/data/Containers/Bundle/Application/FCEF15D7-5F3F-4A90-B2DE-02C4B956A44A/MyApp.app/MyApp
  Reason: image not found
```

Current workaround: `shift + command + k` to clean the project, then re-run. Not pretty, but works for now.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
