### ISSUE TITLE
Can't set minimum or maximum date for time only picker

### ISSUE THREAD

**Issue by leeprobert** [skywinder/ActionSheetPicker-3.0#390]
I have two buttons, one for morning and one for evening. I want to restrict the hours in the picker to before and after midday. Here's my code:

`@IBAction func setTimeBtnAction(_ sender: Any) {
        
        let btn = sender as! UIButton
        let isMorning = btn == morningTimeBtn
        
        let calendar = Calendar.current
        var minDateComponent = calendar.dateComponents([.hour,.minute], from: Date())
        minDateComponent.hour = isMorning ? 0 : 12
        minDateComponent.minute = 0
        let minDate = calendar.date(from: minDateComponent)
        
        var maxDateComponent = calendar.dateComponents([.hour,.minute], from: Date())
        maxDateComponent.hour = isMorning ? 12 : 24
        maxDateComponent.minute = 60
        let maxDate = calendar.date(from: maxDateComponent)
        
        var defaultDateComponent = calendar.dateComponents([.hour,.minute], from: Date())
        defaultDateComponent.hour = isMorning ? 07 : 20
        defaultDateComponent.minute = 0
        let defaultDate = calendar.date(from: defaultDateComponent)
        
        let timePicker:ActionSheetDatePicker = ActionSheetDatePicker(title: "Pick a time", datePickerMode: .time, selectedDate: defaultDate, doneBlock: { (picker, value, index) in
            
            let timeFormatter:DateFormatter = DateFormatter()
            timeFormatter.dateFormat = "HH:mm"
            let btn = sender as! UIButton
            if btn == self.morningTimeBtn {
                
                self.morningTimeLabel.text = timeFormatter.string(from: value as! Date)
                Settings.notificationTimeMorning = value as? Date
                
            }else{
                
                self.eveningTimeLabel.text = timeFormatter.string(from: value as! Date)
                Settings.notificationTimeAfternoon = value as? Date
            }
            
        }, cancel: nil, origin: view)
        
        timePicker.minimumDate = minDate
        timePicker.maximumDate = maxDate
        
        timePicker.show()
    }`

**Comment by skywinder** [comment]
Hello. Looks like question is related to `UIDatePicker`, that is a subview of `ActionSheetDatePicker`. Nevertheless, you can set all the properties  via `ActionSheetDatePicker` as a proxy.
Please check the references of [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker)

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
