### ISSUE TITLE
ActionSheetDatePicker incorrect time order in Arabic

### ISSUE THREAD

**Issue by spijs** [skywinder/ActionSheetPicker-3.0#396]
I am noticing incorrect behavior when creating an ActionSheetDatePicker instance. It appears like the order of the time is incorrect in Arabic. It should be (English equivalent) AM 07:45 and it currently shows AM 45:07. Is there any way around this? In English everything seems to work as expected. It would look like everything is mirrored, but this is not what is expected in Arabic.

![image](https://user-images.githubusercontent.com/2649984/40350545-684ee152-5daa-11e8-9326-c43f01190b56.png)

Code used:
```
let datePicker = ActionSheetDatePicker(title: title, datePickerMode: .time, selectedDate: Date(), doneBlock: { [weak self] (_, value, _) in
            guard let weakSelf = self else { return }
            if let selectedValue = value as? Date {
                let selectedTime = selectedValue.timeStringFormat()
                // Do something with selected time
                }
            }
            }, cancel: { (_) in return }, origin: textField)
        datePicker?.setCustomLocale() // Custom function to translate Ok and cancel as well as set the locale
        datePicker?.show()
```

**Comment by skywinder** [comment]
Hi there. 
This is a wrapper of native `UIDatePicker`.
Is this reproducible in it?

**Comment by spijs** [comment]
I just tried it out with a simple UIDatePicker. No issues there.
![simulator screen shot - iphone 8 plus - 2018-05-31 at 10 20 03](https://user-images.githubusercontent.com/2649984/40770896-39f4fc4c-64bc-11e8-8db4-2d8fd38b4b8c.png)

**Comment by spijs** [comment]
It seems like it is ok in UIDatePicker. By changing the locale to Arabic I get the following screenshot: 
![simulator screen shot - iphone 8 plus - 2018-05-31 at 10 20 03](https://user-images.githubusercontent.com/2649984/40771682-4a610de4-64be-11e8-8046-2a13adf8dc68.png)

**Comment by skywinder** [comment]
@spijs thanks for reply. I'm not familiar with arabic numerics, can you tell, did you solve the issue?

**Comment by Afrah-Tayyab** [comment]
> I am noticing incorrect behavior when creating an ActionSheetDatePicker instance. It appears like the order of the time is incorrect in Arabic. It should be (English equivalent) AM 07:45 and it currently shows AM 45:07. Is there any way around this? In English everything seems to work as expected. It would look like everything is mirrored, but this is not what is expected in Arabic.
> 
> ![image](https://user-images.githubusercontent.com/2649984/40350545-684ee152-5daa-11e8-9326-c43f01190b56.png)
> 
> Code used:
> 
> ```
> let datePicker = ActionSheetDatePicker(title: title, datePickerMode: .time, selectedDate: Date(), doneBlock: { [weak self] (_, value, _) in
>             guard let weakSelf = self else { return }
>             if let selectedValue = value as? Date {
>                 let selectedTime = selectedValue.timeStringFormat()
>                 // Do something with selected time
>                 }
>             }
>             }, cancel: { (_) in return }, origin: textField)
>         datePicker?.setCustomLocale() // Custom function to translate Ok and cancel as well as set the locale
>         datePicker?.show()
> ```

Can you please send me the code you do in this Function.  datePicker?.setCustomLocale()

**Comment by Afrah-Tayyab** [comment]
> I am noticing incorrect behavior when creating an ActionSheetDatePicker instance. It appears like the order of the time is incorrect in Arabic. It should be (English equivalent) AM 07:45 and it currently shows AM 45:07. Is there any way around this? In English everything seems to work as expected. It would look like everything is mirrored, but this is not what is expected in Arabic.
> 
> ![image](https://user-images.githubusercontent.com/2649984/40350545-684ee152-5daa-11e8-9326-c43f01190b56.png)
> 
> Code used:
> 
> ```
> let datePicker = ActionSheetDatePicker(title: title, datePickerMode: .time, selectedDate: Date(), doneBlock: { [weak self] (_, value, _) in
>             guard let weakSelf = self else { return }
>             if let selectedValue = value as? Date {
>                 let selectedTime = selectedValue.timeStringFormat()
>                 // Do something with selected time
>                 }
>             }
>             }, cancel: { (_) in return }, origin: textField)
>         datePicker?.setCustomLocale() // Custom function to translate Ok and cancel as well as set the locale
>         datePicker?.show()
> ```

How you get this time in arabic i am not getting this in arabic as I have Change the language in arabic of my app..

**Comment by skywinder** [comment]
Hi. I'm not familiar with Arabic. 
Can't understand, what happens there and what should we change?

Please descibre exected result in details.

**Comment by skywinder** [comment]
please, have a look on my answer here: https://github.com/skywinder/ActionSheetPicker-3.0/issues/432#issuecomment-560248743

is it the same thing in your case? @spijs

**Comment by skywinder** [comment]
what's in the method `setCustomLocale`? is it your self defined method?

**Comment by Afrah-Tayyab** [comment]
yeah thanks i have search and it was helpful for me . thanks a lot .

**Comment by skywinder** [comment]
Close it in favor of #432.
