### ISSUE TITLE
 ActionSheetStringPicker change button title

### ISSUE THREAD

**Issue by reecreateeduardo** [skywinder/ActionSheetPicker-3.0#397]
Hi, I have tried countless options to try and change the title of the button with  ActionSheetStringPicker.

Could anyone help me with that?

` @IBAction func pickerBtnClicked(_ sender: Any) {
        ActionSheetStringPicker.show(withTitle: "Categories", rows: item, initialSelection: 1, doneBlock: {
            picker, value, index in
            
            print("value = \(value)")
            print("index = \(String(describing: index))")
            print("picker = \(String(describing: picker))")
       
            return
        }, cancel: { ActionStringCancelBlock in return }, origin: sender)
   
    }`

Any ideias? really stuck

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍

**Comment by skywinder** [comment]
@all-contributors please add @xjki  for developers, question, example
