### ISSUE TITLE
SupportedInterfaceOrientations Horizontal fixed

### ISSUE THREAD

**Issue by moheny** [skywinder/ActionSheetPicker-3.0#398]
As we all know we had problem with the supportedInterfaceOrientations property which doesn't take much effect.
I have fixed this issue by injecting the SIO property into the ActionSheetVC. 
https://github.com/moheny/ActionSheetPicker-3.0/tree/supportedInterfaceOrientations-fix

**Comment by skywinder** [comment]
Dear @moheny, Thanks for the feedback! I but my comments to the PR with the fix.

**Comment by moheny** [comment]
@skywinder Can you please review it again.

**Comment by moheny** [comment]
@skywinder Is there any reason for the delay?
