### ISSUE TITLE
Use with UITableViewCells

### ISSUE THREAD

**Issue by martinpfannemueller** [skywinder/ActionSheetPicker-3.0#4]
Hey there,
I tried to run this together with a UITableViewCell (didSelectRowAtIndexPath). This is not possible since I get an NSInternalInconsistencyException with the reason "Invalid origin provided to ActionSheetPicker". Is there a way to run this project with a UITableViewCell?

**Comment by VrasidasP** [comment]
Hello, 
this problem has returned in the latest version.
Presenting an ActionSheetPicker from -(void) tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath with the cell (or its label) as the origin does not work as it should.

**Comment by skywinder** [comment]
@VrasidasP can you provide example, how to reproduce it? 
In Project's example I create special table view to check this case. And it works.

**Comment by skywinder** [comment]
here is an example, how I call Picker:

```obj-c
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
    UILabel * sender = cell.detailTextLabel;
//    ActionStringDoneBlock done = ^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
//        if ([sender respondsToSelector:@selector(setText:)]) {
//            [sender performSelector:@selector(setText:) withObject:selectedValue];
//        }
//    };
//    ActionStringCancelBlock cancel = ^(ActionSheetStringPicker *picker) {
//        NSLog(@"Block Picker Canceled");
//    };
//    NSArray *colors = @[@"Red", @"Green", @"Blue", @"Orange"];
//    [ActionSheetStringPicker showPickerWithTitle:@"Select a Block" rows:colors initialSelection:0 doneBlock:done cancelBlock:cancel origin:sender];
    ActionSheetDatePicker *datePicker = [[ActionSheetDatePicker alloc] initWithTitle:@"Select a time" datePickerMode:UIDatePickerModeTime selectedDate:[NSDate date] target:self action:@selector(timeWasSelected:element:) origin:sender];
    datePicker.minuteInterval = 5;
    [datePicker showActionSheetPicker];
}
```

**Comment by VrasidasP** [comment]
Indeed you are correct, it is working fine.
I have a slightly more complex view hierarchy (my tableview is inside a UICollectionViewCell) and my setup was not 100% correct.
I finally got it right and re-tested, everything works ok in the latest version.

Sorry for the inconvenience and thank you for the excellent library! :)

**Comment by skywinder** [comment]
@VrasidasP you're welcome!
