### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by AndreaMiotto** [skywinder/ActionSheetPicker-3.0#401]
Hi, are they any plans to migrate to Swift 4.2 in the near future? Thank you.

**Comment by xZeok** [comment]
please!! swift 4.2 support! thanks!

**Comment by skywinder** [comment]
Hello. I'm cleanup the code. should work now. 
 I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by skywinder** [comment]
Updated to Swift 5 already 🎉
