### ISSUE TITLE
ActionSheetStringPicker.show auto dismiss the view in doneBlock

### ISSUE THREAD

**Issue by russeljayvitriolo** [skywinder/ActionSheetPicker-3.0#408]
Hi I use SCLAlertView to pop up an alert view, my issue is in doneBlock, whenever I pop up an alert it auto dismiss it.

**Comment by skywinder** [comment]
Hello. please check the latest version. Should be fixed. 
Feel free to reopen the issue, if you still need help. 👍

**Comment by skywinder** [comment]
You can create your own picker based on `AbstractActionSheetPicker` or use  `ActionSheetCustomPicker` to implement it.
