### ISSUE TITLE
ActionSheetPickerView Picker View not appearing for iPAD 

### ISSUE THREAD

**Issue by mbijapur** [skywinder/ActionSheetPicker-3.0#416]

**Comment by mbijapur** [comment]
ActionSheetPickerView Picker View not appearing for iPad, while the same works on iPhone.

**Comment by Maxwell6635** [comment]
Same here , I also facing this issues. Ipad is not showing the ActionSheetPickerView

**Comment by laindow** [comment]
That from previous questions - works fine

You need to specify proper "origin" param. Usually it's a button on which user clicked. When self.view is specified popup is shown outside screen.

**Comment by skywinder** [comment]
Hello. please check the latest version. Should be fixed. 
Feel free to reopen the issue, if you still need help. 👍
