### ISSUE TITLE
#picker ui not showing properly on ios 13 ipad

### ISSUE THREAD

**Issue by jpmeenaa** [skywinder/ActionSheetPicker-3.0#422]
Title bar of popup and UI not showing properly on iPad in iOS 13.
![Uploading issue ios 13.png…]()

**Comment by adya** [comment]
[Here](https://i.imgur.com/pQDMpYi.png) is a working screenshot of "not showing properly" popup.
Basically, it looks like popup has some offset which is ignored by the top toolbar. And it results in toolbar being cut off a bit.

**Comment by jpmeenaa** [comment]
I found the solution to this. I don't have knowledge about how to fork on github, I am learning about it and I will update it.

**Comment by Ankluas** [comment]
@jpmeenaa Hey! I have the same problem, could you provide or explain the solution?

**Comment by jpmeenaa** [comment]
@Ankluas Please check https://github.com/jpmeenaa/ActionSheetPicker

**Comment by skywinder** [comment]
@jpmeenaa did you fixed it? I'm out of iOS development now. WOuld you mind make PR and support this library?

**Comment by skywinder** [comment]
I see you are doing new commits to your fork. We can merge our efforts to not generate new parallel instases.

**Comment by skywinder** [comment]
I do my best to make this project alive. 
Please, let me know, how to fix it. 
I'm also would be glad for any help with this project. So if you are wondering about maintaining this project - please, let me know!
Here is a request topic, that I create about this: #348

**Comment by Ankluas** [comment]
@jpmeenaa Thank you! Could you maybe mention how exactly you fixed the named bug? Your MR contains a lot of changed, I need only the bugfix.

**Comment by Ankluas** [comment]
Could you please merge the fix regarding this bug with the ActionAheetPicker-3.0 version?

**Comment by skywinder** [comment]
I'm ready to review and merge shortly. 
@Ankluas which PR are you referencing to?

**Comment by Ankluas** [comment]
Hey there,

I am referencing the link given by @jpmeenaa 
https://github.com/jpmeenaa/ActionSheetPicker
which should (?) fix the mentioned bug above. It seems like there is no PR for the ActionSheetPicker-3.0 if I didn't oversee it.

**Comment by skywinder** [comment]
I belive this bug was fixed by https://github.com/skywinder/ActionSheetPicker-3.0/pull/444
