### ISSUE TITLE
not support dark mode on iOS 13

### ISSUE THREAD

**Issue by koust** [skywinder/ActionSheetPicker-3.0#424]
Hello everyone ,

I updated all my devices and my applications for iOS 13.
I work only light content mode for my application. "Actionsheetpicker" does not support if my phone is in dark mode

can u help with this?

**Comment by Praveeeenn** [comment]
@skywinder  Please help, Even for me facing the same issue.

**Comment by koust** [comment]
@Praveeeenn 

you should be use this pod.

`pod 'ActionSheetPicker-3.0', :git => 'https://github.com/arnoldxt/ActionSheetPicker-3.0', :commit => 'ad21f8c8908665ee68623d4fee6c26baaa4cb0dd'`

**Comment by huynguyencong** [comment]
> @Praveeeenn
> 
> you should be use this pod.
> 
> `pod 'ActionSheetPicker-3.0', :git => 'https://github.com/arnoldxt/ActionSheetPicker-3.0', :commit => 'ad21f8c8908665ee68623d4fee6c26baaa4cb0dd'`

Thank you. It work for me. I think you can create a pull request to this repo.

**Comment by blackturtle2** [comment]
I have developed as below.

```swift
if #available(iOS 13.0, *) {
            picker?.toolbarButtonsColor = .label
            picker?.pickerBackgroundColor = .systemGray6
            picker?.toolbarBackgroundColor = .systemGray6
        }
```

**Comment by koust** [comment]
@blackturtle2  thanks for another solution

**Comment by grehce** [comment]
> I have developed as below.
> 
> ```swift
> if #available(iOS 13.0, *) {
>             picker?.toolbarButtonsColor = .label
>             picker?.pickerBackgroundColor = .systemGray6
>             picker?.toolbarBackgroundColor = .systemGray6
>         }
> ```

Thoughts on where I can add the above in an @objc func?

>```swift
>   @objc func alarmButtonTapped(_ sender: UIButton) {
>        Analytics.logEvent("select_goal_entry_alarm_reminder_date", parameters: nil)
>        var components = DateComponents()
>        components.year = 200
>        let maxDate = Calendar.current.date(byAdding: components, to: Date())        
>        let _ = ActionSheetDatePicker.show(withTitle: "Select Alarm", datePickerMode: >UIDatePicker.Mode.dateAndTime, selectedDate: Date(), minimumDate: Date(), maximumDate: maxDate, doneBlock: { (picker, value, index) in
>            sender.setTitle((value as! Date).toString(withFormat: "E, MM/dd/yy, h:mm a"), for: .normal)
>            self.alarmText = (value as! Date).toString(withFormat: "E, MM/dd/yy, h:mm a")           
>            return
>        }, cancel: { ActionStringCancelBlock in return
>        }, origin: sender.superview)
>    }```

**Comment by koust** [comment]
@grehce please, can you check commit? because it is same solution.

**Comment by KestrelSystems** [comment]
This did not work for me. Since I only use a white theme I could overide by adding a key in Info.plist

**Comment by koust** [comment]
Which did you try them? @KestrelSystems

**Comment by nitinumaretiya123** [comment]
> @Praveeeenn
> 
> you should be use this pod.
> 
> `pod 'ActionSheetPicker-3.0', :git => 'https://github.com/arnoldxt/ActionSheetPicker-3.0', :commit => 'ad21f8c8908665ee68623d4fee6c26baaa4cb0dd'`

still not working in iOS 13

**Comment by koust** [comment]
> > @Praveeeenn
> > you should be use this pod.
> > `pod 'ActionSheetPicker-3.0', :git => 'https://github.com/arnoldxt/ActionSheetPicker-3.0', :commit => 'ad21f8c8908665ee68623d4fee6c26baaa4cb0dd'`
> 
> still not working in iOS 13

Can you check pod version? because I'm using as see in the example. 
Thanks

**Comment by skywinder** [comment]
Hey, guys. I’m super busy with other projects. If someone knows how to fix it: please make a PR. I would very appreciate for your help! 🙌
Ps
@huynguyencong did you found a solution?

**Comment by skywinder** [comment]
Looks like #421 should fix this.

**Comment by logeshvijayan** [comment]
@koust How did you override the value in plist.I also have a light background for Picker view but I couldn't able to fix it using picker text attributes

**Comment by koust** [comment]
@logeshvijayan I use pod version directly and its working. Do u own the last version?

**Comment by logeshvijayan** [comment]
@koust  So this is my case.My Application has a dark background by default and the overall  label colour was set to white.My picker view has a white background and my label colour needs to set in Black.So I need to override the white colour when the picker view is called.(I use latest swift)

I tried to update my pods to the latest version and set picker attributes but nothing worked.What do you mean by using the pod version directly.?
