### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by tradingstratagem** [skywinder/ActionSheetPicker-3.0#426]
Any chance to add support to SPM?

**Comment by skywinder** [comment]
There is no such feature yet. I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by skywinder** [comment]
I start to migrate in `SPM ` branch, but have no luck
the test project attached to this pranch.

**Comment by skywinder** [comment]
error:
`Umbrella directory '/XXX/ActionSheetPicker-3.0/CoreActionSheetPicker/include' not found`

Don't know how to fix it.

**Comment by skywinder** [comment]
fixed in [\#503](https://github.com/skywinder/ActionSheetPicker-3.0/pull/503) ([by noorulain17](https://github.com/noorulain17))
