### ISSUE TITLE
ActionSheetPicker values are not being displayed on iPhone on iOS 13

### ISSUE THREAD

**Issue by kirankumarg99** [skywinder/ActionSheetPicker-3.0#427]
ActionSheetPicker values are not being displayed on iPhone on iOS 13. But on scrolling on the picker and select a value(not visible on the screen), the selected item value is updating in the label .
Could you please help

**Comment by kirankumarg99** [comment]
![image](https://user-images.githubusercontent.com/42087869/67439260-615ff180-f613-11e9-94b0-0224b749b9e8.png)

I have attached the image as well

**Comment by gaozm0509** [comment]
same problems
iOS 12 dark mode causing the problems

**Comment by vincedev** [comment]
Same problem here, values are in the list, but text color is white, on a white background

**Comment by xjki** [comment]
You can resolve dark mode issues using pickerTextAttributes property.

Example:

```
NSDictionary *rowTextAttributes = @{NSFontAttributeName :font, NSForegroundColorAttributeName : textColor, NSBackgroundColorAttributeName : backgroundColor};
[rowTextAttributes enumerateKeysAndObjectsUsingBlock:^(id  key, id  obj, BOOL * _Nonnull stop) {
    picker.pickerTextAttributes[key] = obj;
}];

```

**Comment by skywinder** [comment]
Hello. please check the latest version. Should be fixed. 
Feel free to reopen the issue, if you still need help. 👍
