### ISSUE TITLE
Change of Date or Time position Left to right or Right to Left

### ISSUE THREAD

**Issue by Afrah-Tayyab** [skywinder/ActionSheetPicker-3.0#432]
I am using Multi Language in my project. I want to change position time i.e (H:MM:SS) LTR in English and also in Arabic have to remain same (H:MM:SS) LTR but it is changing according to language. I can't have access to make it restrict to remain same.

**Comment by skywinder** [comment]
Hi, thanks. Looks like it's related to `UIDatePicker ` itself. you can adjust it as you want.

please look at this: https://stackoverflow.com/questions/47049344/localizing-customizing-the-date-format-of-a-uidatepicker

ALl the pickers has public property `locale`
try to use `picker.locale = Locale(identifier: "ar")` and let me know if it works for you. 👍

**Comment by Afrah-Tayyab** [comment]
yeah its worked. thanks a lot.

**Comment by skywinder** [comment]
Awesome! glad to hear!
You are Welcome! 

@Afrah-Tayyab can we close #396 as well? is it the same issue described there?
