### ISSUE TITLE
i want to set the date format to be "h:mm a" As i am using multi languages. english and arabic

### ISSUE THREAD

**Issue by Afrah-Tayyab** [skywinder/ActionSheetPicker-3.0#457]
I want the date format to be always "h:mm a"  as i am using two languages for my project and for english language it is working fine and when i change language to arabic it show in the format like "a mm:h". 
Please guide me what to do for this i want that it should  always view time in "h:mm a"  this format rather it is in arabic or english.

**Comment by skywinder** [comment]
Duplicate of #383

**Comment by skywinder** [comment]
@Afrah-Tayyab please, check the answer there, thanks, that updated that question.
 I hope my answer  will  help you to solve this
