### ISSUE TITLE
[BUG] - HIGH - Not working on screen rotation + Not working in Landscape

### ISSUE THREAD

**Issue by StefaniOSApps** [skywinder/ActionSheetPicker-3.0#460]
Unfortunately I had to find out that the layout is destroyed when rotating under iOS 13. I have already checked it under 2.4.1 (from 2017) and also checked with develop branch with #379 . This error also exists with this version or with the develop branch.

I created a demo git so that you can easily reproduce it.
https://github.com/StefaniOSApps/ActionSheet-Example

The error is shown in this video.
![Screen Record](https://user-images.githubusercontent.com/29314643/71644229-44a40200-2cc5-11ea-8808-0733d1a193c7.gif)

**Comment by StefaniOSApps** [comment]
@skywinder

**Comment by skywinder** [comment]
@StefaniOSApps Oh, got it. thanks for the mention and detailed description!

Rotations screen was always quite painfull for dynamic views.
I thing the best way to quick fix now - is just hide picker when the screen is rotating. Thougs?

**Comment by StefaniOSApps** [comment]
This will not fix the problem. If you open the sheet in the landscape, it will already be extended incorrectly. This is shown in the GIF. @skywinder 
<img width="719" alt="GIF SCREEN" src="https://user-images.githubusercontent.com/29314643/71749291-4d3b3a80-2e75-11ea-9303-10b70e8e41f8.png">

**Comment by StefaniOSApps** [comment]
It will most likely be a method that is deprecated as of iOS 13.

**Comment by skywinder** [comment]
Can't realize, hot ti fix it in the right way. Looking forward to any suggestions.

**Comment by StefaniOSApps** [comment]
Hey, we need support. Any ideas? @xjki @BubiDevs @TimCinel, @kashifhisam or @delackner?

**Comment by Jack-s** [comment]
If it helps it looks like this is only an issue from the 2.4 release (2.3.1 seems to be fine). It also is an issue on iOS 12 as well so I don't think it's a iOS 13 specific issue.

**Comment by StefaniOSApps** [comment]
yes, it is most likely a bug generated by an iOS update.

**Comment by skywinder** [comment]
@Jack-s confirmed, in 2.3.1 it works. (it's simply dismisse picker)

@StefaniOSApps all that I can do now: to make an action, to dismiss the picker upon rotation. In most cases, it wouldn't be a problem. And I will preserve boolean trigger to switch off that behavior (with the warning, that developer do this at his own risk and it's not tested).

Thoughts?

**Comment by StefaniOSApps** [comment]
I don't think you have yet understood that the picker no longer works in the landscape. This is the main problem. You can also dismiss a picker by using your own methods.
![ezgif-6-ac2350cea71e](https://user-images.githubusercontent.com/29314643/74084098-aba69a80-4a6b-11ea-97a4-4bfa9f14a068.gif)

see demo project https://github.com/StefaniOSApps/ActionSheet-Example

**Comment by StefaniOSApps** [comment]
btw ... the video above was made with 2.3.1 @Jack-s @skywinder 
```
Downloading dependencies
Installing ActionSheetPicker-3.0 2.3.1 (was 2.4.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by skywinder** [comment]
oh, crap. @StefaniOSApps I'm digging into it.

Nope, I tried to run on 2.3.1 - it works fine on ios 11 and ios 13. SO will go deep into diff now.

ps. your project doesn't specify version: 
look at podfile: `  pod 'ActionSheetPicker-3.0'`

so you still use the latest one.

p.s. hope your Energy Tracker  doesn't affect too much. will do my best right now.

**Comment by skywinder** [comment]
Gotcha. @moheny  changes brokes rotation logic. now it works. But I have to dismiss picker on iPhones during rotation. (for iPad it works as it was before)

**Comment by skywinder** [comment]
Fixed in `2.4.2` 🎉

**Comment by skywinder** [comment]
rotation fixes in ACP looks like.. 😂
![image](https://user-images.githubusercontent.com/3356474/74321157-69a38e80-4db4-11ea-87d7-b5bf20cedad7.png)

**Comment by StefaniOSApps** [comment]
@skywinder the commit (change podfile) was not pushed. I have now pushed the changes ([commit](https://github.com/StefaniOSApps/ActionSheet-Example/commit/48ce5538a86fae4ca9e96435932c85cc57f2274e)) I have now extensively tested it and it fixes the problem on 13.0. However, the Dismiss rotation is broken. We currently differentiate between iPad true and false. In the case of iPad == false, one could revise and solve with a transition delegate. I have now implemented this in my new project regardless of you in this way and it looks good. The rotation also looks clean.

**Comment by skywinder** [comment]
Just dun your example. looks good.

What you mean, "Dismiss rotation is broken"? How does it look like? On iphone? Which position? Can you provide any steps to reproduce?

**Comment by StefaniOSApps** [comment]
use demo project from top. @skywinder 
![Ohne-Titel-2](https://user-images.githubusercontent.com/29314643/74596188-12b7e680-504c-11ea-90ab-068fae778fac.gif)

**Comment by skywinder** [comment]
oh, got it. in slow motion, I can see this. 
I will leave it as is for a while. 

so, please let me know, if you know, how to solve this.

**Comment by skywinder** [comment]
@StefaniOSApps Does it persist in latest versions?
