### ISSUE TITLE
Pickerview elements appear white

### ISSUE THREAD

**Issue by logeshvijayan** [skywinder/ActionSheetPicker-3.0#487]
While I am using my label colour as white.I couldn't able to override it .I am using swift and tried the below code to fix the issue but it never worked

![image](https://user-images.githubusercontent.com/42087869/67439260-615ff180-f613-11e9-94b0-0224b749b9e8.png)

I have attached the image as well

_Originally posted by @kirankumarg99 in https://github.com/skywinder/ActionSheetPicker-3.0/issues/427#issuecomment-545664526_

**Comment by logeshvijayan** [comment]
let rowTextAttributes: NSMutableDictionary = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 16), NSAttributedString.Key.foregroundColor: UIColor.black]
        for (key, value) in rowTextAttributes {
            vehiclePicker?.pickerTextAttributes[key] = value
        }

**Comment by logeshvijayan** [comment]
I Just need to set the colour of the labels to black.I tried setTextcolour function too but it never worked

**Comment by hechukwu** [comment]
Try this? `let picker = ActionSheetStringPicker.show(withTitle: title, rows: categoryNames as [Any], initialSelection: initialIndex, doneBlock: { picker, index, value in
                self.pickerIsActive = false
                }
                return
            }, cancel: { actionMultipleStringCancelBlock in
                self.pickerIsActive = false
                return
            }, origin: self.filterButton)
            if #available(iOS 13.0, *) {
                picker?.toolbarButtonsColor = .label
                picker?.pickerBackgroundColor = .systemGray6
                picker?.toolbarBackgroundColor = .systemGray6
                picker?.titleTextAttributes = [NSAttributedString.Key.foregroundColor : UIColor.label]
                picker?.setTextColor(UIColor.label)
            }
        }`

**Comment by skywinder** [comment]
@logeshvijayan did you try @hechukwu solution? does it work?

**Comment by noorulain17** [comment]
> @logeshvijayan did you try @hechukwu solution? does it work?

Also @logeshvijayan , what's the theme of your app/device when the above issue is faced? Dark/Light?

**Comment by logeshvijayan** [comment]
@noorulain17  My theme of the application is dark. So we set the label colour as white. But the picker view was set to white background.I haven't tried @hechukwu  solution.I created a new custom picker view based on our requirements.But i will try the solution and let you know the outcome. soon

**Comment by wei18** [comment]
The color is expected when dark mode on.
Close the issue due to verified on latest version.
![image](https://github.com/skywinder/ActionSheetPicker-3.0/assets/11254896/e8f4858c-04d4-4ac5-b1f4-60ddf13d5558)
