### ISSUE TITLE
Date picker on iOS 14

### ISSUE THREAD

**Issue by MikeZTM** [skywinder/ActionSheetPicker-3.0#492]
iOS 14 changed the style of UIDatePicker and need extra preferredDatePickerStyle to be set to have wheel style like before.

Right now it default to automatic which looks like a button with a popup date picker on click.

**Comment by bb-git** [comment]
Any update on this issue? Might get urgent with the release of iOS 14.

**Comment by bb-git** [comment]
In `ActionSheetDatePicker.m` inside `- (UIView *)configuredPickerView`

add
`    if (@available(iOS 14, *)) {
        [datePicker setPreferredDatePickerStyle:UIDatePickerStyleWheels];
    }`

**Comment by skywinder** [comment]
@bb-git Thank you. Would you mind to make a pull request?

**Comment by KunzManuel** [comment]
@bb-git You can now set the `datePickerStyle` in the `ActionSheetDatePicker.h`.
