### ISSUE TITLE
Date picker no longer showing wheels

### ISSUE THREAD

**Issue by KennyBrunton** [skywinder/ActionSheetPicker-3.0#496]
Updating my project in xcode 12, for some reason the date picker doesn't have wheels. Wondering if anyone else has reported this?

**Comment by KennyBrunton** [comment]
Just realised this is a duplicate

**Comment by skywinder** [comment]
@KennyBrunton Did you found solution? Can you reference to duplicate?

**Comment by KennyBrunton** [comment]
Hello,  Actually it relates to #492 
I've used the solution provided by bb-git temporarily, I presume it'll be committed at some point.

Thanks for getting in touch though.  Kenny
