### ISSUE TITLE
ActionSheetDatePicker still crash in Xcode12 when set the datePickerStyle 

### ISSUE THREAD

**Issue by jolyot** [skywinder/ActionSheetPicker-3.0#498]
Updating my project in Xcode12, and using `pod v2.5.1`. 
https://github.com/skywinder/ActionSheetPicker-3.0/issues/492 is supposed to be resolved in this [PR](https://github.com/skywinder/ActionSheetPicker-3.0/pull/488), but `ActionSheetDatePicker` still crash.

## What did you do?
When set the `datePcikerStyle` in the same way as [this example](https://github.com/noorulain17/ActionSheetPicker-3.0/blob/3debe8f38402d75ea374c18e9214113779679c86/Example%20Projects/Swift-Example/Swift-Example/ViewControllers/SWTableViewController.swift#L52-L63), crash occurs with this error message
```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ActionSheetDatePicker setDatePickerStyle:]: unrecognized selector sent to instance 0x158c1e070'
terminating with uncaught exception of type NSException
```

## What did you expect to happen?

ActionSheetDatePicker does crash in Xcode12 when set the `datePickerStyle`

## Environment
ActionSheetPicker_3_0 version: 2.5.1
Xcode version: 12.0 beta5

**Comment by noorulain17** [comment]
I had tested this on Xcode 12.0 beta 1,
will check again on Xcode 12.0 beta 5 & update you.

**Comment by noorulain17** [comment]
@jolyot I updated  `ActionSheetPicker-3.0` to version **2.5.1** in my a new sample project.
Tried on both Xcode 12.0 beta 1 & Xcode 12.0 beta 5 on simulators of iOS 13.4 & 14.0 & the sample code that you've mentioned above is working fine.

<img width="526" alt="Xcode12beta1" src="https://user-images.githubusercontent.com/6180345/92142294-a7d1cf80-ee24-11ea-942a-175666d8cb3a.png">
<img width="886" alt="Xcode12beta6" src="https://user-images.githubusercontent.com/6180345/92142341-ba4c0900-ee24-11ea-8709-df5f0c4e2de2.png">

**Comment by jolyot** [comment]
@noorulain17 
> Can you please try updating the pod again? If the crash is still reproduced, please post a video/screenshot of it.

OK! I will try!

**Comment by noorulain17** [comment]
Hey @jolyot ,
Any update on the issue?

**Comment by jolyot** [comment]
@noorulain17 
Sorry for the late reply.
I tried with Xcode12GM seed. It does not crash! 
But layout is a little bit broken in iOS14 simulator.

datePickerStyle is automatic | datePickerStyle is wheels
------------ | -------------
<img width="443" alt="スクリーンショット 2020-09-18 19 18 57" src="https://user-images.githubusercontent.com/8514870/93586865-f1edb000-f9e3-11ea-8868-49fed6cfe7da.png"> | <img width="445" alt="スクリーンショット 2020-09-18 19 26 22" src="https://user-images.githubusercontent.com/8514870/93587483-f2d31180-f9e4-11ea-9e9a-6ff0dcec9c6d.png">

However, this issue is about the crash in Xcode12 and it does not occur in Xcode GM seed. So, I think this issue has been resolved.

**Comment by noorulain17** [comment]
Thanks @jolyot for the update.
Yes I've also noticed the broken layout in the latest Xcode version. I've started  working on it and will soon release another stable version.

**Comment by jolyot** [comment]
@noorulain17 
>  I've started working on it and will soon release another stable version.

OK! I hope it will release soon!
