### ISSUE TITLE
iOS 14 datePicker not centered horizontally

### ISSUE THREAD

**Issue by ivan-magda** [skywinder/ActionSheetPicker-3.0#506]
In iOS 14.0 the `UIDatePickerView` is not centered in the container horizontally (width is less than the view width).

![Simulator Screen Shot - iPhone 8 - 2020-09-28 at 11 47 13](https://user-images.githubusercontent.com/8586063/94411447-40881080-0181-11eb-8420-4c2ff2d63592.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-28 at 11 47 16](https://user-images.githubusercontent.com/8586063/94411453-42ea6a80-0181-11eb-8bd7-d1614267c314.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-28 at 11 47 19](https://user-images.githubusercontent.com/8586063/94411457-43830100-0181-11eb-850b-0e7bad4d8b15.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-28 at 11 47 22](https://user-images.githubusercontent.com/8586063/94411461-441b9780-0181-11eb-90c6-03483461e66a.png)

**Comment by noorulain17** [comment]
Yes, that's a known issue (#502).
The same viewWidth is working fine on the lower iOS versions.

**Comment by ivan-magda** [comment]
@noorulain17 yes I saw this [comment](https://github.com/skywinder/ActionSheetPicker-3.0/pull/502#issuecomment-698448273) from you, I just created this issue so that it is not lost in the future.

**Comment by noorulain17** [comment]
Thanks, also you've got a valid point. We can centre the picker even if it's not taking the full viewWidth. Would be a better UX.

**Comment by ronfridman** [comment]
+1

**Comment by ronfridman** [comment]
Well.. I'm suggesting in the meantime until it will be fixed, to create a subclass of the ActionPicker and fix the constraint on the show() function. 

something like: 
```
import UIKit
import ActionSheetPicker_3_0
import SnapKit

@objc class CustomActionSheetDatePicker: ActionSheetDatePicker {

    override func show() {
        super.show()
        self.fixSize()
    }

    private func fixSize() {
        self.pickerView.snp.remakeConstraints { make in
            make.right.bottom.left.equalToSuperview()
            make.top.equalToSuperview().offset(44)
        }
    }
}
```

**Comment by skywinder** [comment]
Fixed in latest version!
