### ISSUE TITLE
Date Picker Wheels Not Showing Anymore on iOS 14

### ISSUE THREAD

**Issue by tkirby** [skywinder/ActionSheetPicker-3.0#510]
I've been using this a long time but now the format seems to have changed for date picker. Before it would show wheels to selcte day/month/year. Now it's only showing the date as a button and when I click on that it's popping up a calendar. How can I get back to the old format?

![Simulator Screen Shot - iPhone 11 - 2020-10-06 at 13 54 37](https://user-images.githubusercontent.com/43665/95169203-b6712500-07dc-11eb-8b77-c680eeeb077a.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-06 at 13 54 43](https://user-images.githubusercontent.com/43665/95169209-b96c1580-07dc-11eb-9732-34a02cd10ba2.png)

**Comment by noorulain17** [comment]
@tkirby the `datePickerStyle` in `ActionSheetDatePicker` is now dynamic ([after iOS 13.4 changes](https://github.com/skywinder/ActionSheetPicker-3.0/blob/develop/Pickers/ActionSheetDatePicker.h#L48)) and you can set it according to your app needs.
You can set `picker.datePickerStyle = .wheels` to get the wheels style.

**Comment by tkirby** [comment]
Didn't realize this was a dupe.

**Comment by skywinder** [comment]
if it's common case, maybe we should specify it in readme / migration guides

**Comment by noorulain17** [comment]
> if it's common case, maybe we should specify it in readme / migration guides

@skywinder Sure
