### ISSUE TITLE
SPM: Cannot find type 'ActionSheetStringPicker' in scope

### ISSUE THREAD

**Issue by rextremotabaresDtt** [skywinder/ActionSheetPicker-3.0#512]
I'm currently trying to migrate from Cocoapods to SPM but got this error `Cannot find type 'ActionSheetStringPicker' in scope` after adding SPM module. I've tried to import CoreActionSheetPicker but seems empty and apparently it cannot resolve its headers. How can you use SPM with ActionSheetPicker-3.0?

**Comment by noorulain17** [comment]
I'll check why in SPM all classes are not showing.

**Comment by unwire-ios-team** [comment]
It is probably because 'Pickers' folder is outside `CoreActionSheetPicker` folder, which is declared as root source folder for package.

**Comment by noorulain17** [comment]
@unwire-ios-team yes you're right. Because the existing structure for `CoreActionSheetPicker` & `Picker` folders are not within the same folder. This needs a fix. I'll work on it tonight.

**Comment by Tommecpe** [comment]
@noorulain17 did you find a way to fix it ? I've got the same error.

**Comment by noorulain17** [comment]
Hey @Tommecpe actually I got busy with the BN release, hence didn't get a chance to look into it yet.

**Comment by noorulain17** [comment]
@Tommecpe / @rextremotabaresDtt / @unwire-ios-team 
https://github.com/skywinder/ActionSheetPicker-3.0/pull/517

**Comment by losernobody** [comment]
This issue is observed in version '2.7.1'. Can anyone point out how to fix this?
