### ISSUE TITLE
Presenting picker fails when picker is presented within modally presented view controller on iPad (iOS 13.7) with ActionSheetPicker version 2.6.1.

### ISSUE THREAD

**Issue by xjki** [skywinder/ActionSheetPicker-3.0#513]
Configuration: Xcode 11 / ActionSheetPicker 2.6.1 / iPad with iOS 13.7

Assuming you want to use UISplitViewController which presents modal editing interface (UIViewController within UINavigationController presented with pageSheet/formSheet modal presentation style), attempt to present picker in UIViewController will fail.

Console log message "Warning: Attempt to present <UIViewController> on 
<UISplitViewController:> which is already presenting <UINavigationController: >

This is due to changes introduced in [AbstractActionSheetPicker presentPopover:] method in version 2.6.1 - see relevant commit (starting from line 792):
https://github.com/skywinder/ActionSheetPicker-3.0/commit/f6ec6f0d62e76c0545859d0eac43c8f00f7fffec#diff-48a7cb226b991c0a3ddda4b756c7c366R843

[self rootViewController] in the method in this this case would return UISplitViewController that already has one modally presented UIViewController.

Previous implementation presented popover from the rect that was defined by container view (e.g. button that calls picker)  that was within the modal view controller hierarchy.

**Comment by xjki** [comment]
CC: @cutmail

**Comment by noorulain17** [comment]
cc: @xjki 
https://github.com/skywinder/ActionSheetPicker-3.0/pull/519

> CC: @cutmail
