### ISSUE TITLE
upside down portrait mode displays incorrectly on iPhone 4S device/emulator

### ISSUE THREAD

**Issue by ginobean** [skywinder/ActionSheetPicker-3.0#52]
when both portrait mode and upside down portrait mode are enabled on my app, on the iPhone 4S device (as well as the emulator), the upside down portrait mode actually displays the action sheet picker
in the wrong orientation, so that it appears upside down, with respect to the rest of the app.

**Comment by skywinder** [comment]
@ginobean fixed in `1.5.0`
