### ISSUE TITLE
Minimum iOS version

### ISSUE THREAD

**Issue by ddaddy** [skywinder/ActionSheetPicker-3.0#522]
In your last commits, did you mean to bump the minimum iOS version to 12?

The lowest Xcode 12 will allow is iOS 9, however it's auto updater sets it to 12.0 which means when building with Carthage it is not building the armv7 slice.

Can I/you change it back to 9.0 minimum?

**Comment by noorulain17** [comment]
@ddaddy will you please share the commit hash/link here in this thread?

**Comment by ddaddy** [comment]
Commit #520 8c6c57b0e4b3a9b4de001e49c4351fe526211cfc
'Update to recommended settings'

**Comment by noorulain17** [comment]
@ddaddy `ActionSheetPicker-3.0` had dropped support for iOS 8.0 in #499.
Rest for Carthage related issue, please open the PR for the fix with the screenshot of the issue.
Thanks :)

**Comment by ddaddy** [comment]
Hitting the update button in xcode 12 automatically sets minimum to 12.0 unless you untick the box. I'm guessing no one checked when doing that.
I'll submit a PR setting it back to 9.0

**Comment by noorulain17** [comment]
Thanks

**Comment by skywinder** [comment]
Looks legit. @noorulain17 since you managed repo, feel free to merge!

**Comment by noorulain17** [comment]
@skywinder Sure will do 🙂

**Comment by pushian** [comment]
![Screenshot 2021-12-03 at 2 10 53 PM](https://user-images.githubusercontent.com/16488850/144554760-da410945-1f89-4822-8866-6018625e7c3a.png)
For the latest version, no armv7 slice is built for xcframework which will cause build error of the following:

ld: warning: ignoring file /Users/yangfanliu/Library/Developer/Xcode/DerivedData/FooyoSDKExample-dtnhbajhphjudubbvjbuqrtniiwv/Build/Intermediates.noindex/ArchiveIntermediates/FooyoTestSDK/BuildProductsPath/Release-iphoneos/CoreActionSheetPicker.framework/CoreActionSheetPicker, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_ActionSheetDatePicker", referenced from:
      objc-class-ref in ItinerarySettingViewController.o
      objc-class-ref in CreatePlanViewController.o
  "_OBJC_CLASS_$_ActionSheetStringPicker", referenced from:
      objc-class-ref in ItinerarySettingViewController.o
      objc-class-ref in CreatePlanViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
