### ISSUE TITLE
tapDismissAction broken after 2.5.1

### ISSUE THREAD

**Issue by danh-geo** [skywinder/ActionSheetPicker-3.0#526]
Hi, thanks for this awesome lib.

Using Xcode 12.1, iPhone 8 - 14.1 Simulator.

I'm using the `actionSheet?.tapDismissAction = .cancel` which worked fine up to and including version 2.5.1 when tapping above the actionsheet, it would call my cancel block. However, using any version after 2.5.1 (including the most recent 2.7.1) when I tap above the actionsheet, it **does** dismiss the actionsheet **BUT** it does not call my cancel block anymore.

e.g.
```
let actionSheet = ActionSheetDatePicker(
            title: title,
            datePickerMode: .time,
            selectedDate: date,
            doneBlock: doneBlock,
            cancel: cancelBlock,
            origin: origin)
actionSheet?.tapDismissAction = .cancel
actionSheet?.show()
```
It doesn't work with a string picker either.

Dan

**Comment by danh-geo** [comment]
The issue seems to be that `SWActionSheet.m` adds the following code:

(Lines 241-245)
```
[_actionSheet removeGestureRecognizer:self.dismissTap];
self.dismissTap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(dismissActionSheet)];
self.dismissTap.delegate = self;
[_actionSheet addGestureRecognizer:self.dismissTap];
```

Which intercept the tap and ignores the logic in `AbstractActionSheetPicker.m`
(Lines 328-331 in my case for the cancel block)
```
self.actionSheet.window.userInteractionEnabled = YES;
UITapGestureRecognizer *tapAction = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(actionPickerCancel:)];
tapAction.delegate = self;
[self.actionSheet.window addGestureRecognizer:tapAction];
```

**Comment by noorulain17** [comment]
Thanks for identifying this issue.
I’ll look into this within this week.

**Comment by noorulain17** [comment]
@danh-geo please test the changes of #528
