### ISSUE TITLE
OK Button Locale not change

### ISSUE THREAD

**Issue by sagarzala123** [skywinder/ActionSheetPicker-3.0#533]
OK Button language not change in French

![OK Not Change](https://user-images.githubusercontent.com/13331874/106239607-ed09fa00-6228-11eb-8f91-5d5a94cfa680.png)

**Comment by noorulain17** [comment]
@sagarzala123 are you using `ActionSheetLocalePicker` or `ActionSheetStringPicker`?

**Comment by sagarzala123** [comment]
I am using `ActionSheetStringPicker`.

**Comment by wei18** [comment]
Verified on version [2.7.4](https://github.com/skywinder/ActionSheetPicker-3.0/releases/tag/2.7.4)

ref:
<img width="348" alt="image" src="https://github.com/skywinder/ActionSheetPicker-3.0/assets/11254896/2a1cd591-460d-44b1-8638-181aacdbe682">

code:
https://github.com/skywinder/ActionSheetPicker-3.0/blob/9c61ff485c40a63b0bf6828370982a7d44684f19/CoreActionSheetPicker/CoreActionSheetPicker/Pickers/AbstractActionSheetPicker.m#L140

Close the issue
