### ISSUE TITLE
Current date is not available on compact Date picker style iOS 14.4 & above

### ISSUE THREAD

**Issue by yevgeniipasko** [skywinder/ActionSheetPicker-3.0#534]
The picker does not contain current date selected on compact mode

Code to reproduce:
```
        let picker = CoreActionSheetPicker.ActionSheetDatePicker(title: "Hi", datePickerMode: .date, selectedDate: Date(), doneBlock: nil, cancel: nil, origin: view)
        picker?.datePickerStyle = .compact
        picker?.show()
```
<img width="250" alt="Screenshot 2021-03-26 at 18 31 52" src="https://user-images.githubusercontent.com/70582179/112663574-ac61e200-8e61-11eb-8a67-b1b8e9d21c5e.png">

When I click this white empty view it redirects to compact picker view
<img width="250" alt="Screenshot 2021-03-26 at 18 31 58" src="https://user-images.githubusercontent.com/70582179/112663705-cef3fb00-8e61-11eb-9fa4-724460e55e91.png">

**Comment by noorulain17** [comment]
Fixed in #541
