### ISSUE TITLE
"exported: true has no effect in '_specialize' attribute" Issue at Xcode 12.5

### ISSUE THREAD

**Issue by havetherain** [skywinder/ActionSheetPicker-3.0#536]
![image](https://user-images.githubusercontent.com/53065255/116171541-f16c8300-a743-11eb-9489-73b4e62ec14e.png)

**Comment by havetherain** [comment]
this issue about CryptoSwift 
I need fast solution

**Comment by havetherain** [comment]
Sorry I was mistake

**Comment by liangbsu** [comment]
how you fix it?
