### ISSUE TITLE
Not working with Swift Package Manager [bug]

### ISSUE THREAD

**Issue by swifthing** [skywinder/ActionSheetPicker-3.0#537]
If I use Cocoapod it is working

But if I use SPM I have an error:
<img width="1119" alt="Capture d’écran 2021-04-29 à 10 57 24" src="https://user-images.githubusercontent.com/66845529/116526573-0713b100-a8da-11eb-9f3d-65d0d1cb9c6c.png">

Module is correctly installed in SPM:
<img width="982" alt="Capture d’écran 2021-04-29 à 10 58 21" src="https://user-images.githubusercontent.com/66845529/116526605-0ed35580-a8da-11eb-878e-063e7b8cd1a0.png">

The error is showing even after I cleaned and builded again

**Comment by vewert** [comment]
I was getting this too. I changed the import to:

`import CoreActionSheetPicker`

which got rid of that error, but then wherever I tried to use the pickers I got the following errors like: 

"Cannot find 'ActionSheetStringPicker' in scope"

**Comment by vewert** [comment]
I also noticed the following compile error:

`/Users/vewert/Library/Developer/Xcode/DerivedData/iPWMinder-hbyymbcbqlydgwcgjgemijqtdgct/Build/Intermediates.noindex/GeneratedModuleMaps-iphonesimulator/CoreActionSheetPicker.modulemap:2:10: Umbrella directory '/Users/vewert/Library/Developer/Xcode/DerivedData/iPWMinder-hbyymbcbqlydgwcgjgemijqtdgct/SourcePackages/checkouts/ActionSheetPicker-3.0/CoreActionSheetPicker/include' not found`

I'm not sure if that is related.

**Comment by swifthing** [comment]
Up

**Comment by kkolontai** [comment]
the same for. me

**Comment by muh-bilal** [comment]
Happening for me as well.
