### ISSUE TITLE
Remove the pieces of the code for less than the Deployment Target

### ISSUE THREAD

**Issue by jolyot** [skywinder/ActionSheetPicker-3.0#538]
In the latest release, the `Deployment Target` is `iOS9`, but there are pieces of code in the library for less than this Target OS. For example, the following section: 
https://github.com/skywinder/ActionSheetPicker-3.0/blob/e0f58d81896bf6e7857f9edc41ab3fcb6ef4629e/CoreActionSheetPicker/CoreActionSheetPicker/Pickers/SWActionSheet.m#L264-L277

I think it is better to remove this code since it does not build on iOS  less than the `Deployment Target`.

**Comment by noorulain17** [comment]
Good point.
@jolyot do you want to open a PR for this?

**Comment by jolyot** [comment]
@noorulain17 
Yes, I would like to open a PR for this.

**Comment by noorulain17** [comment]
Thanks a lot @jolyot. Assigning this issue to you and looking forward for the PR.
