### ISSUE TITLE
Change tint color / font color of Done / Cancel buttons

### ISSUE THREAD

**Issue by nneuberger1** [skywinder/ActionSheetPicker-3.0#54]
I'd like to change the font color of the text on the picker "Cancel" and "Done" buttons.  How can they be changed directly.

My application typically has black menus with white text on the menu.

I'm calling the following:

    [ActionSheetStringPicker showPickerWithTitle:@"A-Trapezoidal (A-Trap)" rows:self.atrapNamesArray initialSelection:0 target:self successAction:@selector(atrapWasSelected:element:) cancelAction:@selector(actionPickerCancelled:) origin:self.view];

I do have a workaround by calling this line of code, but it causes havoc elsewhere inside my app.  i end up putting this in multiple locations and switching the UIColor to do it.

    UIBarButtonItem *barButtonAppearance = [UIBarButtonItem appearance];
    [barButtonAppearance setTintColor:[UIColor blackColor]];

I'd be fine with changing the background color as an alternative.

**Comment by rustanacexd** [comment]
+1 yeah this is a must have feature I think

**Comment by jrustonapps** [comment]
Also would very much appreciate this.

**Comment by skywinder** [comment]
@rustanacexd , @jrustonapps ok, I reopen this issue, since there is at least 3 person mention about this..  I can't promise, that I will implement it in near future, but I'm open for a pull requests and you can implement this feature by yourself also. (as I mention above  by methods: `setCancelButton:` and `setDoneButton:` )

**Comment by tobedev** [comment]
A working workaround you can use is to set a tint color to the main window that hosts the actionpicker, in the SWActionSheet.m file as follows:

```objectivec
- (UIWindow *)window
{
    if ( SWActionSheetWindow )
    {
        return SWActionSheetWindow;
    }
    else
    {
        return SWActionSheetWindow = ({
            UIWindow *window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
            window.windowLevel        = UIWindowLevelAlert;
            window.backgroundColor    = [UIColor clearColor];
            
            // Window Tint Color.
            [window setTintColor:[UIColor whatEverColor]];

            window.rootViewController = [SWActionSheetVC new];
            window;
        });
    }
}
```

PS. This will set the tint color of the default buttons in every single instance of actionsheetpicker in your project.

**Comment by kivannc** [comment]
You can set the color for a single button by using setTitleTextAttiributes. Here is the example 

```objective-c
    UIBarButtonItem *barButtonNext1 = [[UIBarButtonItem alloc]
                                       initWithTitle:NSLocalizedString(@"Next", nil)
                                       style:UIBarButtonItemStylePlain
                                       target:self
                                       action:@selector(genderNextTapped:element:)];
    
    [barButtonNext1 setTitleTextAttributes:@{NSForegroundColorAttributeName : [UIColor blackColor]} forState:UIControlStateNormal];
    [self.pickerGender setDoneButton:barButtonNext1];
```

**Comment by tbaranes** [comment]
+1, I'd love to have this feature too without to have override the native buttons.

**Comment by zerodiff** [comment]
For what it's worth, another workaround is to override this method from `AbstractActionSheetPicker` in whatever subclass of a subclass you can create to set whatever color you want in a subclass of any of the pickers:
```
- (UIBarButtonItem *)createButtonWithType:(UIBarButtonSystemItem)type target:(id)target action:(SEL)buttonAction
{
    UIBarButtonItem *barButton = [super createButtonWithType:type target:target action:buttonAction];
    barButton.tintColor = [UIColor whiteColor];
    return barButton;
}
```

This will keep the default button behavior but change the styles. Of course, you could also make a property of your subclass, etc. I know people are all about composition over inheritance, but hackers gotta hack.

In any case, this a very useful library and saves a lot of time.

**Comment by ghysrc** [comment]
+1, I was just told to change the tint color.

**Comment by mathieudebrito** [comment]
+1

**Comment by Maxatma** [comment]
ActionSheetStringPicker does not conform to the UIAppearanceContainer protocol 
+1 would be nice have this protocol to set same colours for all pickers in app

**Comment by hanishassim** [comment]
+1

**Comment by mikecole20** [comment]
It would still be nice to set the font without having to override the button completely. If you do provide a custom button, do the `doneBlock` and `cancel` closures still get called? I ask because `UIBarButtonItem`s ask for a target and action (a selector).

**Comment by tbaranes** [comment]
Yes, you don't have to set a selector to your custom `UIBarButton` if you have a `doneBlock` set. The block will be called.
