### ISSUE TITLE
Unable to build archieve on Xcode 14.3

### ISSUE THREAD

**Issue by usmanabid94** [skywinder/ActionSheetPicker-3.0#558]
error when building archieve:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/apple/Library/Developer/Xcode/DerivedData/project-buupzkysftlvrqacsnwvthsdrcgh/Build/Intermediates.noindex/ArchiveIntermediates/project/IntermediateBuildFilesPath/project.build/Release-iphoneos/project.build/Script-0DBAEA91FF140668FEA2C095.sh (in target 'project' from project 'project')
    cd /Users/apple/Desktop/Data/project-IOS-App
    /bin/sh -c /Users/apple/Library/Developer/Xcode/DerivedData/project-buupzkysftlvrqacsnwvthsdrcgh/Build/Intermediates.noindex/ArchiveIntermediates/project/IntermediateBuildFilesPath/project.build/Release-iphoneos/project.build/Script-0DBAEA91FF140668FEA2C095.sh

mkdir -p /Users/apple/Library/Developer/Xcode/DerivedData/project-buupzkysftlvrqacsnwvthsdrcgh/Build/Intermediates.noindex/ArchiveIntermediates/project/BuildProductsPath/Release-iphoneos/project.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ActionSheetPicker_3_0.framework" "/Users/apple/Library/Developer/Xcode/DerivedData/project-buupzkysftlvrqacsnwvthsdrcgh/Build/Intermediates.noindex/ArchiveIntermediates/project/InstallationBuildProductsLocation/Applications/project.app/Frameworks"
building file list ... rsync: link_stat "/Users/apple/Desktop/Data/project-IOS-App/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ActionSheetPicker_3_0.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/c2cb9645-dafc-11ed-aa26-6ec1e3b3f7b3/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by usmanabid94** [comment]
@xjki @andreabusi @skywinder @noorulain17

**Comment by usmanabid94** [comment]
@skywinder yes using cocoa pods and also using Xcode 14.3.1 and still facing the same issue

**Comment by usmanabid94** [comment]
what,s the latest version for this library you are using @skywinder ??

**Comment by usmanabid94** [comment]
@andreabusi mentioned that it works can you get in touch in with him on this @skywinder

**Comment by usmanabid94** [comment]
@andreabusi @skywinder i am using the latest version of Xcode 14.3.1 and 2.7.1 version of the action sheet picker still facing the same issue.

**Comment by andreabusi** [comment]
@usmanabid94 try to delete the entire "Pods" folder from your project and do a fresh "pod install" command (also remove derived data from Xcode)

**Comment by usmanabid94** [comment]
@andreabusi @skywinder @xjki @noorulain17 
It was an issue due to files missing in Xcode 14.3 i fixed it now you can also close it and steps to fix it are mentioned below :
9

For the people facing error in Xcode after update to 14.3.

In your xcode, Go to PODS folder :
Target Support Files => Pods-{Your Project} => Pods-{Your Project}-frameworks

Change

source="$(readlink "${source}")"
this :

source="$(readlink -f "${source}")"

**Comment by andreabusi** [comment]
@usmanabid94 ok thanks for the reporting. This issue is not already solved in cocoapods 1.12.1? 

https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1

**Comment by usmanabid94** [comment]
@andreabusi i tried to use the latest cocoapods version also but invain i recommend everyone to use this fix because it will save a lot of time and issues that might arise by some other solutions
