### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by wenfeng-duan** [skywinder/ActionSheetPicker-3.0#570]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Does this SDK need a privacy manifest? If yes, is there any plans to add a privacy manifest?

Thanks,
Duan

**Comment by wei18** [comment]
Thank you for bringing this up. Currently, this project needs everyone's collaboration, and if someone submits a Pull Request regarding the Privacy Manifest, I would be happy to release a new version.

**Comment by youngToMaturity** [comment]
need update. It's due on May 1st. 😂

**Comment by wei18** [comment]
I ran `mint run techinpark/ios_privacy_manifest_scanner`, and the scanner returned `no results found`.

> Does this SDK need a privacy manifest?

No
