### ISSUE TITLE
Error in v2.7.3 compilation issue

### ISSUE THREAD

**Issue by bhaskar-ayla** [skywinder/ActionSheetPicker-3.0#571]
We are using ActionSheetPicker-3.0 (2.7.3) here we are getting below mentioned issue, this was not there in v2.7.1.

<img width="1319" alt="ActionSheetPicker-3 0 (2 7 3)_Issue" src="https://github.com/skywinder/ActionSheetPicker-3.0/assets/85285422/1608b890-0103-42b9-9971-11e24fb9dac4">

**Comment by Wei18** [comment]
Thanks for report!
The [build job](https://github.com/skywinder/ActionSheetPicker-3.0/actions/runs/7834237992/job/21376999520) looks great. 
I will check it later.

**Comment by Wei18** [comment]
As commented before, the job was passed and I can't reproduce the issue.
Could you provide more info like cocoapods version, xcode version, etc.

On the other hand, I made some changes and observed behavior as below.
- Found warns on ActionSheetPicker-3.0.xcworkspace, scheme CoreActionSheetPicker 
```objc
import "AbstractActionSheetPicker.h"
```
<img width="518" alt="image" src="https://github.com/skywinder/ActionSheetPicker-3.0/assets/11254896/3bec8fe4-e5cf-4bff-99be-13b645ca6f5b">

- Passed on SPM, ActionSheetPicker-3.0.xcworkspace, scheme CoreActionSheetPicker,
but the job `build cocoapods` was failed 
```objc
import <CoreActionSheetPicker/AbstractActionSheetPicker.h>
```
<img width="987" alt="image" src="https://github.com/skywinder/ActionSheetPicker-3.0/assets/11254896/55bb6fdf-a9b0-42f0-b1c1-eb350c681ffa">
