### ISSUE TITLE
Issue with ActionSheetStringPicker: "Failed to find Picker view's window" for iPad

### ISSUE THREAD

**Issue by luckyhexalitics** [skywinder/ActionSheetPicker-3.0#578]
Hello ,

I hope this message finds you well. I am currently encountering an issue with the ActionSheetStringPicker library in my iOS project. I have thoroughly tested and integrated the picker, and it works correctly on the iOS simulator. However, when testing on a real device, I consistently encounter the following error:

"Failed to find Picker view's window. This may cause a memory leak."

**Comment by Karim-ezzedine** [comment]
I'm facing the same problem

**Comment by Michael-Lumpp** [comment]
I am getting the same issue! Has anyone solved it??

**Comment by mlch911** [comment]
Could you provide a demo project?

**Comment by wei18** [comment]
Try [2.7.5](https://github.com/skywinder/ActionSheetPicker-3.0/releases/tag/2.7.5)

**Comment by Michael-Lumpp** [comment]
Sorry just wanted to add one more thing, so for example if i'm using this
code (I simplified the code to make it easier but kept the action sheet)

*func* ShowMyPopup()

    {

        *//some code here*



        *let* actionSheetPicker = ActionSheetStringPicker(title: "",
rows:  shiftPeriods,
initialSelection: shiftPeriodSelectedIndex,

                                                        doneBlock: {

                                                            picker, index,
selectedValue *in*

                                                            *self*.
txtSomething.text = (selectedValue *as*! String).description

                                                            *self*.
selectedSomething =
*self*._someService.GetSomethingBySelectedValue(selectedValue
*as*! String)

        }, cancel: { ActionStringCancelBlock *in* *return* }, origin:
txtSomething)!



        *let* btnSelect = UIBarButtonItem(title: Localized("Select"), style:
UIBarButtonItem.Style.plain, target: *self*, action: Selector(""))

        actionSheetPicker.setDoneButton(btnSelect)

        actionSheetPicker.show()

    }



Chat GPT is saying I should be putting [weak self] above, specifically here:


  doneBlock: {

                                                          *[weak
self]*  picker,
index, selectedValue *in*



Would you agree with this and say this is best practice? thank you!
