### ISSUE TITLE
How to change font of picker data rows?

### ISSUE THREAD

**Issue by thatsagreatapp** [skywinder/ActionSheetPicker-3.0#58]
I have seen plenty of examples in your sample project detailing how to customize buttons over the picker but there aren't any examples showing how to change the font of the data row in the action sheet. Any help is highly appreciated.

Thanks,
Jack.

**Comment by arturdev** [comment]
+1

**Comment by softwhisper** [comment]
Give the user the chance to pass a block as a delegate for the pickerView viewForRow will do the thing.

I modify the pod adding this code to the StringPicker
```
- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view {
    
    id obj = (self.data)[(NSUInteger) row];
    UILabel* lbl = (UILabel*)view;
    
    if (!lbl) {
        lbl = [[UILabel alloc] init];
        [lbl setFont:[UIFont fontWithName:@"Helvetica" size:16]];
        [lbl setAdjustsFontSizeToFitWidth:YES];
        [lbl setMinimumScaleFactor:0.5f];
        lbl.numberOfLines = 3;
    }
    
    if ([obj isKindOfClass:[NSString class]])
        tView.text = obj;
    
    if ([obj respondsToSelector:@selector(description)])
        tView.text = [obj performSelector:@selector(description)];
    
    return tView;
}
```

**Comment by nvkiet** [comment]
+1

**Comment by skywinder** [comment]
@softwhisper Thanks for solution. Pretty busy to investigate this feature right now. But feel free to make a PR. :wink:

**Comment by skywinder** [comment]
Hello everybody, check @ainopara PR: #195 with this PR you can change whatever you want, not only font. :wink:

**Comment by skywinder** [comment]
I reopen it since there is a several request for this feature.

**Comment by bb-git** [comment]
I'm using this for my stringPicker and it works great:
picker.pickerTextAttributes = @{NSForegroundColorAttributeName: [UIColor whiteColor],
                                    NSFontAttributeName:[UIFont systemFontOfSize:21.0],};

But it does not work for my Datepicker. Is this a known issue?
Thanks

**Comment by skywinder** [comment]
@bb-git because datepicker uses native Apple Date picker, that doesn't support this option.
