### ISSUE TITLE
Not working with Swift Package Manager on Xcode 15.4

### ISSUE THREAD

**Issue by laxmansahni** [skywinder/ActionSheetPicker-3.0#580]
if I use Swift Package Manager, I have an error on Xcode 15.4:

<img width="856" alt="spm-error" src="https://github.com/user-attachments/assets/04609be4-6c62-46ce-b6c8-99330623268b">

version: 2.7.4

**Comment by wei18** [comment]
@laxmansahni 

Currently, you can use `import CoreActionSheetPicker`. I'd like to fix this in the future.
