### ISSUE TITLE
Ipad causing *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to find Picker view's window. This may cause a memory leak.'

### ISSUE THREAD

**Issue by Michael-Lumpp** [skywinder/ActionSheetPicker-3.0#581]
Hi all,
@skywinder  @Wei18 
This works perfectly fine for iPhone, even latest Swift5, however trying now on latest iPad, I get this error:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to find Picker view's window. This may cause a memory leak.'

It seems to be hitting this block:

```
- (void)addTapDismissAction {
	if (!self.pickerView) {
		NSAssert(_pickerView != NULL, @"Picker view failed to instantiate, perhaps you have invalid component data.");
		return;
	}
	if (self.windowTapActionRetryCount > 10) {
		NSAssert(NO, @"Failed to find Picker view's window. This may cause a memory leak.");
	}
	if (!self.pickerView.window) {
		self.windowTapActionRetryCount += 1;
		dispatch_async(dispatch_get_main_queue(), ^{
			[self addTapDismissAction];
		});
		return;
	}


```

I am calling the code like such:

```
 self.workplacePicker = ActionSheetStringPicker(title: "", rows:  workplaces, initialSelection: workplaceSelectedIndex,
              
                doneBlock: {
                    picker, index, value in
                   //my code here
                    
                   self.Refresh()
                },
                cancel: { ActionSheetCancelBlock in
                    
                   self.workplacePicker?.dismiss()
                  
                },
                origin: lblJob)
            
              let btnCancel = UIBarButtonItem(title: Localized("Cancel"), style: UIBarButtonItem.Style.plain, target: self, action: nil)
              let btnEdit = UIBarButtonItem(title: Localized("Edit"), style: UIBarButtonItem.Style.plain, target: self, action: #selector(JobSettingsViewController.btnEditWorkplace(_:)))
              let btnAddNew = UIBarButtonItem(title: Localized("AddNew"), style: UIBarButtonItem.Style.plain, target: self, action: #selector(JobSettingsViewController.btnAddWorkplace(_:)))
              let btnSelect = UIBarButtonItem(title: Localized("Select"), style: UIBarButtonItem.Style.plain, target: self, action: nil)
           
            workplacePicker!.setCancelButton(btnCancel)
            workplacePicker!.setDoneButton(btnSelect)
              
              // Ensure the view is fully laid out
              self.view.setNeedsLayout()
              self.view.layoutIfNeeded()

              DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                  guard let picker = self.workplacePicker else { return }
                  picker.show()
                 
                  btnCancel.width = picker.toolbar.frame.width / 5
                  btnEdit.width = picker.toolbar.frame.width / 6
                  btnAddNew.width = picker.toolbar.frame.width / 6
                  btnSelect.width = picker.toolbar.frame.width / 6
                  picker.toolbar.items?.insert(btnEdit, at: 1)
                  picker.toolbar.items?.insert(btnAddNew, at: 2)
              }
```

Any ideas or support? thank you so much

**Comment by wei18** [comment]
@mlch911
- It seems to have been introduced in https://github.com/skywinder/ActionSheetPicker-3.0/pull/561. 
Could you take a look?

**Comment by mlch911** [comment]
@Michael-Lumpp 
I have tried your code. And it wouldn't trigger the assert you mentioned. 

BTW, your code could not build. Did you write any extension code to `ActionSheetStringPicker`? We don't have the `dismiss` function.

Could you provide a demo project that can reproduce this assert? Maybe just use our demo app.

**Comment by wei18** [comment]
@mlch911 

Please feel free to check related issue.

- #578

**Comment by ddaddy** [comment]
I'm also seeing this crash on iPad when presenting from a `UITableViewCell`

**Comment by mlch911** [comment]
> I'm also seeing this crash on iPad when presenting from a `UITableViewCell`

Could you provide a demo project?

**Comment by ddaddy** [comment]
Sure, here you go.
Nothing fancy, just run it on the iPad simulator.

[UIPicker Test.zip](https://github.com/user-attachments/files/17599332/UIPicker.Test.zip)

**Comment by wei18** [comment]
Try [2.7.5](https://github.com/skywinder/ActionSheetPicker-3.0/releases/tag/2.7.5)

**Comment by Michael-Lumpp** [comment]
Thanks so much sorry for the delay in reply here. I noticed that when I tap
into the pages that use ActionSheetPicker, the memory seems to increase and
never really goes back down. It's not huge, but enough to build up over
time, and eventually it does crash but it takes a while. Is there a latest
version I should be referencing that fixes issues such as memory leaks,
the above iPad issue, etc?

Thanks so much!

**Comment by kashifhisam** [comment]
I think `addTapDismissAction` is not needed for iPad. So we can simply do following in `showActionSheetPicker`:

`    if (!IS_IPAD)
        [self addTapDismissAction];
`
