### ISSUE TITLE
Swift implementation of Blocks/Closures in ActionSheetStringPicker yeilds and error

### ISSUE THREAD

**Issue by CJKinni** [skywinder/ActionSheetPicker-3.0#66]
When using ActionSheetStringPicker.showPickerWithTitle along with doneBlock, I am hitting an error: 

Missing argument for  parameter 'cancelAction' in call

**Comment by fika4life** [comment]
I am having the same issue. I get the error message. Missing argument for parameter cancelAction. There is no cancelAction in the example so I don't know what to do about this error. Here is my code.  Would be grateful for any help.  Thanks!


@IBAction func SchoolPicker(sender: AnyObject) {
        ActionSheetStringPicker.showPickerWithTitle("A String", rows: anArray, initialSelection: 1,
            doneBlock: {
            picker, value, index in
          
            println("value = \(value)")
            println("index = \(index)")
            println("picker = \(picker)")
            return
            },cancelBlock: { ActionStringCancelBlock in return } ,origin:sender)
        
    }
