### ISSUE TITLE
NSDate from TimePicker is 4 hours later than selected

### ISSUE THREAD

**Issue by djbrooks111** [skywinder/ActionSheetPicker-3.0#69]
I followed the code in your example to implement a time picker and here is my code:

```
-(void)selectATime:(id)sender {
    NSInteger minuteInterval = 5;
    NSInteger referenceTimeInterval = (NSInteger)[self.selectedTime timeIntervalSinceReferenceDate];
    NSInteger remainingSeconds = referenceTimeInterval % (minuteInterval * 60);
    NSInteger timeRoundedToFiveMinutes = referenceTimeInterval - remainingSeconds;
    if (remainingSeconds > ((minuteInterval * 60) / 2)) {
        timeRoundedToFiveMinutes = referenceTimeInterval + ((minuteInterval * 60) - remainingSeconds);
    }
    self.selectedTime = [NSDate dateWithTimeIntervalSinceReferenceDate:(NSTimeInterval)timeRoundedToFiveMinutes];

    ActionSheetDatePicker *datePicker = [[ActionSheetDatePicker alloc] initWithTitle:@"Select a time" datePickerMode:UIDatePickerModeTime selectedDate:self.selectedTime target:self action:@selector(timeWasSelected:element:) origin:sender];
    datePicker.minuteInterval = minuteInterval;
    [datePicker showActionSheetPicker];
}

-(void)timeWasSelected:(NSDate *)selectedTime element:(id)element {
    self.selectedTime = selectedTime;
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"h:mm a"];
    self.timeLabel.text = [dateFormatter stringFromDate:selectedTime];
    [self.timeLabel sizeToFit];
    NSLog(@"%@", self.selectedTime);
}
```

Using the selector, I pick 4:00 AM and the label that I have successfully shows 4:00 AM, however, when I log self.selectedTime or selectedTime within timeWasSelected, the time outputted is 4 hours greater than it should be.  For 4:00 AM, I get this printout: 2014-10-08 08:00:00 +0000.  Clearly 8 AM /= 4 AM

**Comment by rohitb2427** [comment]
For those who did not get it.
Please go to ActionSheetDatePicker.m
and make the following changes in eventForDatePicker

- (void)eventForDatePicker:(id)sender
{
    if (!sender || ![sender isKindOfClass:[UIDatePicker class]])
        return;
    UIDatePicker *datePicker = (UIDatePicker *)sender;
    self.selectedDate = datePicker.date;
    NSTimeInterval timeZoneSeconds = [[NSTimeZone localTimeZone] secondsFromGMT];
    self.selectedDate = [_selectedDate dateByAddingTimeInterval:timeZoneSeconds];
    self.countDownDuration = datePicker.countDownDuration;
}
