### ISSUE TITLE
Dismiss action sheet by tapping on background

### ISSUE THREAD

**Issue by jklp** [skywinder/ActionSheetPicker-3.0#80]
The standard action sheet (UIActionSheet) has a behaviour whereby if you tap on the background (which is not the action sheet), it dismisses the sheet.  I think the same thing should occur for this library too.  

To implement, I put a tap recogniser on the window in the SWActionSheet class to detect the tap, but that seems a little messy, and was thinking there must be a cleaner way to do it - thoughts?

Thanks
Jerrold

**Comment by skywinder** [comment]
Hey, @jklp this feature implemented in #140 and will be merged soon!
