### ISSUE TITLE
Example projects failed to launch

### ISSUE THREAD

**Issue by shivanraptor** [skywinder/ActionSheetPicker-3.0#96]
After I opened `Example.xcworkspace`, and selected `ActionSheetPicker` project, click Launch on my iPhone 5s with iOS 8.1, it crashes at splash screen, with the following error:

```
dyld: Library not loaded: @rpath/CoreActionSheetPicker.framework/CoreActionSheetPicker
  Referenced from: /private/var/mobile/Containers/Bundle/Application/C2F8A2D8-0D95-43B5-B4B9-7CF6A71DFF22/ActionSheetPicker.app/ActionSheetPicker
  Reason: image not found
```

Tried to clean & rebuild, same error is shown.

p.s. Another project `ActionSheetPicker-iOS6-7` works fine. Using Xcode 6.1.

**Comment by Maxatma** [comment]
Just had this issue - still not fixed? why closed so?
